### ISSUE TITLE
Compatibility with Identity broke

### ISSUE THREAD

**Issue by MimzyFang** [Virtuoel/Pehkui#100]
Identity recently had an update which broke the compatibility with Pehkui
The last compatibility was on Pehkui's side that's why I'm bringing it up here
Issue on Identity's side:
https://github.com/Draylar/identity/issues/191

**Comment by Virtuoel** [comment]
Fixed in 60cb975218283ad3fc63bf1a6d50e60ed26727dc

**Comment by MimzyFang** [comment]
Thanks
