### ISSUE TITLE
[Forge] Pehkui crash minecraft

### ISSUE THREAD

**Issue by PrototypeGamin9** [Virtuoel/Pehkui#106]
hello im Prototype Gaming and i was trying to make a map with your mod and fabric work no problem but the person im making map for does not like fabric so im trying to use forge but it crash my minecraft every time i put it in my mods folder is there any way i can fix it or is it on your side of thing please help sincerely 
![Capthgfure](https://user-images.githubusercontent.com/84126142/118105055-8953a900-b3a1-11eb-9005-5e07604fb8fd.PNG)
prototype gaming

**Comment by ImSpaceLover** [comment]
Hello, i'm SpaceLover, I didn't know you're Prototype Gaming, thank you
Sorry, neither I can help you, nor the developer can without the game log. So send it, please

Sincerely,
Space Lover

**Comment by PrototypeGamin9** [comment]
im sorry it wont let mecopy the game logs
is there a way for me to sned it pls tell
![Cgfdsgapture](https://user-images.githubusercontent.com/84126142/118230888-e90a8c80-b453-11eb-9e7b-80d6912c2382.PNG)

**Comment by knightfury3000** [comment]
I have the exact same issue, and it won't even give me a crash log

**Comment by PrototypeGamin9** [comment]
same i have to open minecraft with logs in the setting
but wont let me copy all of it

**Comment by knightfury3000** [comment]
I can provide a mod list, but that's about it
apologies for the lack of information

**Comment by lag42** [comment]
it should still give you a latest.log file in your logs folder, and [pastebin](pastebin.com) should be able to take care of hosting it for you

for example here is [mine on the exact same issue](https://pastebin.com/Bd6dSZnj), lots of mods involved in this log unfortunately, will debug to see if it is a conflict and get a cleaner log later

**Comment by lag42** [comment]
further investigation shows this is a conflict between [two players one horse](https://www.curseforge.com/minecraft/mc-mods/two-players-one-horse) and pehkui on my end
[better log here](https://pastebin.com/M62yctr1)

**Comment by PrototypeGamin9** [comment]
NO REAL HELP HERE I SEE

**Comment by Virtuoel** [comment]
Should now be fixed in Pehkui 2.2.0. If you still run into problems, please open a new issue and make sure to include your full crash report.
