### ISSUE TITLE
Server crashing when I try to start it.

### ISSUE THREAD

**Issue by Thraxironhide** [Virtuoel/Pehkui#107]
Hi. I was using a mohist server on forge version 1.16.5 but it doesn't let me start the server and crashes every time. It worked yesterday but when I made a new server it just stopped working. https://mclo.gs/avSzY9K

**Comment by Virtuoel** [comment]
Should now be fixed by 1e9520e0bc245e29889ae5b7cc725db7790bf3b5 and 32b2c98343af20e09c849deb71957dbe365863cb
