### ISSUE TITLE
I was changing my size to 1000 and now my world keeps crashing how do i fix this?

### ISSUE THREAD

**Issue by azzles369** [Virtuoel/Pehkui#108]

**Comment by ImSpaceLover** [comment]
(Credits to Virtuoel) 
If you've got an unplayable scale, theres a command-based workaround in Pehkui 2.1.0 and newer that'll reset all your scales back to their default values.

/scale debug delete_scale_data username YourUsername
 If you're in singleplayer, enter a different world where you can use commands and run the above command with your username, then rejoin the world where you had the bad scale.

 If you're on a server, have someone that's able to use commands either run it ingame or through the server console, then log back into the server.
