### ISSUE TITLE
hello I have a question can I somehow reduce the blocks and myself?

### ISSUE THREAD

**Issue by rolmem** [Virtuoel/Pehkui#109]

**Comment by rolmem** [comment]
something like this
![2021-05-13 (2)](https://user-images.githubusercontent.com/83511419/118157547-1d6e5080-b434-11eb-930e-302b980387d1.png)
this is taken from the video

**Comment by rolmem** [comment]
and tama, so that you can break
the blocks in a normal state

**Comment by ImSpaceLover** [comment]
what

**Comment by ImSpaceLover** [comment]
can you write the same thing but in English?

**Comment by rolmem** [comment]
I translated it please help me

**Comment by ImSpaceLover** [comment]
I'm pretty sure this thing is made using Scaled Box View feature from Immersive Portals mod. Check the wiki to learn how to do it. https://github.com/qouteall/ImmersivePortalsMod/wiki/Portal-Customization#create-a-scaled-wrapping-zone

**Comment by rolmem** [comment]
thank you very much, I have been searching for information for several days, and the developers of immersive mod portals asked, only there was hope for you, thank you!!!
