### ISSUE TITLE
Pehkui and Size Entity Attributes are incompatible with each other.

### ISSUE THREAD

**Issue by sschr15** [Virtuoel/Pehkui#11]
[(Posted in the SEA repo as well)](https://github.com/MoriyaShiine/size-entity-attributes/issues/1)

Both Pehkui and Size Entity Attributes require mixing into `HorseBaseEntity` to modify a passenger's offsets. Both mods require it for the same reason, but since they both use `@ModifyConstant` with the same priority, they force only one of the two mods to succeed, which causes problems.

I will submit a PR soon to disable this mod's Mixin for `HorseBaseEntity` if it detects the other mod, and I will create a small bridge mod to sit between the two to provide compatibility.

**Comment by Virtuoel** [comment]
Since SEA has been discontinued and the author now recommends using Pehkui instead, this is effectively resolved.
