### ISSUE TITLE
Crash after entering portal

### ISSUE THREAD

**Issue by SodaSlimes** [Virtuoel/Pehkui#110]
So whenever I open the world with Pehkui and immersive portals installed, I enter a portal, and it seems to crash after a couple seconds saying "Error: java.lang.NoSuchMethodError: virtuoel.pehkui.api.ScaleData.of(Lnet/minecraft/class_1297;)Lvirtuoel/pehkui/api/ScaleData;
Exit Code: -1" 

any suggestions?

**Comment by Virtuoel** [comment]
You're using an old version of Immersive Portals. Update to Immersive Portals 0.90 or newer.
