### ISSUE TITLE
when i open the forge version it crashes

### ISSUE THREAD

**Issue by NZgamer2008** [Virtuoel/Pehkui#114]

**Comment by PrototypeGamin9** [comment]
they dont know what going on

**Comment by LinkZeldasGuard** [comment]
Same Problem here. Just wanted to finally play on my Forge Server <:( But take your time, Virtuoel!

**Comment by ImSpaceLover** [comment]
Virtuoel has nothing to do with this issue. It's just Immersive Portals' developer didn't add Pehkui compatibility.

**Comment by Virtuoel** [comment]
Should now be fixed in Pehkui 2.2.0. If you still run into problems, please open a new issue and make sure to include your full crash report.
