### ISSUE TITLE
Incompatibility between Resizing Potions and TwoPlayersOneHorse Mod

### ISSUE THREAD

**Issue by Meskino** [Virtuoel/Pehkui#115]
Minecraft Version: 1.16.5
Forge Version: 36.1.23
Pehkui Version: 2.1.0
Resizing Potions Version: 1.0
TwoPlayersOneHorse Version: 2.0.2
Log: [latest.log](https://github.com/Virtuoel/Pehkui/files/6505551/latest.log)

something prevents the game from starting up with these mods but I don't know

**Comment by Virtuoel** [comment]
Fixed in 8a2f68450d21a1fe4bd1df549f99acedd02c3c88
