### ISSUE TITLE
Add a Reach Scale Limit

### ISSUE THREAD

**Issue by qouteall** [Virtuoel/Pehkui#116]
If I extend reach using `/scale set pehkui:reach 5` and then the player is in big scale such as 30 the game will lag a lot in updating the targeted block. It's recommended to limit the reach to render distance to avoid the lag.

**Comment by Virtuoel** [comment]
Apparently the lag is mostly due to MC's raycasting to find what entity the player's looking at. Interestingly this no longer lags in 1.17 due to changes in how vanilla stores entities.
