### ISSUE TITLE
Crash when loading a world

### ISSUE THREAD

**Issue by PoolloverNathan** [Virtuoel/Pehkui#12]
Whenever I load into a world, it says Loading ... Saving world, and then crashes. This happens both on my "Placing carpets" world from after I installed Carpets, and the "Pehkui Madness" world that I created after that crash, thinking it was because the world was loaded without Pehkui. I also have Immersive Portals installed as I was hoping to make a shrinking station, but does not look like that's happening.

Crash logs:
[Placing carpets - crash-2020-08-07_15.30.19-client.txt](https://github.com/Virtuoel/Pehkui/files/5043353/crash-2020-08-07_15.30.19-client.txt)
[Pehkui Madness - crash-2020-08-07_15.33.59-client.txt](https://github.com/Virtuoel/Pehkui/files/5043354/crash-2020-08-07_15.33.59-client.txt)

**Comment by Virtuoel** [comment]
This has already been [fixed](https://github.com/gnembon/fabric-carpet/issues/352) on Carpet's end, but is unfortunately not yet released.
