### ISSUE TITLE
Can't hit entities with scale width >= 20

### ISSUE THREAD

**Issue by eyyymann** [Virtuoel/Pehkui#120]
Could you add the ability to change the hitbox independently from the width and height? Because as of now, the only way I can sometimes hit entities (players to be specific) with scales of 20 or greater, is spam-hitting them from below. Don't know if it's possible, but it would be very much appreciated.

**Comment by Virtuoel** [comment]
I forget in which version this got fixed, but it is now fixed. Both in terms of adding a separate interaction hitbox scale and fixing not being able to hit entities that are very large.
