### ISSUE TITLE
Forge version is very very buggy

### ISSUE THREAD

**Issue by Gregdabrat** [Virtuoel/Pehkui#122]
On the forge version of the pehuki mod, traveling between portals does not work smoothly, and does not change size accordingly. If you set your scale smaller, it gives you a really choppy experience. Anyone know any fixes?

**Comment by Virtuoel** [comment]
Since you're mentioning portals, this is likely a duplicate of https://github.com/qouteall/ImmersivePortalsModForForge/issues/243, as the Forge version of Immersive Portals doesn't have Pehkui compatibility yet.
