### ISSUE TITLE
infinite title sceen loop on latest ver

### ISSUE THREAD

**Issue by RyanCR03** [Virtuoel/Pehkui#126]
https://pastelink.net/2we3v

**Comment by Virtuoel** [comment]
I think you, or one of the mods you have, might be using an older version of Cardinal Components API that doesn't work with newer versions of Fabric API. Can you try again with a newer CCAPI version in the mods folder, e.g. [2.8.3](https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3312678)?

**Comment by RyanCR03** [comment]
i wasnt using cardinal components in the first place but now its crashing but without a crash report
https://pastelink.net/2wjqs

**Comment by Virtuoel** [comment]
> Caused by: java.lang.ClassNotFoundException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found

Seems the issue you're now having is caused by some other mod that accidentally forgot to remove some example code. No idea which mod, but this does not appear to be a Pehkui issue anymore.
