### ISSUE TITLE
Issues with Movement Anti-Cheat

### ISSUE THREAD

**Issue by Limeyhoney** [Virtuoel/Pehkui#128]
At any scale other than 1, becoming more noticeable at scales lower than 0.75 and scales higher than 1.5, player movement in survival gets caught by Minecraft's movement anti-cheat. allow-flight doesn't disable the movement anti-cheat so that doesn't fix this issue either.

This causes the player's velocity to be constantly reset, making them unable to move, and of course the "Player moved wrongly!" spam in console.

This issue is listed in Known Issues with Growth, but it affects both scales, and at not very large differences from baseline.

**Comment by Virtuoel** [comment]
If by chance you have Performant installed as well, this is an issue on their end, and should be reported to them instead. If you do not have Performant, can you provide your Pehkui version, Forge/Fabric version, and the rest of your mod list?

**Comment by Limeyhoney** [comment]
> If by chance you have Performant installed as well, this is an issue on their end, and should be reported to them instead. If you do not have Performant, can you provide your Pehkui version, Forge/Fabric version, and the rest of your mod list?

Okay, I found the REAL issue at hand here, and it wasn't movement anti-cheat. Some mod incompatibility is causing opening the inventory to reset parts of your scaling. Immediately after opening the inventory, the motion gets reset to normal, then after sneaking the height and width gets reset. It doesn't seem like anything else gets reset though.

I'm searching for what mod is doing this, shall I close this issue and open a new one once I find the mod?

**Comment by Virtuoel** [comment]
This issue is fine I suppose. I can rename this one once you figure out the actual cause.

**Comment by Limeyhoney** [comment]
Huh, well I uninstalled all the mods, and reinstalled them one by one trying to find what mod was causing the issue. I got all the way through the modlist, and now I don't have the issue anymore. I guess that solves that?

**Comment by Limeyhoney** [comment]
I actually now have two instances of minecraft which are identical, and one has this problem while the other doesn't. I'm going to close this since it seems like there's no issue in the mod, just the installation.
