### ISSUE TITLE
I can only download the snapshot

### ISSUE THREAD

**Issue by AceShep** [Virtuoel/Pehkui#130]
I need 1.16.5

**Comment by ImSpaceLover** [comment]
okay

**Comment by ImSpaceLover** [comment]
download it

**Comment by camblycreeper** [comment]
If you're using the curseforge launcher you can go to the versions tab on the mod in question and select the right version. Then it may promt you to update, but don't do that or you may run into the same problem

**Comment by Virtuoel** [comment]
The latest version (2.2.1) supports all MC versions that Fabric exists for (1.17, 1.16.5, 1.15.2, and 1.14.4)
