### ISSUE TITLE
Fails to launch.

### ISSUE THREAD

**Issue by FROGGSSS** [Virtuoel/Pehkui#135]
![image](https://user-images.githubusercontent.com/85373094/120866830-b0e00080-c55e-11eb-9015-157b9cd3558a.png)

it fails to launch, I have the mods required, it won't launch.

**Comment by Virtuoel** [comment]
You're using either a Pehkui version that's too old, or are using the Forge version of Pehkui. Use the latest Fabric version of Pehkui (2.2.1) and it should work.
