### ISSUE TITLE
No API documentation.

### ISSUE THREAD

**Issue by StupidRepo** [Virtuoel/Pehkui#136]
So I want to use this in my mod but there is no documentation. How am I supposed to use it now?

**Comment by Alluysl** [comment]
In the meantime you can look at how other mods do it. An example for Fabric would be Extra Origins' [modify size power](https://github.com/MoriyaShiine/extra-origins/blob/master/src/main/java/moriyashiine/extraorigins/common/power/ModifySizePower.java).

**Comment by skylorbeck** [comment]
Additionally, the API page on the wiki is private. https://github.com/Virtuoel/Pehkui/wiki/Mod-Developer-API

**Comment by Meaxis** [comment]
It's still private after half a year, could it be finally made public?

**Comment by Dragon-Seeker** [comment]
@Virtuoel Any update on better documentation at all?

**Comment by RobotoSkunk** [comment]
This is still a problem

**Comment by StillLutto** [comment]
After 2 and a half years, there still isn't any documentation. Not even **one line of documentation**! Please do something about this @Virtuoel. We need to at least know how to import the mod.

**Comment by Nidoskull** [comment]
This is getting ridiculous. Are we just supposed to figure out how to use this on our own through experimentation?
