### ISSUE TITLE
1.16.5 Forge, View does not scale with size

### ISSUE THREAD

**Issue by MandizRivii** [Virtuoel/Pehkui#139]
Ok, so im playing on forge Origins with Pekhui so I can play smaller origins. But when I choose one, view and hitboxex are still like I would be normal size. When I hold shift it fixes

**Comment by Virtuoel** [comment]
What other mods do you have installed?
(If you have Shrink installed, this is an issue on their side, not Pehkui's.)

**Comment by Virtuoel** [comment]
Closing due to no response from the author in a while. If the problem still occurs with the latest Pehkui version, please open another issue.
