### ISSUE TITLE
1.16.5 Fabric pehkui with immersive portals don`t work

### ISSUE THREAD

**Issue by Capy4U** [Virtuoel/Pehkui#141]
I installed the pehkui with immersive portals but it don`t create a portal  with resizing.

**Comment by Capy4U** [comment]
Please someone respond...

**Comment by eehunter** [comment]
If you're using forge that's because the forge version of IP doesn't have that feature yet.

**Comment by Virtuoel** [comment]
Potentially fixed in Pehkui 2.4.0. If the problem still occurs, please open another issue.
