### ISSUE TITLE
Game Crashes When Walk In A Portal For Change Size(Immersive Portals)

### ISSUE THREAD

**Issue by Emirpro2244** [Virtuoel/Pehkui#142]
When i walk into a portal to change size,It saves the chunks and game crashes.I'm on 1.16.4 Fabric.Can anyone help?

**Comment by ProblematicGuy** [comment]
I have the same problem.

**Comment by Virtuoel** [comment]
Potentially fixed in Pehkui 2.4.0. If the problem still occurs, please open another issue.
