### ISSUE TITLE
Pehkui Forces Forge to crash to minecraft launcher

### ISSUE THREAD

**Issue by Fivenpod** [Virtuoel/Pehkui#146]
I have Pehkui 2.2.1 with Forge 36.0.15 and when I launch the client it crashes to the Minecraft launcher halfway through the loading process with an exit code of 0.

I tried removing some other mods from the folder and I tried having only 
Pehkui in the folder and the issue still occurs
![Screenshot 2021-07-26 090653](https://user-images.githubusercontent.com/76071079/127002492-0dc3d237-6d19-4ea4-b8bb-00e2a6e0e1a2.png)

And the launcher didn't give me an error log

**Comment by Virtuoel** [comment]
I think your Forge version might be too old. Can you try again after updating Forge to 36.1.32 or newer?

**Comment by Fivenpod** [comment]
Ok I updated to forge 36.1.32 and that fixed the crashing issue
