### ISSUE TITLE
[Suggestion] Random operation for /scale 

### ISSUE THREAD

**Issue by ImSpaceLover** [Virtuoel/Pehkui#153]
Syntax: 
> /scale random <value1> <value2> [entity]

Or 
> /scale random <value> [entity]

In the first variant the command chooses a random value between two different values. 
For example: 

> /scale random 0.25 16 [entity]
 
 But in the second variant it changes your scale depending on your current scale where the value means multiplier or divisor.
 For example if your scale is 0.5 and the command is
 
 > /scale random 5 [entity]
 
the command will choose a random value between 0.1 (0.5/5) and 2.5 (0.5*5)

**Comment by Derailedzack** [comment]
I could probably try implementing this

**Comment by Virtuoel** [comment]
No need, this has been implemented in dev already for the next version
