### ISSUE TITLE
Resizing Animation does not work

### ISSUE THREAD

**Issue by BautiFujisaki** [Virtuoel/Pehkui#156]
When i change my size it just instantly shrinks or grows me, instead of going smoothly as it has done before

**Comment by ImSpaceLover** [comment]
try using /scale delay set <ticks> [entity]

**Comment by Virtuoel** [comment]
Definitely sounds like this is happening because your scale delay is set to 0 ticks. If that's not the case, please open a new issue with more details on how to reproduce the issue.
