### ISSUE TITLE
(Feature Request) Scale independently on all 3 axes

### ISSUE THREAD

**Issue by VexianEmpire** [Virtuoel/Pehkui#16]
Height, width, and length scaling

**Comment by Virtuoel** [comment]
Due to limitations with how Minecraft handles entities, such as their bounding boxes not having an explicit length and instead just using width for both directions, this is unfortunately not feasible unless something were to change on Mojang's end.

**Comment by raqbit** [comment]
> Due to limitations with how Minecraft handles entities, such as their bounding boxes not having an explicit length and instead just using width for both directions, this is unfortunately not feasible unless something were to change on Mojang's end.

Would it not be possible to only allow changing the model in multiple directions but not the bounding box?
