### ISSUE TITLE
Launcher crashes with a "Exit Code:0" while running a couple of mods

### ISSUE THREAD

**Issue by Misterboy64** [Virtuoel/Pehkui#17]
Hello there! i've used this mod because its required with an another one called "Extra Origins" which also requires its own mods.
while i was ordering my modpack and seeing which one worked and which one did not, i bumped into this problem believing it was "Extra Origins" to cause the problem, apparently it was this dependecy that caused the crash of the launcher
anyways here's the log about what happened, it's a GZ file and i can't open it normally i hope you can understand something about it, thanks about all the contribution about this fix if you can deal with it.
[2020-08-29-7.log.gz](https://github.com/Virtuoel/Pehkui/files/5145446/2020-08-29-7.log.gz)

**Comment by Virtuoel** [comment]
Size Entity Attributes and Pehkui cannot be used at the same time as they are not compatible with each other..

Extra Origins recently switched from using Size Entity Attributes to using Pehkui.
If you're using `extraorigins-16.jar` or newer, only Pehkui should be present, but if you're using `extraorigins-15.jar` or older, only Size Entity Attributes should be present.
