### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by yonk4** [Virtuoel/Pehkui#171]
### Minecraft version(s)

1.16.5

### Mod loader

Fabric

### Mod loader version

0.11.6

### Fabric API version

0.37.2

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

crash when start

### Full list of installed mods

aaaa

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

crash

**Comment by ImSpaceLover** [comment]
Post a full list of the mods and a crashlog, no one can help you without at least one of these

**Comment by Virtuoel** [comment]
Closing due to not following the issue template. Make sure to include your crash report and mod list next time.
