### ISSUE TITLE
[Bug]: pehkui:health works wrong with /scale modifier 

### ISSUE THREAD

**Issue by ImSpaceLover** [Virtuoel/Pehkui#176]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

Fabric loader - 0.11.6

### Fabric API version

0.37.2

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

When I use the command
`/scale modifier add pehkui:health pehkui:base_multiplier`
and then scale up to 2 the game shows me 4x more hearts, but
`/scale compute pehkui:health`
![image](https://user-images.githubusercontent.com/64267797/129930621-b3d360aa-4df5-4cf1-b7a5-f86ac3278a84.png)
says that pehkui:health is 2. These hearts are ghostly, so they can not regenerate.
When I scale down back to 1 I still have 2x hearts, though these hearts disappears as soon as I get any damage.
![image](https://user-images.githubusercontent.com/64267797/129930480-eae07bdb-5995-4e8f-9b82-1f30e0265831.png)
This bug is visual only, but it's still annoying and confusing.

### Full list of installed mods

fabric-api-0.37.2+1.17
Pehkui-2.3.0+1.14.4-1.17.1

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
Should now be fixed in Pehkui 2.4.0.
