### ISSUE TITLE
Game Crashes after loading a new world

### ISSUE THREAD

**Issue by tkrow** [Virtuoel/Pehkui#180]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

Fabric 0.11.6

### Fabric API version

0.39.2

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

The game crashes a few seconds after loading a new world and leaving the origins menu.

The "Game Crashed" popup also says:

The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Pose stack not empty
Exit Code: -1

### Full list of installed mods

additionalbars: Additional Bars 2.1.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		apoli: Apoli 1.0.4
		architectury: Architectury 2.4.26
		artifality: Artifality 0.3.3
		betterbeacon: Better Beacons 1.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		bettersafebed: BetterSafeBed fabric-1.17-1.4
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		calio: Calio 1.0.2
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v5 5.0.38
		collectionorigins1: Imperium Origins Collection 1 2.0
		collectionorigins2: Imperium Origins Collection 2 2.0
		com_focamacho_sealconfig: sealconfig 1.2.2
		companion_bats: Companion Bats 1.17.6
		complete_bone_meal: Complete Bone Meal 1.2.0
		darkness: True Darkness 1.6.74
		explorerscompass: Explorer's Compass 1.17.1-2.0.1-fabric
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabric-tree-chopper: Fabric Tree Chopper 0.7.2
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		graveyard: The Graveyard 1.0
		harvest_scythes: Harvest Scythes 2.0.6
		imm_ptl_core: Immersive Portals Core 0.20
		imm_ptl_surv_adapt: Immersive Portals Mod Survival Adaptation 0.4.0
		immersive_portals: Immersive Portals 0.20
		inventoryhud: Inventory HUD + 3.4.0
		inventoryprofilesnext: Inventory Profiles Next 1.0.0
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		magna: Magna 1.5.5-1.17-pre4
		mechanicaldispensers: MechanicalDispensers 2.0
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		moborigins: Mob Origins 1.6.0
		modern_industrialization: Modern Industrialization 0.5.11
		modmenu: Mod Menu 2.0.5
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nbtcrafting: NBT Crafting 2.0.19+mc1.17
		norecipebook: NoRecipeBook 2.1+1.17
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		oxidizelib: OxidizeLib 1.1.0
		passivecharms: Passive Charms 1.1.0
		patchouli: Patchouli 1.17-52-FABRIC-SNAPSHOT
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		pitch-dark: Pitch Dark 2.0.0
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.20
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		right-click-harvest: Right-Click-Harvest 1.1.0
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.0.268-alpha
		simple_backpack: SimpleBackpack 1.1.18
		soullights: Soul Lights 1.0.0
		storagecabinet: Storage Cabinet 1.17.1-1.3.1
		team_reborn_energy: Energy 0.1.1
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		trinkets: Trinkets 3.0.2
		urns: Urns 1.0.1
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		yungsapi: YUNG's API 1.17-Fabric-16

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/27/21, 12:10 AM
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$baa000$redirectRenderingWorld(class_757.java:4622)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$baa000$redirectRenderingWorld(class_757.java:4622)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$bji000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['SpicyMedia'/272, l='ClientWorld minecraft:overworld', x=120.50, y=63.00, z=167.50]]
	Chunk stats: Client Chunks (ImmPtl) 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,63,171), Section: (at 0,15,11 in 8,3,10; chunk contains blocks 128,0,160 to 143,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25 game time, 25 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3111083904 bytes (2966 MiB) / 4974444544 bytes (4744 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=27.20.22023.1004
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 1.87
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 1.87
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 56270.95
	Virtual memory used (MB): 17500.91
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 1.74
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		additionalbars: Additional Bars 2.1.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.10
		apoli: Apoli 1.0.4
		architectury: Architectury 2.4.26
		artifality: Artifality 0.3.3
		betterbeacon: Better Beacons 1.0.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		bettersafebed: BetterSafeBed fabric-1.17-1.4
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		calio: Calio 1.0.2
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-common-events-v1: Cloth Common Events v1 1.5.47
		cloth-config2: Cloth Config v5 5.0.38
		collectionorigins1: Imperium Origins Collection 1 2.0
		collectionorigins2: Imperium Origins Collection 2 2.0
		com_focamacho_sealconfig: sealconfig 1.2.2
		companion_bats: Companion Bats 1.17.6
		complete_bone_meal: Complete Bone Meal 1.2.0
		darkness: True Darkness 1.6.74
		explorerscompass: Explorer's Compass 1.17.1-2.0.1-fabric
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabric-tree-chopper: Fabric Tree Chopper 0.7.2
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fasttransferlib: Fast Transfer Lib 0.5.6
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		graveyard: The Graveyard 1.0
		harvest_scythes: Harvest Scythes 2.0.6
		imm_ptl_core: Immersive Portals Core 0.20
		imm_ptl_surv_adapt: Immersive Portals Mod Survival Adaptation 0.4.0
		immersive_portals: Immersive Portals 0.20
		inventoryhud: Inventory HUD + 3.4.0
		inventoryprofilesnext: Inventory Profiles Next 1.0.0
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		magna: Magna 1.5.5-1.17-pre4
		mechanicaldispensers: MechanicalDispensers 2.0
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		moborigins: Mob Origins 1.6.0
		modern_industrialization: Modern Industrialization 0.5.11
		modmenu: Mod Menu 2.0.5
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nbtcrafting: NBT Crafting 2.0.19+mc1.17
		norecipebook: NoRecipeBook 2.1+1.17
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		oxidizelib: OxidizeLib 1.1.0
		passivecharms: Passive Charms 1.1.0
		patchouli: Patchouli 1.17-52-FABRIC-SNAPSHOT
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		pitch-dark: Pitch Dark 2.0.0
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		q_misc_util: A Miscellaneous Utility Library from qouteall 0.20
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		right-click-harvest: Right-Click-Harvest 1.1.0
		ringsofascension: Rings of Ascension 1.0.1
		roughlyenoughitems: Roughly Enough Items 6.0.268-alpha
		simple_backpack: SimpleBackpack 1.1.18
		soullights: Soul Lights 1.0.0
		storagecabinet: Storage Cabinet 1.17.1-1.3.1
		team_reborn_energy: Energy 0.1.1
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		trinkets: Trinkets 3.0.2
		urns: Urns 1.0.1
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 570 Series GL version 3.2.14742 Core Profile Forward-Compatible Context 21.8.1 27.20.22023.1004, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Player Count: 1 / 8; [class_3222['SpicyMedia'/272, l='ServerWorld minecraft:overworld Survival', x=120.50, y=63.00, z=167.50]]
	Data Packs: vanilla, Fabric Mods

**Comment by tkrow** [comment]
Nevermind. I got Pehkui to stop crashing the game when I removed Artifality.

**Comment by Silviyius** [comment]
![image](https://user-images.githubusercontent.com/7122428/131236363-8a11369a-c321-42dc-99e7-8dd45f471411.png)


https://pastebin.com/zuti0uJc

I wouldn't say its fixed.  According to MoriyaShinne from Bewitchment This Mod might be canceling any methods to do with rendering and instead scale it to be invisible.

**Comment by Virtuoel** [comment]
Should now be fixed in Pehkui 2.4.0.
