### ISSUE TITLE
Add a function to be stepped on or squish depending on the size of the entity.

### ISSUE THREAD

**Issue by DGKaru** [Virtuoel/Pehkui#183]
### What is your suggestion?

Smaller entities can get stepped on by larger entities.
Larger entities can walk, jump or fall on smaller entities to squish them.
I suggest adding this function like pehkui:squish.

**Comment by Virtuoel** [comment]
Unfortunately, this seems somewhat out of scope for Pehkui itself. Would be interesting to see another mod that adds this kind of functionality though.
