### ISSUE TITLE
[Bug]: When using a world converted from 1.16.5 in 1.17.1, The console is spammed and RAM usage spikes.

### ISSUE THREAD

**Issue by Alkiasan** [Virtuoel/Pehkui#184]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

0.11.6

### Fabric API version

0.38.2+

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

When casually playing, the console logs are spammed with the following:
[19:09:11] [Server thread/WARN]: Ignoring unknown attribute 'stepheightentityattribute:stepheight'
This seems to be causing lag, and killing all entities doesn't stop the error from happening... Is there a way of fixing this?

### Full list of installed mods

- adorn@2.1.3+1.17.1
	- amecsapi@1.1.5+mc21w16a
	- antiqueatlas@6.0.0-fabric-mc1.17.1
	- apoli@1.0.4
	- artifice@0.15.5+21w07a
	- autoconfig1u@3.3.1
	- backslot@1.2.0
	- bclib@0.3.1
	- bedspreads@1.4.0-1.17
	- bendy-lib@2.0.2
	- betterend@0.11.0-pre
	- betternether@5.1.3
	- blockbot-api@1.0.0
	- blockbot-discord@2.0.0-beta1
	- blockus@2.2.8+1.17.1
	- calio@1.0.2
	- cardinal-components-base@3.1.1
	- cardinal-components-entity@3.1.1
	- carpet@1.4.45
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.38
	- colorchat@1.3.2
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml@2.12.2
	- comforts@0.0.5-1.17.1
	- cosmetic-armor@1.1.0
	- croptopia@1.6.1
	- customportalapi@0.0.1-beta40-1.17
	- dual_riders@1.0.5
	- ec-core@1.0.0-mc1.17
	- emotecraft@2.0.9
	- essential_commands@0.16.1-mc1.17
	- extraalchemy@1.5.1
	- extraorigins@1.17-6
	- fabric@0.38.2+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+2f75c6ce18
	- fabric-biome-api-v1@3.1.12+3fe74aa118
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.4+2e8bd82f18
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b446318
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.3+kotlin.1.5.21
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+2e8bd82f18
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.7.0+2e8bd82f18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.0+3fe74aa118
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.1.2+8195aec118
	- fabricloader@0.11.6
	- fabrictailor@1.6.3
	- fallflyinglib@3.0.0-beta.2
	- fantasy@0.4.1+1.17
	- fantasy-origins@1.0.0
	- fatxporbs@1.0.1
	- ferritecore@3.0.3
	- fiber@0.23.0-2
	- flan@1.17.1-1.6.2
	- gateofbabylon@1.5.0-1.17
	- go-fish@1.3.0-beta-1.17
	- haema@1.7.5+1.17
	- harvest@1.2.12
	- hologram-api@0.2.1+1.17.1
	- horizonrpmod@1.0.0
	- image2map@0.2.1
	- interdimensional@1.0.0-beta.2
	- invisiblights@7.1+1.17
	- invview@1.4.6-1.17.1+
	- iris@1.1.1
	- jankson@3.0.1+j1.2.0
	- java@16
	- kanos_config@0.1.4+1.14.4-1.17.1
	- libcd@3.0.3+1.16.3
	- libgui@4.1.3+1.17.1
	- libninepatch@1.1.0
	- mc_discord_reserializer@1.0.0
	- mcda@1.7.9
	- minecraft@1.17.1
	- minegate-moreblocks@1.1.6
	- modmenu@2.0.5
	- more_codecs@0.1.4
	- mostructures@1.3.0-pre1-1.17.1
	- ne-v-seti@0.1.6-1.17
	- notenoughanimations@1.3.0
	- omega-config@1.0.8
	- org_jetbrains_kotlin_kotlin-reflect@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- origins@1.0.3
	- origins-classes@1.2.2
	- packet_tweaker@0.2.0-1.17-pre1
	- patchouli@1.17-55-FABRIC-SNAPSHOT
	- pehkui@2.3.0+1.14.4-1.17.1
	- pingspam@1.2.2-1.17
	- placeholder-api@1.1.0+1.17.1
	- player_roles@1.4.3
	- player_roles_api@1.4.3
	- playerabilitylib@1.3.0
	- polymer@0.1.0-rc.4+1.17.1
	- reach-entity-attributes@2.1.1
	- satin@1.6.1
	- server_translations_api@1.4.5+1.17
	- servercpa@0.0.1-beta0-1.17
	- sgui@1.0.0-rc4+1.17.1
	- slimeorigin@4.0.0
	- sodium@0.3.0+IRIS2
	- somnus@0.0.12-1.17
	- spark@1.6.1
	- starlight@1.0.0-RC3+fabric.2b7d7ae
	- taterzens@1.3.0
	- transliterationlib@1.1.0
	- transparent_cosmetics@1.3.0
	- trinkets@3.0.2
	- universal-graves@1.0.8+1.17.1
	- voicechat@1.17.1-1.1.4
	- worldedit@7.2.6+4b2d1e7
	- xaeroworldmap@1.16.1
	- xlpackets@2.0-1.17

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
The RAM issue should be solved with recent performance improvements. The spam, however, was caused by removing the step-height-entity-attribute mod or a mod that contained it. No idea the fix for that, but not a Pehkui issue.
