### ISSUE TITLE
[Bug]: crash on start up

### ISSUE THREAD

**Issue by itsdinkd** [Virtuoel/Pehkui#185]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

latest

### Fabric API version

latest

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

on start up game crashes 

### Full list of installed mods

https://pastebin.com/etEumgUp

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

https://pastebin.com/etEumgUp

**Comment by itsdinkd** [comment]
Turns out this is because Towelette was on the server. Pehuki is not compat with Towelette

**Comment by HockeyZman2000** [comment]
I'm having a very similar problem to this one where the crash report is the same, removed the Adorn mod because it has Towelette embedded in it, but still crashes on startup.

Latest Log: https://pastebin.com/k2fX5rF9
Crash Report: https://pastebin.com/WNR3n8jY

**Comment by frikinjay** [comment]
Can confirm I am crashing with a similar crash report. But it crashes only on multimc and works fine of the curseforge app.

**Comment by itsdinkd** [comment]
Seems the mod author is inactive but a lot of mods are still using Pehkui as a dependacy. sucks.

**Comment by Virtuoel** [comment]
Should now be fixed in Pehkui 2.4.0.
