### ISSUE TITLE
[Bug]: Compatibility issue MedievalWeapons

### ISSUE THREAD

**Issue by UltimateCoffee** [Virtuoel/Pehkui#188]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

0.11.6

### Fabric API version

0.39.2

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

When playing in any game mode (Tried single player and multiplayer via hosted server), the client crashes anytime the game tries to render a 3rd person character that is holding one of these weapons from the MedievalWeapons mod: Healing Staff, Mace, Waraxe, Javeline, Lance.

https://pastebin.com/HPws45eM

Note: Crash report had a lot of mods loaded.
Got the same crash with identical report after disabling everything except what is listed in the Full list of installed mods.

### Full list of installed mods

MedievalWeapons
Pehkui
Polymorph
Fabric API
Cloth API
Cloth Config API

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/9/21, 5:06 PM
Description: Unexpected error

java.lang.IllegalStateException: Pose stack not empty
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_22979(class_761.java:1472)
	at net.minecraft.class_761.method_22710(class_761.java:1235)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$doo000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['UltimateCoffee'/475230, l='ClientLevel', x=-239.24, y=70.00, z=87.68]]
	Chunk stats: 1024, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (-240,72,93), Section: (at 0,8,13 in -15,4,5; chunk contains blocks -240,-64,80 to -225,319,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 4025288 game time, 1047097 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, charmonium/journeyman, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 897492896 bytes (855 MiB) / 1879048192 bytes (1792 MiB) up to 16106127360 bytes (15360 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.09
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 2080 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e81
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6589
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.00
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.00
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 81844.28
	Virtual memory used (MB): 12733.77
	Swap memory total (MB): 49152.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx15360m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.2
		additionalbars: Additional Bars 2.1.1
		adorn: Adorn 2.1.4+1.17.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventurez: AdventureZ 1.2.11
		amecsapi: Amecs API 1.1.5+mc21w16a
		aqupdcaracal: Caracal mob 1.17-1.3.11
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		architects_palette: Architect's Palette Fabric 1.2
		architectury: Architectury 2.5.27
		artifality: Artifality 0.3.5
		artifice: Artifice 0.15.5+21w07a
		assembly: Assembly 21w06a-1.0.0
		attributefix: Attribute Fix {FABRIC} 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.2
		backslot: BackSlot 1.2.0
		backslotaddon: BackSlot Addon 1.0.6
		bclib: BCLib 0.3.1
		beaconoverhaul: Beacon Overhaul 1.4.1+1.17
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		bettersodiumvideosettingsbutton: Better Sodium Video Settings Button 2.0.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		bewitchment: Bewitchment 1.17-5
		caelus: Caelus API 0.0.16-1.17
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carrier: Carrier 1.8.0
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.3
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cherishedworlds: Cherished Worlds 2.0.1-1.17.1
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps fabric-1.17.1-7.0.5
		colytra: Colytra 2.0.0-1.17
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		comforts: Comforts 0.0.6-1.17.1
		controlling: Controlling For Fabric 1.1.2
		cosmetic-armor: Cosmetic Armor 1.1.0
		couplings: Couplings 1.5.0+1.17
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portals 0.0.1-beta33-1.17
		customstars: Custom Stars 0.5
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		darkpaintings: Dark Paintings 4.0.2
		dashloader: DashLoader 2.0
		dawn: Dawn API 2.0.6
		deepslatecutting: Deepslate Cutting 1.2.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dragonloot: DragonLoot 1.0.9
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		dynamicfps: Dynamic FPS 2.0.5
		earthtojavamobs: Earth2Java 1.7.3+1.17
		elytratrinket: Elytra Trinket 2.0.1-1.17
		enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhancedcelestials: Enhanced Celestials 2.0.4
		expandedstorage: Expanded Storage 7.1.0
		extended_armor_bars: Extended Armor Bars 1.1.0
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabric-tree-chopper: Fabric Tree Chopper 0.7.2
		fabricloader: Fabric Loader 0.11.6
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fancymenu: FancyMenu 2.2.2
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		flesh2leather: Flesh2Leather 1.0.2
		flintytools: Flinty Tools 1.0.0
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.7
		forgottenrecipes: Forgotten Recipes 1.0.2
		geckolib3: Geckolib 3.0.13
		goml: Get Off My Lawn 1.4.0-beta
		grass_pass: Grass Bypass 1.0.0
		graveyard: The Graveyard 1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		illuminations: Illuminations 1.7
		impersonate: Impersonate 2.3.3
		inmis: Inmis 2.3.1-1.17
		inventoryhud: Inventory HUD + 3.4.0
		io_activej_activej-codegen: activej-codegen 4.3
		io_activej_activej-serializer: activej-serializer 4.3
		iris: Iris 1.1.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		konkrete: Konkrete 1.2.3
		krypton: Krypton 0.1.4
		kubejs: KubeJS 1605.3.10-build.9999
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		linkedstorage: Linked Storage 1.3.13-1.17
		lovely_snails: Lovely Snails 1.0.3+1.17
		mavm: More Axolotl Variants Mod 1.0.3a
		maybe-data: Maybe data 1.0.1-1.17
		me_hypherionmc_simple-rpc-lib: simple-rpc-lib 2.1.5
		medievalweapons: Medieval Weapons 1.1.6
		megane: megane 5.2.1
		megane-base: megane-base 5.2.1
		megane-fabric-transfer: megane-fabric-transfer 5.2.1+1.1.0-3fe74aa118
		megane-runtime: megane-runtime 5.2.1
		megane-vanilla: megane-vanilla 5.2.1+1.17.1
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.7
		more-structures-add-on-for-william-wythers-overhauled-overworld: More Structures add-on for William Wythers Overhauled Overworld 1.2
		morebannerfeatures: More Banner Features 1.0.5
		morerespawnanchors: More Respawn Anchors 1.0.2
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nears: Nears 1.1.2
		nearsightedly: Near-Sightedly 1.2.1
		npcvariety: NPC Variety 2.1.2
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		org_yaml_snakeyaml: snakeyaml 1.27
		outvoted: Outvoted 2.0.0-alpha.12
		oxidized: Oxidized 1.3.0
		oxidizelib: OxidizeLib 1.1.0
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17-54-FABRIC
		paxi: Paxi 1.17-1.2.2
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		placeholder-api: Placeholder API 1.1.0+1.17.1
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		polymer: Polymer 0.1.0-rc.4+1.17.1
		polymorph: Polymorph 0.0.12-1.17.1
		primordial-shores-add-on-for-wwoo: Primordial Shores add-on for William Wythers Overhauled Overworld 1.0
		promenade: Promenade 2.1.2
		quartzelv: Quartz Elevator 1.2.5
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 2.3.2+1.17.1
		rhino: Rhino 1605.1.2-build.40
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		scorch: Scorch 1.1.0
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		server_translations_api: Server Translations API 1.4.5+1.17
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerutils: shulkerutils 1.0.4-1.17
		simple-rpc: Simple Rpc 1.17-2.3.1-fabric
		sit: Sit 1.17.1-13
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.3.0+IRIS2
		somnus: Somnus API 0.0.14-1.17.1
		spark: spark 1.6.1
		spirit: Spirit 1.1.0
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.3
		stonevaults: Stonevaults 1.1.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 2.0.0
		terraform-config-api-v1: Terraform Config API (v1) 2.0.0
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 2.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 2.0.0
		terraform-tree-api-v1: Terraform Tree API (v1) 2.0.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		the_aether: The Aether 1.17.1-1.5.0
		things: Things 0.2.5
		transparent_cosmetics: Transparent Cosmetics 1.3.0
		traverse: Traverse 4.0.0-beta.2
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.3
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		tweed: Tweed 3.0.0-beta.26
		universal-graves: Universal Graves 1.0.8+1.17.1
		universal_ores: Universal Ores 1.0
		upgradedechests: Upgraded Ender Chests 1.0.2-1.17
		upgradedshulkers: Upgraded Shulkers 1.0.2-1.17
		urns: Urns 1.0.1
		vanilla_degus: Vanilla Degus 1.2.0
		veinmining: Vein Mining 0.0.10-1.17
		villagernames: Villager Names 2.0.0
		villagershats: Goosik's Villager Hats 1.2.0
		visuality: Visuality 0.1.0
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.4
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.6
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.14.0
		xaeroworldmap: Xaero's World Map 1.15.0.1
		xp_storage: XP Storage 1.4.2+1.17.1
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.17.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 465.89, NVIDIA Corporation
	Window size: 3620x2036
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, charmonium/journeyman, charmonium/journeyman
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 3900X 12-Core Processor

**Comment by Virtuoel** [comment]
Should now be fixed in Pehkui 2.4.0.
