### ISSUE TITLE
impossible to interact with blocks if there's entities behind them

### ISSUE THREAD

**Issue by Chuunkyz** [Virtuoel/Pehkui#192]
### Minecraft version(s)

1.17.1

### Minecraft version details

1.17.1

### Mod loader

Fabric

### Mod loader version

0.11.6

### Fabric API version

0.40.1

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Well, i can literally hurt enemies through blocks, kill my villager trying to make villager contraptions,... try by yourself !
(the bug isn't a thing in 2.2.1, just 2.4.0)

### Full list of installed mods

my modpack
https://www.curseforge.com/minecraft/modpacks/benchmark

### Did the problem cause the game to crash?

No.

**Comment by ImUrX** [comment]
kind of offtopic but when is next release @Virtuoel ?

i didnt see the code was updated so i couldnt compile my own jar :p

**Comment by Chuunkyz** [comment]
hi, sorry but this is not fixed at all in 2.5.2

**Comment by Virtuoel** [comment]
It is known, the issue for this on 2.5.2 is at #204
