### ISSUE TITLE
[Suggestion]: Add a maven repo for forge and fabric

### ISSUE THREAD

**Issue by Derailedzack** [Virtuoel/Pehkui#193]
### What is your suggestion?

Add/Create a maven repo for the forge and or fabric version of this mod.

**Comment by Derailedzack** [comment]
I'm currently stuck with version 2.0.0

**Comment by Virtuoel** [comment]
Hmm, have you tried using JitPack for the maven?
I'll also be adding a README later in the week which should (hopefully) make it clearer how to use this mod as a library.

**Comment by Derailedzack** [comment]
Yes
