### ISSUE TITLE
When increasing scale, game crashes at a smaller scale compared to previous versions

### ISSUE THREAD

**Issue by MagmaCaliburX** [Virtuoel/Pehkui#197]
### What is your suggestion?

In 1.16 Pehkui, the game can run comfortably up a player is around scale 40. However, in the 1.17 version, it can already start to lag when a player is around scale 15. Happens in both singleplayer and multiplayer.

**Comment by ImSpaceLover** [comment]
Change this issue from suggestion to bug and write down more information please

**Comment by MagmaCaliburX** [comment]
Sorry. Turns out some other people have pointed out this bug already
