### ISSUE TITLE
[Bug]: Reach entity attributes "attack attribute" don't work with pehkui installed

### ISSUE THREAD

**Issue by Estrelaura** [Virtuoel/Pehkui#199]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

0.11.7

### Fabric API version

0.40.6

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Mods that modify attack reach using reach entity attributes don't work with the mod installed. Examples include the long reach effect from Beacon Overhaul, which modifies the block reach but not the attack when installed with Pehkui.

### Full list of installed mods

        - accurateblockplacement@1.0.10
	- addendum@1.0.2
	- advanced_runtime_resource_pack@0.4.3
	- advancementplaques@1.4.1
	- advancements-enlarger@0.2.4
	- alternatecurrent@0.4.0
	- amecsapi@1.1.5+mc21w16a
	- animal_feeding_trough@1.0.2
	- annotateddi@2.0.3+1.17.1
	- antighost@1.17.1-fabric0.36.1-1.1.4
	- aopalliance_aopalliance@1.0
	- appleskin@mc1.17-2.1.3
	- arcanus@1.16
	- architectury@2.5.30
	- asa@1.2
	- assembly@21w06a-1.0.0
	- atmosfera@2.0.0+mc1.17
	- audaki_cart_engine@1.0.1
	- augmentedautojump@1.1.0
	- authme@1.5.0
	- autoconfig1u@3.3.1
	- axesareweapons@1.3-1.17
	- axolotlitemfix@1.1.2
	- azalea_hedges@1.0.0
	- beaconoverhaul@1.4.2+1.17
	- bedrockify@1.2.0+mc1.17.1
	- bedrockwaters@1.5.0+1.17.1
	- bedspreads@1.4.0-1.17
	- better_concrete@1.0.0
	- betterdungeons@1.17-1.0.2
	- bettereating@0.3.0
	- betterf3@1.1.5
	- bettermineshafts@1.17-1.0.1
	- bettermounthud@1.1.2
	- betterrecipebook@1.4.1
	- betterstrongholds@1.17-1.1.2
	- betterthirdperson@1.5.0
	- big_items_duh@1.0.2+mc1.17-rc2
	- blast@1.8
	- blastproof_netherite@2.0.0+mc1.17
	- blockshifter@1.4.0+fabric-1.17.1
	- blocktuner@0.6.3
	- blockus@2.2.10+1.17.1
	- blur@2.1.0
	- boatcontainer@1.0.0
	- bookworm@1.0.0
	- caelus@0.0.18-1.17.1
	- cakechomps@1.4.0-1.17
	- camp_fires_cook_mobs@1.2.1+MC1.17-1.17.1
	- cardinal-components-base@3.1.1
	- cardinal-components-entity@3.1.1
	- cardinal-components-item@3.0.0-nightly.1.17-pre2
	- carpet@1.4.47
	- carpet-extra@1.4.43
	- carpet-fixes@1.17.1-1.1.0+v210919
	- carpet-tis-addition@1.22.0+build.678
	- cartloaders@0.0.2
	- carvepump@1.0.4
	- cauldronconcrete@1.0.0+21w16a-fabric
	- cauldronriptide@1.1-mc1.17-fabric
	- cauldrons@1.1.4
	- cavebiomes@0.6.3
	- chainsuspension@1.0.0
	- chord@1.8.0+1.17-rc1-fabric
	- clear-skies@1.5.70
	- clientsidenoteblocks@2.0
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.38
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- colorfulsubtitles@1.0.0
	- columns@1.2.0
	- com_electronwill_night-config_core@3.6.4
	- com_electronwill_night-config_toml@3.6.4
	- com_focamacho_sealconfig@1.2.2
	- com_google_inject_guice@5.0.1
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- connectiblechains@1.2.3
	- controlling@1.1.2
	- couplings@1.5.0+1.17
	- cr-arrows-info@1.1.0+1.17
	- creativeonepunch@1.2
	- crosshairmod@0.3.1
	- crowdin-translate@1.3+1.17
	- customizableelytra@1.5.1-1.17
	- customstars@0.5
	- darkpaintings@4.0.2
	- datareload@1.1
	- deathcoords@1.0.0
	- detailab@2.6.1+1.17.1-fabric
	- discerning_furnace@1.0.3+MC1.17-1.17.1
	- dontdropit@2.3.2+1.17
	- doublejump@1.0.1+mc1.17
	- dual_riders@1.0.5
	- dummmmmmy@1.17-1.1.0
	- durabilityspeed@1.4.0
	- dynamicfps@2.0.5
	- dynmus@1.3.0
	- earthtojavamobs@1.7.3+1.17
	- easyautocrafting@1.1+1.17
	- eatinganimationid@1.2
	- economical_villager_trading@1.2.1+MC1.17-1.17.1
	- elytraprotection@1.17-0.1.1
	- enchantment_lore@1.2.1+MC1.17.1
	- enchantmentdescriptions@4.0.1
	- enchantmenttweaker@0.0.1b
	- endless_cake@1.0.0
	- enhanced_attack_indicator@1.0.2+1.17
	- enhancedblockentities@0.5+1.17
	- enhancedcelestials@2.0.5
	- entityculling@1.3.3
	- environmentz@1.1.6
	- extrasounds@1.4.1
	- extrasucchopper@1.0+1.17
	- fabric@0.40.6+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.5+kotlin.1.5.31
	- fabric-language-scala@1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+cbda931818
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.11+7931163218
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.4+7931163218
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.14+4658223018
	- fabric-rendering-v0@1.1.5+7931163218
	- fabric-rendering-v1@1.9.0+7931163218
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabric-transfer-api-v1@1.4.0+7931163218
	- fabricloader@0.11.7
	- fabulousclouds@0.2.3
	- fairhorsestats@1.0.0
	- fallingattack@1.17.1-1.1.2
	- fallingblocktweaks@1.0.0+1.16.5-fabric
	- fallingleaves@1.7.3+1.17.1
	- farsighted-mobs@1.1-1.17
	- fefafly@1.0.0
	- ferritecore@3.1.0
	- fireplacelib@6.0.6+1.17.1
	- fireworkfrenzy@1.5
	- fishonaleash@1.17-1.0.0
	- flagbric@2.0.1
	- flytre_lib@0.2.21
	- freezma@1.17.1-1
	- fruitful@1.0.1
	- fuelinfo@1.0
	- full_slabs@3.1.4
	- gateofbabylon@1.5.1-1.17.1
	- ghastly_wail@1.0.3+MC1.17-1.17.1
	- gildedarmor@1.3.0+fabric-1.17.1
	- go-fish@1.3.0-beta-1.17.1
	- goosiklib@0.1.0
	- graveyard@1.0
	- grindenchantments@1.4.0+1.17.1
	- grindstoneismadeofstone@1.0
	- hatlist@1.2
	- herdspanic@1.0.3
	- homecamp@2.1.0+1.17.1
	- hotfurnace@1.0
	- hydrogen@0.3
	- illuminations@1.8
	- indium@1.0.0+mc1.17.1
	- indypets@0.7.0
	- infinitywaterbucket@1.4.1-mc1.17-fabric
	- inspecio@1.1.0+1.17
	- interdimensional-map-markers@1.0.0
	- iris@1.1.2+build.9
	- itemmodelfix@1.0.2+1.17
	- java@16
	- javax_inject_javax_inject@1
	- kanos_config@0.1.4+1.14.4-1.17.1
	- kirin@1.9.1
	- koi@1.0.1
	- krypton@0.1.4
	- lakeside@1.1.0+1.17
	- lambdabettergrass@1.2.1+1.17
	- lambdynlights@2.0.2+1.17
	- lawnage@4.0.0
	- lazydfu@0.1.2
	- leather-blocks@1.1.2
	- letsleepingdogslie@1.0.0
	- libcd@3.0.3+1.16.3
	- light-fix@1.0.0
	- lightfooted@1.0.0+20w49a
	- lithium@0.7.4
	- loading-timer@1.5.0-Beta1
	- lovely_snails@1.0.3+1.17
	- lumiwool@1.1.1
	- lunaar-carpet-addons@0.5.0
	- maelstrom_library@1.2.1-1.17-pre1
	- malilib@0.10.0-dev.24
	- maybe-data@1.0.1-1.17
	- midnightlib@0.2.5
	- mighty_mangoes@1.0.5
	- minecraft@1.17.1
	- minitweaks@1.1.2
	- mixintrace@1.1.0+1.17
	- mm@2.2
	- mobs_attempt_parkour@0.2.3-1.17-pre1
	- modmenu@2.0.14
	- mojangster@1.17-3.0.1
	- more_tooltips@1.0.2
	- morebannerfeatures@1.0.7
	- moreflowerpots@2.0-SNAPSHOT
	- mossierdeepslate@1.0.0
	- mostructures@1.3.0-pre1-1.17.1
	- mousewheelie@1.7.3+mc1.17.1-pre1
	- musicdr@1.2.1
	- namepain@1.4.0
	- nbexpand@2.0.1
	- ne-v-seti@0.1.6-1.17
	- nears@1.1.2
	- netherchest@2.0
	- nethermap@1.5.0-1.17.1
	- no-potion-offset@${version}
	- not-that-cc@1.0
	- notenoughanimations@1.3.0
	- notenoughcrashes@3.6.5+1.17.1
	- odysseyhud@1.0.0
	- omega-config@1.0.8
	- onsoulfire@1.17-1
	- org_aperlambda_lambdajcommon@1.8.1
	- org_codehaus_groovy_groovy@3.0.8
	- org_codehaus_groovy_groovy-jsr223@3.0.8
	- org_jetbrains_annotations@17.0.0
	- org_jetbrains_kotlin_kotlin-reflect@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.7
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.3.0
	- oxidized@1.4.0
	- paintings@1.17.1-1.0.0.3
	- pale@1.0.0
	- particlerain@1.5.0
	- patternedglass@1.17-1.0.1
	- paxi@1.17-1.2.2
	- peepingcreepers@1.1-1.17
	- pehkui@2.4.0+1.14.4-1.17.1
	- perfectaccuracy@1.1
	- pickblockstate@1.0.0+1.17
	- pingspam@1.2.2-1.17
	- plated@2.1.1
	- pling@1.4.0
	- powershot@1.2.0-1.17-fabric
	- ppp@1.3.0
	- presencefootsteps@r32-1.17-rc1
	- puddles@1.1.0
	- quicksand@1.0.2
	- quickspyglasser@0.3.0
	- quitconfirm@1.3
	- rad@1.0.1
	- rainbow-shenanigans@1.0.0
	- reach-entity-attributes@2.1.1
	- recipecache@0.2.0-1.17.1
	- repurposed_structures@2.3.6+1.17.1
	- reroll@1.3.0-1.17.1
	- rocket_minecarts@1.0.0
	- roughlyenoughitems@6.0.279-alpha
	- rug@1.17.1-1.1.13
	- rutreplantswamp@0.0.1
	- satin@1.6.4
	- scaryplayer@1.1.0
	- scorch@1.1.2
	- screenshotclipboard@1.0.6
	- searchablecontainers@1.3
	- secondchance@1.1.0
	- servertick@1.5
	- sgui@1.0.0-rc3-1.17.1
	- sheepconsistency@1.0.3
	- sihywtcamc@1.4.1+1.17.1
	- sihywtcamd@1.5.2+1.17.1
	- simplyimprovedterrain@0.4.0.3-Fabric-1.17
	- sizeshiftingpotions@1.2.0
	- skinlayers@1.1.0
	- slight-gui-modifications@2.0.1
	- slimyfloor@1.17.1-1.2.0
	- smoothscrollingeverywhere@3.0.3-unstable
	- smoothswapping@0.4.2
	- snowundertrees@1.0.0
	- sodium@0.3.2+IRIS2-build.9
	- sound_track@1.0.4
	- soundphysics@2.0.0
	- spruceui@3.3.0+1.17
	- spyzoom@1.0.1
	- starlight@1.0.0+fabric.73f6d37
	- stat_check@1.1.0
	- statement@4.1.3+1.14.4-1.17.1
	- statement_vanilla_compatibility@1.0.1+1.16.5-1.17
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- stonevaults@1.1.0
	- talkbubbles@1.0.0
	- taxfreelevels@1.2.1
	- telepistons@1.0.2
	- terraform-biome-builder-api-v1@2.0.0
	- terraform-config-api-v1@2.0.0
	- terraform-overworld-biome-extensions-api-v1@2.0.0
	- terraform-surfaces-api-v1@2.0.0
	- terraform-tree-api-v1@2.0.0
	- terraform-wood-api-v1@2.0.2
	- tooltipfix@1.0.3-1.16
	- torohealth@1.17.1-fabric-12
	- totemmod@0.3.2
	- tougherglass@1.0.3
	- transliterationlib@1.2.2
	- trapexpansion@1.3.3
	- traverse@4.0.0
	- treefax@1.3.0
	- treefelling@1.0.0
	- trinketofundying@2.0.0-1.17
	- trinkets@3.0.4
	- trinketshulkerboxes@2.0.0-1.17
	- trirev@1.0.3
	- tweed@3.0.0-beta.26
	- twigs@1.0.2
	- undergroundambientlighting@2.1.0
	- unsaddleeeee@1.0+mc1.17-Fabric
	- vectorientation@1.0.1a
	- vehiclefix@1.1
	- verticalrepeaters@1.1.2
	- villager-hats@1.2.1
	- villager_see_villager_do@1.1.1+MC1.17-1.17.1
	- villagers@1.0+1.16.3
	- visuality@0.1.3
	- waig@1.0.0
	- wandering_collector@1.0.2+mc1.17
	- waterdripsound@1.17-0.2.2
	- waveycapes@1.0.3
	- waystones@2.1.2
	- weaponthrow@1.17.1-1.2
	- wolveswitharmor@1.6.1-1.17.1
	- yungsapi@1.17-Fabric-19

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
Superseded by #203
