### ISSUE TITLE
[Bug]: Immersive Portals doesn't really match with Pehkui

### ISSUE THREAD

**Issue by hay-dude007** [Virtuoel/Pehkui#200]
### Minecraft version(s)

1.16.5

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.11.7-1.16.5

### Fabric API version

Fabric API 0.40.1

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I installed Pehkui but it didn't allow me:
Any scale portals...
... and therefor no scaling the player with portals
I expected:
Any scale portals...
...and therefor scaling the player with portals

### Full list of installed mods

fabric-api-0.40.1+1.16.jar,
immersive-portals-0.16-mc1.16.5-forge.jar,
immersive-portals-0.99-mc1.16.5fabric.jar,
optifabric-1.9.6.jar,
OptiFine_1.16.5_HD_U_G7.jar,
Pehkui-2.4.0+1.14.4-1.17.1.jar,
the-backrooms-1.3.1.jar

### Did the problem cause the game to crash?

No.

**Comment by ImSpaceLover** [comment]
You're using the forge version of pehkui and immersive portals. The portal scaling feature is added by Immersive Portals mod, which is not currently supported, so the developer of Pehkui can't do much about it. You can use the Fabric version of the mod instead.

**Comment by hay-dude007** [comment]
Ohhhh thank you sososososososo much i finally can scale trough portals thank you
