### ISSUE TITLE
Datapacks Support

### ISSUE THREAD

**Issue by ghost** [Virtuoel/Pehkui#201]
### What is your suggestion?

I Just Used This Mod But Idk Why This Is Not Supported With Datapacks
Like Not Gonna Lie Its A Pretty Dope Pack
But I Will Like To See Datapack Support 
Asap Please

**Comment by ImSpaceLover** [comment]
what exactly do you mean by "datapack support"? Pehkui already supports datapacks. There's a plenty of useful commands for datapacks. If you want something special, then clarify what you want. And don't say "asap" please, there's nothing important to be impatient.

**Comment by ghost** [comment]
I am sorry
but When I tried using  it with datapacks
its not working for me

**Comment by Virtuoel** [comment]
Closing since original poster is now a deleted account.
