### ISSUE TITLE
[Bug]: Destroys Performance

### ISSUE THREAD

**Issue by TrueCP6** [Virtuoel/Pehkui#206]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.12.2

### Fabric API version

0.41.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Pehkui destroys server performance. See [here](https://github.com/MoriyaShiine/bewitchment/issues/196) for more information.

### Full list of installed mods

Occurs with any mods that have Pehkui as a dependency

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
Does this still occur with Pehkui 2.5.3, and if yes, can you provide a Spark profile link?

**Comment by TrueCP6** [comment]
I have been unable to test yet due to exams, and won't be able to for another week or two. If anyone else can that would be highly appreciated.

**Comment by Virtuoel** [comment]
Performance impact confirmed by other sources for the latest Forge version. Am assuming the same still applies for the Fabric version.

**Comment by Virtuoel** [comment]
This should now be improved a bit with Pehkui 2.6.0 and above. Do let me know how performance is when you have time to test.

**Comment by TrueCP6** [comment]
The performance impact does seem to be less but still very high when compared to other mods.
[Only with spark](https://spark.lucko.me/2Dq6iMb5sC)
[Bewitchment with only its required depenencies](https://spark.lucko.me/jyDKjeBIxZ)

**Comment by ChristianKilduff** [comment]
https://spark.lucko.me/tjBMFTVsfr using 16% of cpu
[penkui-profile.zip](https://github.com/Virtuoel/Pehkui/files/8187524/penkui-profile.zip)

(fabric)

**Comment by ChristianKilduff** [comment]
i am confused by the fact that most of the cpu is used by isreset() im guessing that is connected to the /scale reset command but that does not make a lot of sense because it should not need to be called every tick but instead should just be handled by an event that hooks into everywhere that needs to be reset only running when command is used?

**Comment by Virtuoel** [comment]
The 3.2.0 version of Pehkui has introduced various performance improvements.
If your performance with 3.2.0 is still inadequate, please post a new Spark profile.

**Comment by HacoKavanah** [comment]
Version Pehkui-3.2.2+1.14.4-1.19.jar severely affected the performance of my world and the game starts up 10x slower with it. Downgrading to Pehkui-3.2.1+1.14.4-1.19.jar solves the issue. Decided to post this here since it basically sounds like the same issue.

**Comment by Virtuoel** [comment]
> Version Pehkui-3.2.2+1.14.4-1.19.jar severely affected the performance of my world and the game starts up 10x slower with it. Downgrading to Pehkui-3.2.1+1.14.4-1.19.jar solves the issue. Decided to post this here since it basically sounds like the same issue.

Can you test again with Pehkui 3.3.0?

Note: if on 1.19 snapshots, the vanilla game appears to have a minute or more of high CPU usage after starting up the game. For those versions it's best to wait for the CPU usage to fall back down or wait for the console to print
`____ Datafixer optimizations took _____ milliseconds`
before continuing with checking performance impact.

**Comment by HacoKavanah** [comment]
Using 1.18.2! Been playing with 3.3.0 for a little while now, feels really good!

**Comment by Virtuoel** [comment]
More performance improvements were added back in the 3.6.0 update.

I'm also consolidating all performance related issues into one big issue: https://github.com/Virtuoel/Pehkui/issues/375
If you still run into performance issues, add a comment with a Spark profiler report to that issue.
