### ISSUE TITLE
is not compatible with the latest version of fabric Api

### ISSUE THREAD

**Issue by Phantom912** [Virtuoel/Pehkui#21]
it just closes when I try to use the latest API and says "Could not find required mod: pehkui requires {fabric-command-api-v1 @ [*]}"

in case you ask since it's not technically crashing there is no crash report

**Comment by Virtuoel** [comment]
Resolved with 49067bdd837ce503ad4c83594ada088397588d88 and b50d7580e88700bcf05b3f3f306ed4bbffddf24e
