### ISSUE TITLE
How can I disable scale commands?

### ISSUE THREAD

**Issue by Lampstern** [Virtuoel/Pehkui#210]
### What is your suggestion?

I don't want anyone to be able to use scale commands. Which file(s) should I delete to fix this problem?

**Comment by Virtuoel** [comment]
The commands are only usable by players that have high enough permissions, e.g. players that have been `/op`d. If you're wanting to restrict this even further, would a config option that removes the commands entirely be sufficient?

**Comment by Lampstern** [comment]
Yes, but I don't know how to do that.
