### ISSUE TITLE
[Bug]: Pehkui not working with Aternos server

### ISSUE THREAD

**Issue by aintgotenoughcoffee** [Virtuoel/Pehkui#211]
### Minecraft version(s)

1.17.1

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.12.5

### Fabric API version

Fabric API 0.42.1

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I was making an origins server with friends (with custom origins), but for some odd reason when we started none of the pehkui powers worked. They did work in a singleplayer world, so I thought it was strange, and I thought it must be some sort of bug with the code but then I realized the commands didn't show up either. I ended up figuring out that the entire mod just doesn't show up on the server, which I can't find any reason for. And yes it is installed on both client side and server side. I'm using Aternos for the server, by the way.

### Full list of installed mods

- Basic Nether Ores 6.0.0
- Fabric API 0.42.1
- Ferritecore 3.1.0
- Mod Menu 2.0.14
- Origins 1.1.4
- Pehkui 2.5.3

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by RuizaHQ** [comment]
Is there any updates? i am having the same issue than this person

**Comment by aintgotenoughcoffee** [comment]
> 

@RuizaHQ I figured out the problem on my side and hopefully this will work with yours. Does your Pehkui file have "-sources" at the end? Then thats the reason. If thats it then reinstall it from curseforge so that it doesnt have that ending. Should look like this
![image](https://user-images.githubusercontent.com/93180019/142991712-ce10bda8-eca1-453b-b0ba-ddc6932b9c65.png)

**Comment by Virtuoel** [comment]
Oh great, not that sources issue again.
Should hopefully now be fixed. Will wait for others to respond before closing.

**Comment by aintgotenoughcoffee** [comment]
> Oh great, not that sources issue again. Should hopefully now be fixed. Will wait for others to respond before closing.

Thank you for your help! It's fixed on my side but unsure about others

**Comment by Virtuoel** [comment]
Other person's still not responded yet, so I'll assume it's fixed. If you're still having this problem, please open another issue.
