### ISSUE TITLE
[Bug]: command don't exist

### ISSUE THREAD

**Issue by QuibopWon** [Virtuoel/Pehkui#217]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

1.16.5

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

so basically when i try to type /scale, it says unknown or incomplete command

### Full list of installed mods

abnormal's core, appleskin, autoreglib, cavebiomeapi, caves and cliffs backport, construction wand, core ascension, create, enhanced mushrooms, environmental, flywheel. hwyla, immersive portals, jei, nonetherfog, offline skins, optifine, pehkui, quark, selene, supplementaries, total darkness, worldedit and xaero's minimap

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

i didn't experience a crash

**Comment by Virtuoel** [comment]
Fixed in 25f3c57e65a1fd14b82d11d6b049aab201a4d3dc
You might also need to go to the Pehkui config and set `enableCommands` to `true`.
