### ISSUE TITLE
[1.16.3] Animations slow down/speed up "unrealistically" when scaled down/up

### ISSUE THREAD

**Issue by Jarfeh** [Virtuoel/Pehkui#22]
By unrealistically, I mean they either move too quickly, or too slowly.

**Comment by ImSpaceLover** [comment]
Issue wasn't fixed

**Comment by Virtuoel** [comment]
Can you specify which animations are still having issues in the latest (1.7.0) version?

**Comment by ImSpaceLover** [comment]
Walking animation. Player's legs moves much slower when the player is smaller and moves faster when the player is bigger. It looks weird when you goes through the portal from Immersive Portals mod and you suddenly begins moving slower.

**Comment by ImSpaceLover** [comment]
I made a video showing it https://youtu.be/8dZ_nh8a5fk

**Comment by Virtuoel** [comment]
The video appears to currently be private. Maybe you could make it unlisted instead?
If you prefer, it is possible to directly upload a video file to a comment.

I've been doing some testing, but so far I am unable to reproduce the leg movement issue with `Pehkui-1.7.0+20w51a.jar` and `immersive-portals-0.55-mc1.16.4-fabric.jar` on 1.16.4.

**Comment by ImSpaceLover** [comment]
Oops, sorry. I opened it.

**Comment by Virtuoel** [comment]
Unable to reproduce with `Pehkui-1.7.0+20w51a.jar` and `immersive-portals-0.55-mc1.16.4-fabric.jar` on 1.16.4.

https://user-images.githubusercontent.com/8584461/103707189-4599fe80-4fbf-11eb-83bd-cb5c1fe2d6b7.mp4

**Comment by ImSpaceLover** [comment]
Oh, sorry, I am really dumb. I installed the new version but didn't put it in the mods folder. Issue can be closed.
