### ISSUE TITLE
[Bug]: TapL's You Grow Every Minute CHALLENGE (RECREATION) 

### ISSUE THREAD

**Issue by iFarkedilmem** [Virtuoel/Pehkui#220]
### Minecraft version(s)

1.16.5

### Minecraft version details

1.17 - 1.16.5 Fabric

### Mod loader

Fabric

### Mod loader version

1.16.5

### Fabric API version

1.16.5

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

[crash-2021-12-04_20.41.00-server.txt](https://github.com/Virtuoel/Pehkui/files/7657087/crash-2021-12-04_20.41.00-server.txt)

https://www.curseforge.com/minecraft/mc-mods/tapls-you-grow-every-minute-challenge-recreation/files

I can't use your mod on my server. I have posted the error codes as txt. Can you review?

### Full list of installed mods

https://www.curseforge.com/minecraft/mc-mods/tapls-you-grow-every-minute-challenge-recreation/files

https://www.curseforge.com/minecraft/mc-mods/fabric-api/download/3483905

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

I open the serve
[crash-2021-12-04_20.41.00-server.txt](https://github.com/Virtuoel/Pehkui/files/7657110/crash-2021-12-04_20.41.00-server.txt)
r. After the code I wrote to run the mod, the server shuts itself down.

**Comment by Virtuoel** [comment]
That is in fact not my mod. That is someone else's mod using the code from mine directly for whatever reason instead of using a proper Jar-in-Jar Pehkui dependency. Report to that mod's creator instead.
