### ISSUE TITLE
[Bug]: Collisions

### ISSUE THREAD

**Issue by THETENTRIO** [Virtuoel/Pehkui#222]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

Forge-36.2.1

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

When you resize yourself smaller your hitbox won't collide with the ceiling properly. I'm not sure about being bigger.

### Full list of installed mods

Just this one.

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
~~I'm unable to reproduce this issue. Can you provide some more info, e.g. steps to reproduce, or images, or a video, etc?
Does this still occur for you in Pehkui 3.1.0?~~
Confirmed in 3.1.0.
