### ISSUE TITLE
[Bug]: Null `base` type

### ISSUE THREAD

**Issue by GiantLuigi4** [Virtuoel/Pehkui#223]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.9

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Sometimes when loading the game, the base type will be null
I'm not sure how long this has been happening for, but it's been a thing since atleast pehkui 2.3.0

### Full list of installed mods

forge-1.16.5-36.2.9-client.jar 1.16.5
FramedBlocks 2.11.0
Repurposed Structures 3.4.1+1.16.5
The One Probe 1.16-3.1.4
Helium 1.0
Ferrite Core 2.1.0
Just Enough Items 7.7.1.137
Pehkui 3.0.1+1.16.5-forge 
Camera Overhaul 1.0.0
Forge 36.2.9
Flywheel 1.16-0.2.4.custom
CodeChicken Lib  4.0.3.434
CBMultipart 3.0.2.120
Create v0.3.2f
Chisels & bits 0.3.4-RELEASE
Smallerunits 1.2
Gravestone Mod 1.16.5-1.0.6
CollisionReversion

Afaik, the only ones which might be relevant are pehkui, SU, and Collision Reversion

[Collision Reversion (cuz it's not on CF yet, I'm still working on it)](https://cdn.discordapp.com/attachments/892136637604171806/912522539677405214/CollisionReversion-1.0-SNAPSHOT.jar)
[Specific build of SU which I uploaded with that version of collision reversion](https://cdn.discordapp.com/attachments/892136637604171806/912522539463508028/smallerunits-1.16.jar)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

https://pastebin.com/fxQ5BwSr

**Comment by GiantLuigi4** [comment]
huh, I get the feeling I should put that crash report on a gist or paste

done

**Comment by Virtuoel** [comment]
Appears to be resolved on SU's end now that the Pehkui compat call has been moved to `FMLCommonSetupEvent`.
