### ISSUE TITLE
Is there a way to scale things instantly?

### ISSUE THREAD

**Issue by jacob-cob** [Virtuoel/Pehkui#225]
### What is your suggestion?

I want to scale things gradually, but when you scale things it takes about a second, which when constantly scaling little by little, can be very slow. So is there a way to instantly scale things instantly, like when you reset your size? If not, it would be really cool if you could add an extra parameter to the /scale command to add the time needed for scaling.

example: /scale 10 player 0.1(the time in seconds to scale the player)

**Comment by Virtuoel** [comment]
The scaling delay is a separate property changed via `/scale delay set <delay in ticks>`, e.g. two seconds of delay would be `/scale delay set 40`, instant would be `/scale delay set 0` and so on.
