### ISSUE TITLE
[Bug]: I cant scale myself

### ISSUE THREAD

**Issue by MinecraftCitizen** [Virtuoel/Pehkui#233]
### Minecraft version(s)

1.15.2

### Minecraft version details

Did not use a snapshot

### Mod loader

Fabric

### Mod loader version

I forgot

### Fabric API version

I forgot

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Nothing happened

### Full list of installed mods

Immersive Portals and Pekhui and Mod menu

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Unfortunately Immersive Portals for 1.15.2 did not support scaling with Pehkui yet. On 1.16.5 and newer it does though.
