### ISSUE TITLE
[Bug]: Unable to break blocks at small scale

### ISSUE THREAD

**Issue by GamyGamer** [Virtuoel/Pehkui#234]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.18.1

### Mod loader

Fabric

### Mod loader version

fabric-loader-0.12.11-1.18.1

### Fabric API version

fabric-api-0.44.0+1.18.jar

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

What happens:
I am unable to place/break blocks at low scale (tested at 0.25)

Expected:
I should be able to break blocks

How to reproduce
/scale set 0.25
try to break block
that's really it (You will see typical breaking animation but block reappear as if I didn't break it at all)

### Full list of installed mods

Pehkui-3.0.0+1.14.4-1.18
fabric-api-0.44.0+1.18

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Should now be resolved in 3.1.0. Let me know if this still occurs.
