### ISSUE TITLE
[Bug]: Scale not persisting, resetting after a few seconds

### ISSUE THREAD

**Issue by netcore10** [Virtuoel/Pehkui#236]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.22

### In what environment did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

Scale persistence resets after a few seconds after death, for the life of me I can't figure out what mod is affecting it. It works on its own. Are there any known mods that are already known that might affect it?

### Full list of installed mods

GoProne (by Alpvax)
Wonderful Enchantments (by Majrusz17)
Bookshelf (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
Bayou Blues (Forge) (by team_aurora_modding)
Abundance (by team_aurora_modding)
Persistent Players (by henkelmax)
Default Options (by BlayTheNinth)
Mekanism Additions (by bradyaidanc)
BlockCarpentry (by PianoManu)
Nether's Delight (by lumpazl)
Refined Storage Addons (by raoulvdberge)
Create Crafts & Additions (by MRHminer)
CC: Tweaked (by SquidDev)
Underwater Enchanting (Forge) (by Serilum)
Iron Age Furniture (by SkyBlade1978)
ConnectedTexturesMod (by tterrag1098)
Sulfuric (by someoneelsewastaken)
Engineer's Decor (by wilechaote)
RandomPatches (Forge) (by TheRandomLabs)
Majrusz Library (by Majrusz17)
TellMe (by masady)
Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)
Ars Nouveau (by baileyholl2)
Carry On (by Tschipp)
Ender Storage 1.8.+ (by covers1624)
Darker Depths (by naterbobber)
JEITweaker (by Jaredlll08)
Absent by Design (by Lothrazar)
Upgrade Aquatic (by TeamAbnormals)
Simple Voice Chat (by henkelmax)
Storage Drawers (by Texelsaur)
MrCrayfish's Furniture Mod (by MrCrayfish)
TRansliterationLib (by tr9zw)
FlashFyre's Enchantments (by f1ashfyre)
AppleSkin (by squeek502)
Industrial Foregoing (by Buuz135)
Joy of Painting (by xerca0)
Create Stuff Additions (by Furti_Two)
Initial Inventory (by Jaredlll08)
Farmer's Delight Cookbook Addon [0.4 is the last update] (by dalumma)
First-person Model (Forge/Fabric) (by tr9zw)
Waystones (by BlayTheNinth)
Open Loader (by DarkhaxDev)
CreateTweaker (by Jaredlll08)
Konkrete [Forge] (by Keksuccino)
Xaero's World Map (by xaero96)
AI Improvements (by QueenOfMissiles)
Kiwi 🥝 (Forge) (by Snownee_)
Atum 2: Return to the Sands (by Shadowclaimer)
Allurement (by TeamAbnormals)
Buzzier Bees (by TeamAbnormals)
Silent Lib (silentlib) (by SilentChaos512)
Bedspreads (Forge) (by TheIllusiveC4)
Infernal Expansion (by InfernalStudios)
MineColonies (by H3lay)
Snow! Real Magic! ⛄ (by Snownee_)
Runelic (by DarkhaxDev)
Dragon Gear (by Partonetrain)
Citadel (by alex_khaan)
Fishing Real (by PricelessKoala)
Titanium (by Buuz135)
spark (by Iucko)
Silent Gear (by SilentChaos512)
More Snow (by mrp_v2)
GeckoLib (by ThanosGecko)
Dark Utilities (by DarkhaxDev)
Pam's HarvestCraft 2 - Trees (by pamharvestcraft)
Cryness Double Slabs (by crynesss)
Immersive Engineering (by BluSunrize)
More Create Stuffs (by JerryLu086)
Biomes O' Plenty (by Forstride)
The Endergetic Expansion (by TeamAbnormals)
Chisel (by tterrag1098)
Arrows Break Torches (by Trhod177)
Server Tab Info (by black_dog20)
Fairy Lights (by pau101)
Macaw's Trapdoors (by sketch_macaw)
Clickable advancements[Forge/Fabric] (by someaddon)
Dynamic Surroundings (by OreCruncher)
Create (by simibubi)
Camera Mod (by henkelmax)
Connectivity (by someaddon)
FancyMenu [Forge] (by Keksuccino)
Apotheosis (by Shadows_of_Fire)
Neko's Enchanted Books (by Nekomaster1000)
RoadRunner (by MaxNeedsSnacks)
Farmer's Delight Compats (by burritoeatinghamster)
Patchouli (by Vazkii)
Unique Enchantments - Battle (by Speiger)
Building Gadgets (by Direwolf20)
Realistic Horse Genetics (by sekelsta)
Biome Id Fixer (Forge) (by desagas)
More Minecarts and Rails (by goldey3)
Structurize (by H3lay)
Farsight[Forge/Fabric] (by someaddon)
BetterEnd Reforked (by someoneelsewastaken)
Limited Chunkloading (by someaddon)
Blood Magic (by WayofTime)
Macaw's Windows (by sketch_macaw)
Corpse Complex (by TheIllusiveC4)
CraftTweaker (by Jaredlll08)
Orcinus's Caves (by orcinus73)
Refined Storage (by raoulvdberge)
Mekanism (by bradyaidanc)
Unique Enchantments (by Speiger)
Ensorcellation (by TeamCoFH)
Smooth Boot (Forge) (by UltimateBoomer)
Drippy Loading Screen [Forge] (by Keksuccino)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Unique Enchantments - Utils (by Speiger)
Create Deco (by talrey)
Advanced Peripherals (by srrendi)
Unique Enchantments Base (by Speiger)
FerriteCore (Forge) (by malte0811)
The Bumblezone (Forge) (by telepathicgrunt)
CodeChicken Lib 1.8.+ (by covers1624)
CaveBiomeAPI [Forge] (by blackgear27)
Load My Resources [Forge] (by Keksuccino)
Akashic Tome (by Vazkii)
Macaw's Lights and Lamps (by sketch_macaw)
Artifacts (by ochotonida)
Pam's HarvestCraft 2 - Crops (by pamharvestcraft)
Macaw's Paintings (by sketch_macaw)
Enchanting Commands (Forge) (by Serilum)
Transport (by Sky_Som)
Curious Armor Stands (by ochotonida)
Supplementaries (by MehVahdJukaar)
Music Maker Mod (by xerca0)
[Add-On] The Abyss: Beginning (by y4z0n)
CoFH Core (by TeamCoFH)
Cooking for Blockheads (by BlayTheNinth)
Serene Seasons (by TheAdubbz)
Just Enough Resources (JER) (by way2muchnoise)
Farmer's Delight (by vectorwing)
Cosmetic Armor Reworked (by LainMI)
Aquaculture 2 (by Shadowclaimer)
Macaw's Fences and Walls (by sketch_macaw)
CreativeCore (by CreativeMD)
Scuba Gear (by ModdingLegacy)
Macaw's Bridges (by sketch_macaw)
Collective (Forge) (by Serilum)
Snow Under Trees (by bl4ckscor3)
Clumps (by Jaredlll08)
Pehkui (by Virtuoel)
The Abyss II - The Other Side (by y4z0n)
DrawerFPS (by someaddon)
The Twilight Forest (by Benimatic)
Leap (by ModdingLegacy)
Nature's Compass (by Chaosyr)
Comforts (Forge) (by TheIllusiveC4)
Iron Chests (by ProgWML6)
AutoRegLib (by Vazkii)
Blueprint (by TeamAbnormals)
Builders Crafts & Additions (Forge) (by MRHminer)
Fast Leaf Decay (by olafskiii)
Cyclic (by Lothrazar)
Autumnity (by TeamAbnormals)
Lightmans Currency (by Lightman314)
MrCrayfish's More Furniture Mod (by MrCrayfish)
Curios API (Forge) (by TheIllusiveC4)
MarbleGate's Exotic Enchantment: Flowing Agony (by marblegatekeeper)
FancyHud (by Keksuccino)
Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)
FPS Reducer (by bre2el)
Corpse (by henkelmax)
Macaw's Roofs (by sketch_macaw)
Ice and Fire: Dragons (by alex_khaan)
Alex's Mobs (by alex_khaan)
Immersive Cooking (by CrimsonDragonRider)
Not Enough Animations (Forge/Fabric) (by tr9zw)
Inventory Tweaks Renewed (by David1544)
Mouse Tweaks (by YaLTeR)
Flywheel (by jozufozu)
Torch Slabs Mod (by EndlesNights)
More Overlays Updated (by RiDGo8)
Torchmaster (by xalcon)
ExpandAbility (by florensie)
Not Enough Crashes (Forge) (by NatanFudge)
Macaw's Doors (by sketch_macaw)
Extended Slabs + (by RealBlackout03)
Controlling (by Jaredlll08)
Caves & Cliffs Backport (by blackgear27)
Xaero's Minimap (by xaero96)
Hwyla (by TehNut)
Macaw's Furniture (by sketch_macaw)
Customizable Player Models (by tom54541)
Selene Lib (by MehVahdJukaar)
Placebo (by Shadows_of_Fire)
AmbientSounds 5 (by CreativeMD)
Glow Bats (by RedLikeRose0)

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Does this issue still occur in Pehkui 3.1.0?

**Comment by netcore10** [comment]
Indeed it does.

**Comment by netcore10** [comment]
indeed it does.

**Comment by Virtuoel** [comment]
Should now be resolved with Pehkui 3.3.0.
