### ISSUE TITLE
[Bug]: Scaled-up boats sink

### ISSUE THREAD

**Issue by bravely-beep** [Virtuoel/Pehkui#239]
### Minecraft version(s)

1.18.1

### Minecraft version details

1.18.1

### Mod loader

Fabric

### Mod loader version

fabric-loader-0.12.12-1.18.1

### Fabric API version

fabric-api-0.45.0+1.18.jar

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

What I did:
Scale a boat up to 2.5 or higher

What I expected:
It floats

What happened:
It sinks

### Full list of installed mods

fabric-api-0.45.0+1.18.jar
Pehkui-3.1.0+1.14.4-1.18.1.jar

### Did the problem cause the game to crash?

No.

**Comment by DhaneshAbhipraya** [comment]
realistic
