### ISSUE TITLE
Every player stays weirdly scaled after using with origins extras. (1.16.4)

### ISSUE THREAD

**Issue by ProfEnd** [Virtuoel/Pehkui#24]
I'm running a server and for some reason after installing origins extras, all players become scaled to what one of the origins is. The height stays the same it seems, but the width and length of the player changes to the origin. This causes a big head on the normal player. After removing the mods, it stays the same and the hitbox is the normal player one. It doesn't occur in singleplayer, but only on the server. I'm not entirely sure that this mod is the source of the problem, but I can't find the exact cause.

Modlist- https://drive.google.com/file/d/1IWQm7mQ4fsdzaEMAscu-BOiBu5ISYj5x/view
Log file- 
[latest.log](https://github.com/Virtuoel/Pehkui/files/5550690/latest.log)

**Comment by Virtuoel** [comment]
Mods using Pehkui can now also use the new scale modifier system introduced in 73d1671d3280ef1106ea75292f96b0d48102e1a0.
Once those mods update to use the new system, this issue should no longer occur when mods are removed.
