### ISSUE TITLE
[Suggestion]: Add sanity checks

### ISSUE THREAD

**Issue by bravely-beep** [Virtuoel/Pehkui#240]
### What is your suggestion?

So players can't type `/scale set -1` and crash the game

**Comment by ChristianKilduff** [comment]
that doesnt seem like an enhancement that a bug? or more so error

**Comment by WanderingCat27** [comment]
[penkui-profile.zip](https://github.com/Virtuoel/Pehkui/files/8187522/penkui-profile.zip)

**Comment by Virtuoel** [comment]
With scale limit configs now present on Fabric & Forge, admins should now be able to configure the scale types that they want to keep within certain ranges.
