### ISSUE TITLE
Trying to use 3.1.0-forge fails: 

### ISSUE THREAD

**Issue by fenrir6969** [Virtuoel/Pehkui#241]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

Forge 36.2.9

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

I'm using forge 1.16.5. I'm trying to upgrade from Pehkui version 2.5.3 to 3.1.0 per 
https://www.curseforge.com/minecraft/mc-mods/pehkui/files/all?filter-game-version=2020709689%3A8203

With 
```
pehkui_version=2.5.3-forge
```
in gradle.settings it builds, and runs, but crashes during startup (with mixin problem). 
Trying to upgrade to 3.1.0 to sove the mixin issue but changing the line above to
```
pehkui_version=3.1.0-forge
```
Gives me a build error:

```
Could not resolve all files for configuration ':runtimeClasspathCopy'.
> Could not find com.github.Virtuoel:Pehkui:3.1.0-forge_mapped_official_1.16.5.
  Searched in the following locations:
    - file:/Users/Tobi/.gradle/caches/forge_gradle/bundeled_repo/com/github/Virtuoel/Pehkui/3.1.0-forge_mapped_official_1.16.5/Pehkui-3.1.0-forge_mapped_official_1.16.5.pom
    - file:/Users/Tobi/.gradle/caches/forge_gradle/bundeled_repo/com/github/Virtuoel/Pehkui/3.1.0-forge_mapped_official_1.16.5/Pehkui-3.1.0-forge_mapped_official_1.16.5.jar
  Required by:
      project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
Could not resolve all files for configuration ':runtimeClasspathCopy'.
> Could not find com.github.Virtuoel:Pehkui:3.1.0-forge_mapped_official_1.16.5.
  Searched in the following locations:
    - file:/Users/Tobi/.gradle/caches/forge_gradle/bundeled_repo/com/github/Virtuoel/Pehkui/3.1.0-forge_mapped_official_1.16.5/Pehkui-3.1.0-forge_mapped_official_1.16.5.pom
    - file:/Users/Tobi/.gradle/caches/forge_gradle/bundeled_repo/com/github/Virtuoel/Pehkui/3.1.0-forge_mapped_official_1.16.5/Pehkui-3.1.0-forge_mapped_official_1.16.5.jar
  Required by:
      project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### Full list of installed mods

None!
This was in the IntelliJ IDEA CE environment.

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
The version numbers for the 1.16.5 Forge versions were recently noticed to be inconsistent with the rest of the Forge versions, so new ones now get the MC version added to them like the others.
According to the list of [tags](https://github.com/Virtuoel/Pehkui/tags), the version number you want is `3.1.0-1.16.5-forge`.
