### ISSUE TITLE
[Bug]: Crash immediately on load starting.

### ISSUE THREAD

**Issue by Darkmega18** [Virtuoel/Pehkui#249]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.28

### In what environment did the problem occur?

First few moments of game start-up

### What went wrong? (Crash logs don't go here)

As soon as I start my modpack with the most up to date mods available to it from the mods it uses the game crashes with a rather fatal looking error. The modpack in question is "Order of All Creation: Relic Hunters". I had updated all the mods currently contained in it to their latest available versions and this happened. Turning off pekhui and customizable player models enables the game to load fine.

### Full list of installed mods

see crash log or take a look at my mod pack... I run out of comment length posting it straight out of the crash log.

### Did the problem cause the game to crash?

Yes. very quickly.

### Full crash report contents (if you experienced a crash)
I can't do as you ask and post it here, because the comment becomes too long. thats how bad it is.

here is the file instead. it might just be easier to look at it in notepad++ or something:
[crash-2022-02-22_21.44.03-client.txt](https://github.com/Virtuoel/Pehkui/files/8115941/crash-2022-02-22_21.44.03-client.txt)

**Comment by Virtuoel** [comment]
Should now be resolved with the 3.2.0 release.

**Comment by Darkmega18** [comment]
it was. thanks.
