### ISSUE TITLE
[Bug]: Jump Height is not a valid command in game

### ISSUE THREAD

**Issue by Patrick12411** [Virtuoel/Pehkui#250]
### Minecraft version(s)

1.18.1

### Mod loader

Fabric

### Mod loader version

0.10.2

### Fabric API version

0.46.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Jump height modification is listed on the mod's web page but in game is not recognized as a valid command.

### Full list of installed mods

https://puu.sh/IKXah/f044c7bd7b.png

This is a screenshot of my mods folder.

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Fisch37** [comment]
Can confirm this happening with only Pehkui
+ Fabric Version: 0.13.3
+ API Version: 0.46.6
+ Environment: Test environment: New world with skeleton setup

**Comment by Virtuoel** [comment]
Resolved with 3.2.0 release.
