### ISSUE TITLE
[Bug]: server crashes upon start

### ISSUE THREAD

**Issue by StarShooter49** [Virtuoel/Pehkui#251]
### Minecraft version(s)

1.16.5

### Mod loader

Fabric

### Mod loader version

0.11.7

### Fabric API version

0.31.01.16

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

When playing in a single player test world, it worked great, everything was doing what it was supposed to, but when we tried to add it to the server it would crash upon starting. We tried several things, including several versions of this mod, but could not get it to work

### Full list of installed mods

byg 1.1.8
cloth-config
fabric api 0.31.01.16
optifabric 1.11.9
OptiFine_1.16.5_HD_U_G8
origins 0.7.3
RoughlyEnoughItems-5.10.184
voicechat-fabric-1.16.5-1.9.9
wraith-waystones-1.1.1.1
Xaeros_Minimap_21.4.1_Fabric_1.16.5

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

I do not have a copy of the crash report, but it sums up to Pehkui requiring the fabric loader to work

**Comment by Virtuoel** [comment]
Your Fabric Loader version (0.11.7) is too old. Updating to a newer version using the Fabric installer, e.g. to 0.13.3, should fix the issue.
