### ISSUE TITLE
[Bug]: one point eighteen point two updat for the pehkui

### ISSUE THREAD

**Issue by sylv256** [Virtuoel/Pehkui#252]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

one point eighteen point two updat for the pehkui

### Mod loader

Fabric

### Mod loader version

farbric 0.13.three

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

the mod is unot updated to one point eighteen point two updat for the pehkui

### Full list of installed mods

all of them

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

decrypting...
decrypting...
acess denied

hacking...
access granted (based)

error: one point eighteen point two updat for the pehkui not installed, critical malfunction, 1010101101111

**Comment by sylv256** [comment]
please excuse my bad grammar it's 00:29 oiadsfj ok

**Comment by Virtuoel** [comment]
Resolved with 3.2.0 release.
