### ISSUE TITLE
[Bug]: No Minimum Limit

### ISSUE THREAD

**Issue by MinerB4** [Virtuoel/Pehkui#253]
### Minecraft version(s)

1.18.1

### Mod loader

Forge

### Mod loader version

Forge 39.1.0

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

You can set scale to a value smaller than reasonable, I set size to -1 and the game crashed.

### Full list of installed mods

Not required, issue is with the mod itself.

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

Crash Report was not created for some reason...

**Comment by Virtuoel** [comment]
Should now be resolved on Forge with Pehkui 3.3.0. Scale limit configs are in the server config folder in the world folder, and should get synced to connecting players.
