### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Mazereck** [Virtuoel/Pehkui#264]
### Minecraft version(s)

1.16.5

### Mod loader

Fabric

### Mod loader version

Fabric 0.13.3

### Fabric API version

Fabric API 0.30.0

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Upon adding Pehkui to a modpack it crashes on startup without generating a crash report, i have provided the log file instead.

### Full list of installed mods

        - addendum 1.16.5-1.0.2
	- additionalbars 2.0.4
	- adorn 1.14.2+1.16.5
	- advanced_runtime_resource_pack 0.4.3 via enhancedblockentities
	- advancements-enlarger 0.2.3
	- advdebug 2.3.0
	- adventurez 1.2.6
	- alloy_forgery 1.2.0
	- amecsapi 1.3.5+mc1.16.5 via mousewheelie
	- angerable-patch 1.1.0-1.16.4 via repurposed_structures
	- appleskin 2.3.0+mc1.16.5
	- appliedenergistics2 8.4.0-alpha.3
	- aqupdcaracal 1.16-1.3.5
	- aqupdgrizzly 1.16-1.2.2
	- architects_palette 1.0
	- architectury 1.26.42
	- armorhotswap 1.2
	- artifacts 4.0.3+fabric
	- artifice 0.14.6+1.16.5 via secretrooms
	- astromine 1.11.6+fabric-1.16.5
	- astromine-core 1.11.+fabric-1.16.5 via astromine
	- astromine-discoveries 1.11.6+fabric-1.16.5 via astromine
	- astromine-foundations 1.11.6+fabric-1.16.5 via astromine
	- astromine-technologies 1.11.6+fabric-1.16.5 via astromine
	- astromine-transportations 1.11.6+fabric-1.16.5 via astromine
	- attributefix 1.0.2
	- authme 2.1.0
	- autoconfig1u 3.3.1 via bettermineshafts
	- autoconfigtoml 1.0.0-fabric via vanilladeathchest
	- autofish 0.9.2
	- awesomedungeon 2.0.5
	- bambootweaks 2.0.1+1.16.5
	- bannerpp 2.0.3-snapshot+mc.1.16.2-rc1 via entitybanners
	- basicshields 1.2.1-1.16.5
	- battletowers 3.3.4-1.16.4
	- bclib 0.1.45
	- bedspreads 1.3.1-1.16.4
	- beenfo 1.16.5-fabric0.30.0-1.3.2
	- betteranimalsplus 1.16.5-11.0.4
	- bettercaves 1.16.5-1.2
	- betterdungeons 1.16.5-1.0.1
	- betterend 0.9.8.5-pre
	- betterf3 1.1.3
	- bettermineshafts 1.16.4-1.0.2
	- betternether 5.0.7
	- betterthanmending 1.3.0
	- biome_locator 1.1.2
	- biomemakeover 1.16.5-1.3.8
	- blade 2.0.0 via astromine-core
	- blast 1.5.2
	- blockshifter 1.4.0+fabric-1.16.4
	- blockus 2.1.12+1.16.5
	- blue_endless_jankson 1.2.0 via kyrptconfig
	- boringbackgrounds 3.0.2+1.16.3
	- bowinfinityfix rv9
	- breakprogress 1.0.1
	- byg 1.1.8
	- caelus 0.0.15-1.16.4
	- can-i-mine-this-block 1.0.2
	- cardinal-components 2.8.3
	- cardinal-components-base 2.8.3 via artifacts
	- cardinal-components-block 2.8.3 via cardinal-components
	- cardinal-components-chunk 2.8.3 via cardinal-components
	- cardinal-components-entity 2.8.3 via artifacts
	- cardinal-components-item 2.8.3 via cardinal-components
	- cardinal-components-level 2.8.3 via cardinal-components
	- cardinal-components-scoreboard 2.8.3 via cardinal-components
	- cardinal-components-util 2.8.3 via cardinal-components
	- cardinal-components-world 2.8.3 via cardinal-components
	- carrier 1.7.6
	- cavebiomes 0.6.2
	- charm 2.3.2
	- chat_heads 0.6.0
	- chatplus 1.0.1
	- cherishedworlds 2.0.1-1.16.5
	- chickensshed 1.16.5-1.0.0
	- chunky 1.2.54
	- cinderscapes 1.4.0
	- cleancut mc1.16-2.1-fabric
	- cloth-api 1.4.9
	- cloth-armor-api-v1 1.5.47 via modern_industrialization
	- cloth-basic-math 0.6.0 via cloth-config2
	- cloth-client-events-v0 1.5.47 via roughlyenoughitems
	- cloth-common-events-v1 1.5.47 via modern_industrialization
	- cloth-config2 4.13.49
	- cloth-datagen-api-v1 1.4.9 via cloth-api
	- cloth-durability-bar-api-v1 1.5.47 via indrev
	- cloth-dynamic-registry-api-v1 1.4.9 via cloth-api
	- cloth-scissors-api-v1 1.4.9 via cloth-api
	- cloth-utils-v1 1.4.9 via cloth-api
	- coat 1.0.0-beta.14 via mousewheelie
	- collective-fabric 4.12
	- colytra 1.3.0-1.16.4
	- com_electronwill_night-config_core 3.6.3 via computercraft
	- com_electronwill_night-config_toml 3.6.3 via computercraft
	- com_github_nathanpb_safer 1.1.0 via dml-refabricated
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- comforts 0.0.6-1.16.5
	- compacthelpcommand-fabric 1.1
	- companion_bats 1.15.2
	- compressedblocks 1.0
	- computercraft 1.96.3
	- conjuring 0.2.5
	- connectiblechains 1.2.2
	- controlling 1.1.2
	- couplings 1.3.3
	- craftpresence 1.8.8
	- crookedcrooks 1.3.3+1.16.4
	- croptopia 1.4.0
	- croptosis 1.1.0
	- crowdin-translate 1.3+1.16 via beenfo
	- curioofundying 1.1.1-1.16.5
	- curios 0.0.13-1.16.5
	- curiouselytra 1.1.1-1.16.5
	- customizableelytra 1.5.2-1.16.4
	- customportalapi 0.0.1-beta32-1.16 via gobber2
	- danceofgrowth 1.0
	- dankstorage 1.10a-1.16.5
	- dark-enchanting 0.2.1+mc.1.16.5
	- darkpaintings 3.0.4
	- deep-dungeons 1.0.0-1.16.5
	- defaultsettings 3.0.2
	- desolation 1.1.2
	- diggusmaximus 1.4.2-1.16.3
	- direbats 1.1.1+1.16.5-fabric
	- disable_custom_worlds_advice 1.4
	- dml-refabricated 0.3.3-beta1
	- dragonloot 1.0.6
	- drinkbeer 3.0.2
	- drippyloadingscreen 1.5.1
	- dungeonsmod 1.16.5-1.0.14
	- earthtojavamobs 1.7.1+1.16.4
	- eggtab 2.1.0+1.16-fabric
	- emeraldextendedfabric 0.1.1
	- enchdesc 2.0.8
	- end_additions 1.1
	- enhanced_attack_indicator 1.0.1
	- enhancedblockentities 0.4
	- enhancedcelestials 2.0.6
	- entitybanners 1.0-BETA
	- entityculling 1.3.0
	- expandability 2.0.1 via artifacts
	- expandedstorage 7.3.7
	- extraalchemy 1.4.5
	- extragenerators 1.0.3-BETA+1.16
	- fabric 0.42.0+1.16
	- fabric-api-base 0.4.0+3cc0f0907d via fabric
	- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d via fabric
	- fabric-biome-api-v1 3.1.13+3cc0f0907d via fabric
	- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d via fabric
	- fabric-command-api-v1 1.1.3+3cc0f0907d via fabric
	- fabric-commands-v0 0.2.3+3cc0f0907d via fabric
	- fabric-containers-v0 0.1.12+3cc0f0907d via fabric
	- fabric-content-registries-v0 0.2.5+3cc0f0907d via fabric
	- fabric-crash-report-info-v1 0.1.4+3cc0f0907d via fabric
	- fabric-dimensions-v1 2.0.8+3cc0f0907d via fabric
	- fabric-entity-events-v1 1.2.4+3cc0f0907d via fabric
	- fabric-events-interaction-v0 0.4.5+3cc0f0907d via fabric
	- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d via fabric
	- fabric-furnaces 1.3.3-1.16.4
	- fabric-game-rule-api-v1 1.0.7+3cc0f0907d via fabric
	- fabric-item-api-v1 1.2.2+3cc0f0907d via fabric
	- fabric-item-groups-v0 0.3.1+3cc0f0907d via fabric
	- fabric-key-binding-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-keybindings-v0 0.2.2+3cc0f0907d via fabric
	- fabric-language-kotlin 1.7.0+kotlin.1.6.0
	- fabric-language-scala 1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d via fabric
	- fabric-loot-tables-v1 1.0.3+3cc0f0907d via fabric
	- fabric-mining-levels-v0 0.1.4+3cc0f0907d via fabric
	- fabric-models-v0 0.3.1+3cc0f0907d via fabric
	- fabric-networking-api-v1 1.0.5+3cc0f0907d via fabric
	- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d via fabric
	- fabric-networking-v0 0.3.3+3cc0f0907d via fabric
	- fabric-object-builder-api-v1 1.9.6+3cc0f0907d via fabric
	- fabric-object-builders-v0 0.7.3+3cc0f0907d via fabric
	- fabric-particles-v1 0.2.5+3cc0f0907d via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via fabric-tpa
	- fabric-registry-sync-v0 0.7.6+3cc0f0907d via fabric
	- fabric-renderer-api-v1 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-indigo 0.4.5+3cc0f0907d via fabric
	- fabric-renderer-registries-v1 2.3.1+3cc0f0907d via fabric
	- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d via fabric
	- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d via fabric
	- fabric-rendering-v0 1.1.3+3cc0f0907d via fabric
	- fabric-rendering-v1 1.6.1+3cc0f0907d via fabric
	- fabric-resource-loader-v0 0.4.8+3cc0f0907d via fabric
	- fabric-screen-api-v1 1.0.1+3cc0f0907d via fabric
	- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d via fabric
	- fabric-structure-api-v1 1.1.12+3cc0f0907d via fabric
	- fabric-tag-extensions-v0 1.1.2+3cc0f0907d via fabric
	- fabric-textures-v0 1.0.7+3cc0f0907d via fabric
	- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d via fabric
	- fabric-tpa 2.0.3
	- fabric-transfer-api-v1 1.5.0+3cc0f0907d via fabric
	- fabrichomes 1.0.0
	- fabricloader 0.13.3
	- fabricshieldlib 1.4.5+1.16
	- fabrictailor 1.5.0-1.16.5
	- fabricwarps 1.0.0
	- fallflyinglib 2.0.4 via winged
	- fallingleaves 1.6.0+1.16.5
	- fancymenu 2.6.3
	- farmersdelight 1.16.5-0.0.7
	- farsight 1.16.5-1.5.2
	- fasttransferlib 0.4.2 via appliedenergistics2
	- fatxporbs 0.0.9
	- fermion 2.1.191 via wrenchable
	- fermion-modkeys 1.10.218 via astromine-core
	- ferritecore 2.1.0
	- fiber 0.23.0-2 via collective-fabric
	- flamingo_ooo 1.0.4-MC1.16.3-fabric
	- flonters 1.1.1+1.16.2
	- flora-doubling 1.3.0+1.16.4-fabric
	- flycommand 1.16.5-1.4
	- flytre_lib 0.2.11
	- fpsreducer 1.24-mc1.16.5
	- frex 4.5.201 via json-model-extensions
	- ftbchunks 1605.3.2-build.115
	- ftblibrary 1605.3.4-build.90
	- ftbquests 1605.3.6-build.76
	- ftbteams 1605.2.3-build.40
	- gateofbabylon 1.4.4-1.16.5
	- gbfabrictools 1.3.2+1.16.4 via beenfo
	- geckolib3 3.0.68
	- givemehats 1.5.1
	- glassential 1.16.4-1.1.5
	- go-fish 1.2.3-beta-1.16.5
	- gobber2 2.3.79
	- goblintraders 1.4.1
	- goldenhoppers 1.0.2
	- goml 1.3.4-beta
	- graveyard 1.1
	- greater_eye 1.1.5
	- grindenchantments 1.1.3+1.16.3
	- guardiansgalore 1.16.5-3.0
	- haema 1.7.2+1.16
	- harvest 1.2.12
	- harvest_scythes 2.0.4
	- healingcampfire-fabric 3.3
	- healthoverlay 4.0.1
	- ignis-fatuus 1.1.3
	- iknowwhatimdoing 4.0.0
	- illuminations 1.5.1
	- improved-stations 2.0.3
	- indium 1.0.0+mc1.16.5
	- indrev 1.9.18-BETA
	- inmis 2.2.1-1.16.5
	- inventoryhud 3.4.1
	- inventorysorter 1.7.9-1.16
	- iris 1.2.0-pre
	- iron-jetpacks 0.3.1
	- itemfilters 1605.2.5-build.9
	- jankson 3.0.1+j1.2.0 via adorn
	- java 8
	- json-model-extensions 1.19.172 via ignis-fatuus
	- jumpoverfences 1.16-0.0.3
	- kanos_config 0.2.0+1.14.4-1.19 via pehkui
	- kibe 1.7-BETA
	- konkrete 1.3.3
	- krypton 0.1.2
	- ktdatataglib 1.4.0 via dml-refabricated
	- kubejs 1605.3.19-build.299
	- kyrptconfig 1.1.6-1.16 via inventorysorter
	- lakeside 1.0.3+1.16.4
	- lambdynlights 1.3.4+1.16
	- lapisreserve 1.0.7
	- lazydfu 0.1.2
	- libblockattributes 0.8.8 via modern_industrialization
	- libblockattributes_core 0.8.8 via extragenerators
	- libblockattributes_fluids 0.8.8 via extragenerators
	- libblockattributes_items 0.8.8 via extragenerators
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 3.4.0+1.16.5 via dark-enchanting
	- libraryferret 1.0.3
	- libstructure 1.5 via battletowers
	- lifts 1.1.1-BETA
	- lightoverlay 5.8.1
	- lightstones 1.3.0
	- lithium 0.6.6
	- magna 1.5.3-1.16.5 via vanilla-hammers
	- maybe-data 1.0.0-1.16.2 via vanilla-hammers
	- mcdict 2.0.1+1.16.4 via crookedcrooks
	- megane 4.1.4
	- megane-applied-energistics-2 4.1.4+8.3.0-alpha.1 via megane
	- megane-astromine 4.1.4+1.11.4-fabric-1.16.3 via megane
	- megane-base 4.1.4 via megane
	- megane-fabric-furnaces 4.1.4+1.3.3-1.16.4 via megane
	- megane-fast-transfer-lib 4.1.4+0.3.1 via megane
	- megane-industrial-revolution 4.1.4+1.8.13-BETA via megane
	- megane-kibe 4.1.4+1.6.6-BETA via megane
	- megane-lib-block-attributes 4.1.4+0.8.7 via megane
	- megane-modern-industrialization-4 4.1.4+0.4.0-alpha.11 via megane
	- megane-runtime 4.1.4 via megane
	- megane-team-reborn-energy 4.1.4+0.1.0 via megane
	- megane-tech-reborn 4.1.4+3.8.2-build.220 via megane
	- megane-vanilla 4.1.4+1.16.5 via megane
	- minecraft 1.16.5
	- minershorizon 1.6.2-1.16.5
	- mm 2.1 via slight-gui-modifications
	- mo_glass 1.5-MC1.16.5
	- mocolors 1.1.2
	- modern_industrialization 0.4.0-alpha.11
	- modmenu 1.16.22
	- morechathistory 1.1.0
	- morerespawnanchors 1.0
	- morevillagers-fabric 1.4.1-SNAPSHOT
	- mostructures 1.2.0-1.16.5
	- mousetweaks 2.22
	- mousewheelie 1.8.3+mc1.16.5
	- multi_item_lib 1.3.0 via netherite_plus
	- mysticalagriculture 1.1.7
	- mythic-mounts 1.16.5-5.0
	- naturallychargedcreepers-fabric 1.7
	- netherite_plus 1.4.5-1.16.5
	- ninjaphenix_container_lib 1.2.10
	- no-potion-offset ${version}
	- noanglebrackets 1.0.1
	- nocreeperholes 1.2.0
	- noenchantcap 4.1.0
	- nohostilesaroundcampfire-fabric 3.8
	- norecipebook 2.2+1.16.5
	- notenoughanimations 1.2.4
	- notenoughcrashes 4.1.4+1.16.5
	- okzoomer 4.0.1+1.16.2
	- omega-config 1.0.4 via dark-enchanting
	- openloader 1.0.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_codehaus_groovy_groovy 3.0.3 via slight-gui-modifications
	- org_codehaus_groovy_groovy-jsr223 3.0.3 via slight-gui-modifications
	- org_jetbrains_kotlin_kotlin-reflect 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.0 via astromine-core
	- org_objenesis_objenesis 3.2 via plantinajar
	- org_slf4j_slf4j-api 1.7.12 via iris
	- origins 0.7.3
	- origins-classes 1.1.1
	- oro_config 3.0.0 via netherite_plus
	- owo 0.1 via conjuring
	- patchouli 1.16.4-53-FABRIC
	- pehkui 3.2.2+1.14.4-1.19
	- phosphor 0.8.0
	- piglib 1.0.1 via astromine-core
	- plantinajar 2.1.2
	- playerabilitylib 1.2.2 via kibe
	- pling 1.3.0
	- prefab 1.0.6
	- pugh_lib 1.1.0 via gobber2
	- quarrymod 0.5.4
	- quartzelv 1.3.0+1.16
	- questsadditions 1.1.2
	- rad 1.0.1
	- randomtp 4.2.1+1.16
	- rare-ice 0.2.2
	- ratsmischief 1.1.2
	- reach-entity-attributes 1.1.1 via gateofbabylon
	- reborncore 4.7.3+build.136
	- redbits 1.8.0
	- repurposed_structures 1.16.5-1.11.6-fabric
	- reroll 1.2.1-1.16.5
	- respawnablepets 1.16.5-2
	- rhino 1605.1.5-build.75
	- ringsofascension 1.1.1
	- roughlyenoughitems 5.12.248
	- roughlyenoughitems-api 5.12.248 via roughlyenoughitems
	- roughlyenoughitems-default-plugin 5.12.248 via roughlyenoughitems
	- roughlyenoughitems-runtime 5.12.248 via roughlyenoughitems
	- rtree-3i-lite-fabric 0.3.0 via goml
	- sakurarosea 1.6.0-MC1.16.3-fabric
	- sandwichable 1.2-rc4+1.16
	- satin 1.5.1 via haema
	- seasons 1.2.0.1-BETA+1.16
	- secretrooms 0.9.5+1.16.5
	- shulkerboxtooltip 2.3.8+1.16.5
	- shulkerutils 1.0.1-1.16 via upgradedshulkers
	- simple_backpack 1.0.38
	- sit 1.16.5-11
	- skeletonfix 1.1.0+1.16
	- skeletonhorsespawn-fabric 1.9
	- skinlayers 1.1.0
	- slight-gui-modifications 1.7.1
	- slotlink 2.4.3+1.16.5
	- slotlock 1.0.3-BETA
	- smoothboot 1.16.5-1.6.0
	- smootherbedrock 1.0.4
	- smoothscrollingeverywhere 3.0.3-unstable
	- snowpig 1.0.0
	- sodium 0.2.0+build.4
	- sodium-extra 0.3.9
	- someforgepatchesported 1.0.0
	- somnus 0.0.12-1.16.5 via comforts
	- spark 1.6.0
	- spruceui 2.1.4+1.16 via sandwichable
	- staffofbuilding 1.2.6-1.16.5
	- static-content 1.0.2-1.16.2 via battletowers
	- staticdata 1.1.2 via static-content
	- step-height-entity-attribute 1.0.0 via artifacts
	- stoneholm 1.2.1
	- structure-helpers 3.0.0 via battletowers
	- structurized 1.2.0-1.16.5 via tacocraft
	- tacocraft 1.5.2+mc.1.16.5
	- team_reborn_energy 0.1.1 via extragenerators
	- techreborn 3.8.4+build.236
	- terraform-biome-builder-api-v1 1.0.4 via terrestria
	- terraform-config-api-v1 1.0.3 via terrestria
	- terraform-dirt-api-v1 1.1.3 via terrestria
	- terraform-overworld-biome-extensions-api-v1 1.0.3 via terrestria
	- terraform-shapes-api-v1 1.0.3 via terrestria
	- terraform-surfaces-api-v1 1.0.3 via terrestria
	- terraform-tree-api-v1 1.0.4 via terrestria
	- terraform-wood-api-v1 1.0.3 via terrestria
	- terrarianslimes 1.1-BETA+1.16
	- terrestria 2.2.0
	- thonkutil 1.3 via goblintraders
	- tis3d MC1.16.5-Fabric-1.6.2.35
	- tk_valoeghese_zoesteriaconfig 1.3.6 via byg
	- toolstats 1.0.1
	- tooltipfix 1.0.2-1.16
	- torcherino 14.0.1
	- totemmod 0.3.2
	- trampledisablerfabric 1.0.1
	- transliterationlib 1.0.4
	- trapexpansion 1.3.2
	- traverse 3.3.3
	- trinkets 2.6.7
	- truerooms 1.1.3
	- tweed4_annotated 1.2.0 via mousewheelie
	- tweed4_base 1.3.1 via mousewheelie
	- tweed4_data 1.2.0 via mousewheelie
	- tweed4_data_hjson 1.1.0 via mousewheelie
	- tweed4_tailor_coat 1.0.1 via mousewheelie
	- tweed4_tailor_screen 1.0.1 via mousewheelie
	- untitledduckmod 0.2.2
	- upgradedshulkers 1.0.1-1.16
	- urns 1.0.0
	- vanilla-hammers 3.0.3-1.16.5
	- vanilladeathchest 2.0.6-fabric
	- vanillaexcavators 1.1.0
	- villagernames 1.6.0
	- villagespawnpoint-fabric 1.8
	- voicechat 1.16.5-1.10.0
	- voidtotem 1.16.5-1.2.0
	- voidz 1.0.2
	- voyager 1.0.0 via repurposed_structures
	- waystones 2.0.1
	- windowedfullscreen 1.0.0
	- winged 1.16.5-2.1.4
	- wirelessnetworks 1.0.3
	- wither_proof_block 1.0.3
	- wolveswitharmor 1.5.4-1.16.5
	- woodenhoppers 1.0.0
	- woods_and_mires 1.0.4+1.16.3
	- worldedit 7.2.5+57d5ac9
	- wrenchable 1.0.0+1.16.1 via astromine-core
	- wthit 2.10.11
	- xlpackets 1.1
	- yungsapi 1.16.5-Fabric-9
	- zombiehorsespawn-fabric 3.0

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

No generated crash report so i will provide the log file instead
[latest.log](https://github.com/Virtuoel/Pehkui/files/8484734/latest.log)

**Comment by Virtuoel** [comment]
Is this an existing modpack, and if yes, could you also provide a link to it?

**Comment by Mazereck** [comment]
https://www.curseforge.com/minecraft/modpacks/all-of-nexus

**Comment by Mazereck** [comment]
Im currently removing large chunks of the mods at a time and testing for crashes to see if its a conflict issue

**Comment by Virtuoel** [comment]
Conflicts appear to be with NoCreeperHoles and ExtraAlchemy.
For NoCreeperHoles, they're redirecting an explosion method call to prevent Ghast fireball fire placement and block destruction instead of just modifying those fire and destruction arguments directly, which conflicts with Pehkui's changes to just the fireball explosion strength.
For ExtraAlchemy, the older 1.16.5 version is not compatible with newer Pehkui.
In both cases, seems to be on the other mods' ends.

**Comment by Mazereck** [comment]
That did the trick, i appreciate your time.

**Comment by TBSpirit** [comment]
Thanks for your help!
