### ISSUE TITLE
I HAVE ISSUE

### ISSUE THREAD

**Issue by THEBOSSGAMER123** [Virtuoel/Pehkui#266]
MY MINECRAFT IS CRASHING WHENEVER I AM  STARTING  IT
HERE THE ISSUE LOG
https://pastebin.com/Etq4d1Gc

**Comment by THEBOSSGAMER123** [comment]
can anyone help me?

**Comment by Virtuoel** [comment]
Your log is very incomplete, has no actual crash inside, and you haven't provided any info about Minecraft version, Forge/Fabric version, Pehkui version, etc. Please submit a new issue and make sure to use the Bug Report button to get a form that you can put the info in.
