### ISSUE TITLE
Minecraft Not Opening

### ISSUE THREAD

**Issue by Mooniee0** [Virtuoel/Pehkui#269]
### Minecraft version(s)

1.18.2

### Mod loader

Fabric

### Mod loader version

fabric  0.10.2

### Fabric API version

0.51.1

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Whenever I try to open Minecraft it starts with one crash, after that when I try to reopen nothing loads at all. like nothing shows. i tried removing the mod but then it kept asking for it. i tried it on 1.18.1 and it worked. just doesn't work for 1.18.2

### Full list of installed mods

3dskinlayers-fabric-1.4.3-mc1.18.2
extraorigins-1.18-10 (2)
fabric-api-0.51.1+1.18.2
optifabric-1.13.0
OptiFine_1.18.2_HD_U_H6
Pehkui-3.2.2+1.14.4-1.19 (3)
replaymod-1.18.2-2.6.4
voicechat-fabric-1.18.2-2.2.31
Xaeros_Minimap_22.4.0_Fabric_1.18.2

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

![unknown](https://user-images.githubusercontent.com/104559993/165717262-5adbe8a5-0830-4d3a-80be-440ca99a8429.png)
![unknown](https://user-images.githubusercontent.com/104559993/165717310-9a4341ab-16c3-4ccf-bc05-fb7a2c43cb05.png)

**Comment by Virtuoel** [comment]
You're launching with an older version of Fabric Loader (0.10.2) that can't run 1.18.2. You'll need to update Fabric Loader to 0.13.3 or newer by using the Fabric Installer.
