### ISSUE TITLE
Mod not installing properly?

### ISSUE THREAD

**Issue by Onemario1234** [Virtuoel/Pehkui#27]
I've got the latest version of Fabric, yet putting this mod in my mods folder doesn't register it. It doesn't think it's installed.

Fabric API, Immersive Portals, and ModMenu are the only other mods I've installed.

**Comment by Sarium** [comment]
how was this solved?

**Comment by Onemario1234** [comment]
Turns out it wasn't a problem to begin with. It was installed, but I had no visual indicator, so I assumed it thought it wasn't installed.
