### ISSUE TITLE
[Bug]: Performance Issues

### ISSUE THREAD

**Issue by Shaiookami** [Virtuoel/Pehkui#272]
### Minecraft version(s)

1.18.2

### Mod loader

Fabric

### Mod loader version

0.14.4

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

if I use the command "/scale set " and put 150 
cpu and gpu degrees rise to 80/85 degrees celsius
Won’t anything damage my computer if I accidentally put that size?

### Full list of installed mods

Mods:
  [✔️] 1.18.2-additionalbars-3.0.0
  [✔️] 3dskinlayers-fabric-1.4.3-mc1.18.2
  [✔️] AdditionalAdditions-3.0.1
  [✔️] AdditionalEnchantedMiner-1.18-fabric-18.4.0
  [✔️] AdditionalStructures-1.18.2-(v.3.0.3)
  [✔️] Adorn-3.4.0+1.18.2-fabric
  [✔️] advancednetherite-fabric-1.5.0-1.18.2
  [✔️] AdvancementPlaques-1.18-fabric-1.4.4
  [✔️] advancements-enlarger-0.2.4
  [✔️] advdebug-2.3.0
  [✔️] adventurez-1.4.10
  [✔️] arcanus-1.29
  [✔️] architects-palette-fabric-1.7
  [✔️] architectury-4.2.50
  [✔️] AttributeFix-Fabric-1.18.2-14.0.1
  [✔️] autoconfig1u-3.4.0
  [✔️] axolotl-item-fix-1.1.3
  [✔️] badpackets-fabric-0.1.1
  [✔️] balm-fabric-3.0.0+0
  [✔️] BasicShields-1.3.1-1.18.2
  [✔️] bclib-1.4.5
  [✔️] BetterAdvancements-1.18.1-0.1.2.122
  [✔️] betteranimalsplus-1.18.2-11.0.5-fabric
  [✔️] betterCompatibilityChecker-fabric-1.0.5
  [✔️] better-end-1.1.0
  [✔️] BetterF3-1.2.4-Fabric-1.18.2
  [✔️] better-nether-6.1.1
  [✔️] bettersleeping-0.5.1+1.18
  [✔️] BetterThirdPerson-Fabric-1.18.2-1.7.3
  [❌] biomeinfo-1.18.2-10.jar (disabled)
  [✔️] biomemakeover-FABRIC-1.18.2-1.4.18
  [✔️] blockus-2.4.5+1.18.2
  [✔️] blur-2.4.1
  [✔️] BOMD-1.3.6-1.18.2
  [✔️] Bookshelf-Fabric-1.18.2-13.0.13
  [✔️] cammies-minecart-tweaks-1.5
  [✔️] camsbackpacks-2.11
  [✔️] capybara-1.18-1.0.4
  [✔️] caracal-1.18.2-1.3.8
  [✔️] cardinal-components-api-4.1.4
  [✔️] charm-fabric-1.18-4.1.0
  [✔️] charmonium-fabric-1.18-4.0.0
  [✔️] chat_heads-0.6.0-fabric-1.18.1
  [✔️] cherishedworlds-fabric-2.0.1-1.18
  [✔️] chipped-1.2
  [✔️] chisel-1.4.5+1.18.x
  [✔️] clienttweaks-fabric-1.18.1-7.1.0
  [✔️] cloth-config-6.2.57-fabric
  [✔️] Clumps-fabric-1.18.2-8.0.0+8
  [✔️] collective-fabric-1.18.x-4.26
  [✔️] comforts-fabric-1.1.2-1.18.2
  [✔️] connectivity-fabric-1.18.2-2.9
  [✔️] continuity-1.1.0+1.18.2
  [✔️] Controlling-fabric-1.18.2-9.0+19
  [✔️] CraftTweaker-fabric-1.18.2-9.1.116
  [✔️] crawl-0.10.6
  [✔️] CreaturesFromTheSnow[1.18.2]+1.0.0
  [✔️] CreaturesFromTheWarmths[1.18.2]+1.0.0
  [✔️] creeperoverhaul-1.18.2-1.3.0-fabric
  [✔️] crockpot-0.8.4+1.18.2
  [✔️] Croptopia-1.18.2-FABRIC-2.0.0
  [✔️] cullleaves-2.3.2
  [✔️] DarkPaintings-Fabric-1.18.2-10.0.1
  [✔️] dashloader-def-3.1.1+1.18
  [✔️] dawn-3.3.0
  [✔️] Decorative Blocks-fabric-1.18.2-2.1.0
  [✔️] deepslatecutting-1.18.2-1.3.2
  [✔️] DeleteWorldsToTrash-v3.2.0-1.18.2-Fabric
  [✔️] dragonloot-1.0.10
  [✔️] dualwielding-1.0.8
  [✔️] duckling-1.0.3-fabric
  [✔️] dustrial-decor-fabric-0.5
  [✔️] dynamic-fps-2.1.0
  [✔️] DynamicSoundFilters-1.3.0+1.18.2
  [✔️] Earth2Java-1.8.0+1.18.2
  [✔️] EasyMagic-v3.3.0-1.18.2-Fabric
  [✔️] EasyShulkerBoxes-v3.1.1-1.18.2-Fabric
  [✔️] eating-animation-1.6
  [✔️] ecologics-FABRIC-1.18.2-1.5.4
  [✔️] eden-ring-0.5.1
  [✔️] effective-1.2.1
  [✔️] elytratrinket-fabric-3.0.0-1.18.1
  [✔️] emotecraft-for-MC1.18.2-2.1.2-fabric
  [✔️] EnchantmentDescriptions-Fabric-1.18.2-10.0.2
  [✔️] enchantment-lore-1.2.6-1+MC1.18-1.18.2
  [✔️] end-goblin-traders-1.5
  [✔️] enhanced_attack_indicator-1.0.3+1.18
  [✔️] enhancedcelestials-2.0.9-1.18
  [✔️] entityculling-fabric-mc1.18-1.5.1
  [✔️] EquipmentCompare-1.18.2-fabric-1.2.12
  [✔️] extended-armor-bars-1.2.1
  [✔️] fabric-api-0.51.1+1.18.2
  [✔️] fabric-experiencebugfix-1.18-18
  [✔️] fabric-language-kotlin-1.7.4+kotlin.1.6.21
  [✔️] FabricShieldLib-1.5.3-1.18
  [✔️] fallingleaves-1.10.0+1.18.2
  [✔️] FallingTree-1.18.2-3.5.0
  [✔️] farmers-delight-fabric-0.2.1
  [✔️] FauxCustomEntityData-fabric-1.18.2-2.0.1
  [✔️] feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1
  [✔️] ferritecore-4.2.1-fabric
  [✔️] ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric
  [✔️] forgottenrecipes-fabric-1.18.1-1.0.0
  [✔️] friendsandfoes-fabric-mc1.18.2-1.3.4
  [✔️] ftb-chunks-fabric-1802.3.5-build.130
  [✔️] ftb-library-fabric-1802.3.6-build.115
  [✔️] ftb-teams-fabric-1802.2.6-build.51
  [✔️] gate-of-babylon-1.7.0-1.18.2
  [✔️] geckolib-fabric-1.18-3.0.38
  [✔️] goblin-traders-1.5.1
  [✔️] go-fish-1.5.0-1.18.2
  [✔️] grizzlybear-1.18-1.3
  [✔️] guard-villagers-fabric-1.18.2-1.0.11
  [✔️] Highlighter-1.18-fabric-1.1.2
  [✔️] Iceberg-1.18.2-fabric-1.0.38
  [✔️] illager_expansion-0.1.5
  [❌] illuminations-1.10.2.jar (disabled)
  [✔️] immersive_weathering-2.4.0
  [✔️] impaled-1.1.1
  [✔️] indium-1.0.3+mc1.18.2
  [✔️] infusion-table-mod-1.0.5
  [✔️] IngredientExtensionAPI-fabric-1.18.2-2.0.5
  [✔️] inmis-2.5.3-1.18.2
  [✔️] interactic-0.1.10+1.18
  [✔️] iris-mc1.18.2-1.2.4-build.38
  [✔️] item-filters-fabric-1802.2.7-build.21
  [✔️] kleeslabs-fabric-1.18-11.0.0
  [✔️] konkrete_fabric_1.3.3-1_MC_1.18-1.18.2
  [✔️] krypton-0.1.9
  [✔️] lambdynamiclights-2.1.0+1.17
  [✔️] lazydfu-0.1.2
  [✔️] lithium-fabric-mc1.18.2-0.7.9
  [✔️] logprot-fabric-1.18-1.6
  [✔️] lovely_snails-1.0.4+1.18
  [✔️] magehand-1.1.0
  [✔️] MagnumTorch-v3.1.2-1.18.2-Fabric
  [✔️] mavm-fabric-1.18.1-1.0.7a
  [✔️] mcw-doors-1.0.6fabric-mc1.18.2
  [✔️] mcw-fences-1.0.4fabric-mc1.18.2
  [✔️] mcw-lights-1.0.3c+fabric-mc1.18.2
  [✔️] mcw-roofs-2.1.2fabric-mc1.18.2
  [✔️] mcw-trapdoors-1.0.5fabric-mc1.18.2
  [✔️] mcw-windows-2.0.3bfabric-mc1.18.2
  [✔️] megane-7.5.1
  [✔️] midnightlib-0.4.0
  [✔️] MmmMmmMmmMmm-1.18-1.5.1
  [✔️] Modern-Industrialization-1.1.1
  [✔️] modmenu-3.2.1
  [✔️] More Babies-fabric-1.18.1-0.5.1
  [✔️] MoreAchievements-1.18.1-1.0.8
  [✔️] more-axolotls-1.0.2-1.18
  [✔️] more-geodes-1.3.1
  [✔️] MoreTags-3.0.4
  [✔️] morevillagers-FABRIC-1.18.2-3.2.0
  [✔️] mostructures-1.4.1+1.18.2
  [✔️] MouseTweaks-fabric-mc1.18-2.22
  [✔️] namepain-1.4.0+fabric-1.17.x
  [✔️] NaturesCompass-1.18.2-2.0.3-fabric
  [✔️] nears-fabric-1.18-1.1.8
  [✔️] netherportalfix-fabric-1.18-9.0.0
  [✔️] notenoughanimations-fabric-1.6.0-mc1.18.2
  [✔️] OfflineSkins-1.18.2-v2
  [✔️] Oh_The_Biomes_You'll_Go-fabric-1.18.2-1.4-RC-10
  [✔️] onsoulfire-1.18-1
  [✔️] overweightfarming-1.18.2-1.2.0-fabric
  [✔️] oxidized-1.6.3
  [✔️] Paintings-fabric-1.18.2-9.1.1.0
  [✔️] paradise-lost-1.6.8+1.18.2
  [✔️] particle-rain-2.0.0
  [✔️] Patchouli-1.18.2-67-FABRIC
  [✔️] Paxi-1.18.2-Fabric-2.0
  [✔️] Pehkui-3.3.0+1.14.4-1.19
  [✔️] phosphor-fabric-mc1.18.x-0.8.1
  [✔️] PickUpNotifier-v3.2.0-1.18.2-Fabric
  [✔️] pigsteel-fabric-1.18.2-1.7.1
  [✔️] Ping-1.18-1.8.0
  [✔️] plushie-mod-1.2-1.18.2
  [✔️] polymorph-fabric-0.0.20-1.18.2
  [✔️] post-materia-1.0.0-1.18.2
  [✔️] PresenceFootsteps-1.5.0
  [✔️] probablychests-0.3.2
  [✔️] puzzle-1.2.1
  [✔️] PuzzlesLib-v3.3.1-1.18.2-Fabric
  [✔️] quartz-elevator-2.1.1+1.18
  [✔️] repurposed_structures_fabric-4.1.6+1.18.2
  [✔️] rer-2.5.0
  [✔️] rightclickharvest-2.0.0
  [✔️] RoughlyEnoughItems-8.1.457
  [✔️] RoughlyEnoughProfessions-fabric-1.18.2-1.0.1
  [✔️] Runelic-Fabric-1.18.2-11.0.1
  [✔️] SimpleRPC-fabric-1.18.2-3.0.0
  [✔️] sit-1.18.2-18
  [❌] skinnedlanterns-1.2.0+build.12.jar (disabled)
  [✔️] skylorlib-1.3.34
  [✔️] smoothboot-fabric-1.18.2-1.7.0
  [✔️] sodium-fabric-mc1.18.2-0.4.1+build.15
  [✔️] spark-1.9.1-fabric
  [✔️] Spirit-fabric-1.18.2-1.2.3
  [✔️] sprout-1.2.0-fabric
  [✔️] stoneholm-1.4.3
  [✔️] styled-chat-1.2.3+1.18
  [✔️] styled-nicknames-1.0.4+1.18
  [✔️] styledplayerlist-2.1.3+1.18
  [✔️] Tempad-fabric-1.18.2-1.1.0
  [✔️] TerraBlender-fabric-1.18.2-1.1.0.99
  [✔️] Terralith_v2.2.1a
  [✔️] the_bumblezone_fabric-5.0.10+1.18.2
  [✔️] The_Graveyard_1.7_(FABRIC)_for_1.18.2 (1)
  [✔️] thonkutil-2.12.0+1.18
  [✔️] toms_storage_fabric-1.18.2-1.3.0
  [✔️] totw_additions-1.2.1-1.18.2-fabric-polymer
  [✔️] TradingPost-v3.2.0-1.18.2-Fabric
  [✔️] transportables-1.1
  [✔️] TravelersTitles-1.18.2-Fabric-2.1.1
  [✔️] trinketofundying-fabric-2.0.1-1.18
  [✔️] trinkets-3.3.0
  [✔️] twigs-fabric-1.1.3-patch1+1.18.2
  [✔️] UniversalBoneMeal-v3.0.4-1.18.2-Fabric
  [✔️] vanilla_degus-1.18.2-v1.3.0-fabric
  [✔️] veinmining-fabric-0.0.12-1.18.2
  [✔️] villager-hats-mod-1.3.1
  [✔️] villagernames-1.18.2-4.0.4
  [✔️] visuality-0.4.2
  [✔️] VisualWorkbench-v3.3.0-1.18.2-Fabric
  [✔️] voidtotem-fabric-1.18.2-1.3.1
  [✔️] voidz-1.0.7
  [✔️] wanderingcollector-1.1.2+mc1.18.2
  [✔️] windchimes-1.2.0
  [✔️] wraith-waystones-2.5.0
  [✔️] wthit-fabric-4.9.1
  [✔️] youre-in-grave-danger-1.3.1
  [✔️] YungsApi-1.18.2-Fabric-2.0.7
  [✔️] YungsApi-1.18.2-Fabric-2.0.8
  [✔️] YungsBetterDungeons-1.18.2-Fabric-2.1.0
  [✔️] YungsBetterMineshafts-1.18.2-Fabric-2.1.1
  [✔️] YungsBetterStrongholds-1.18.2-Fabric-2.1.1
  [✔️] YungsBridges-1.18.2-Fabric-2.1.0
  [✔️] YungsExtras-1.18.2-Fabric-2.1.0
  [✔️] zihlaunchpads-1.2.0

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
A scale of 150 is somewhat excessive. That'd be pretty close to the height of the entire world. I'd be surprised if any computer didn't struggle with an entity as wide as multiple chunks.

Not really something that can be "fixed", but if you want a visually large entity, there's the `model_width` and `model_height` scale types you can use while keeping the `hitbox_width` and `hitbox_height` scales at lower values that don't collide with a significant amount of the terrain.
For server admins, they can configure limits for the max value a scale can be in the config.

If you run into other performance issues, there is now one big issue for all performance reports: https://github.com/Virtuoel/Pehkui/issues/375
