### ISSUE TITLE
[Bug] Error code 1 when using Pehkui with Mantle/Tinker's Construct

### ISSUE THREAD

**Issue by RedstoneFox** [Virtuoel/Pehkui#274]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

Forge 40.1.19

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

I added Mantle/Tinker's Construct to a modpack that had Pekhui and it kept throwing out Unexpected Fatal Error codes.

### Full list of installed mods

![List Part 1](https://user-images.githubusercontent.com/14907966/167523858-53da951a-de50-4090-9c57-d2dabc81764a.png)
![List Part 2](https://user-images.githubusercontent.com/14907966/167523874-63741486-e7ff-4b05-9899-25630cae13fa.png)
![List Part 3](https://user-images.githubusercontent.com/14907966/167523885-74a0b694-094e-4b68-b95c-38fa15b8cc22.png)
![List Part 4](https://user-images.githubusercontent.com/14907966/167523893-6a34a63e-1135-4650-9643-1cfa0f2e4014.png)
![List Part 5](https://user-images.githubusercontent.com/14907966/167523903-054041b3-0405-4f59-ae14-dc3e9ee13132.png)
![List Part 6](https://user-images.githubusercontent.com/14907966/167523909-fbbb990a-e37b-49cb-ae5b-494988dde896.png)
![List Part 7](https://user-images.githubusercontent.com/14907966/167523920-ff1706a2-c75c-45c8-ad9b-3ec91ba898e0.png)
![List Part 8](https://user-images.githubusercontent.com/14907966/167523926-90ab0ffc-0e3a-4328-8b87-b117c39979c1.png)
![List Part 9](https://user-images.githubusercontent.com/14907966/167523932-7aecde48-8c87-4e94-9d0d-ed431083c56d.png)
![List Part 10](https://user-images.githubusercontent.com/14907966/167523942-704a912f-3342-4e6e-b5da-845d324c0723.png)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
[Launcher console Error thingy.txt](https://github.com/Virtuoel/Pehkui/files/8656352/Launcher.console.Error.thingy.txt)

**Comment by Virtuoel** [comment]
Should now be resolved in Pehkui 3.3.1.
