### ISSUE TITLE
[Bug]: Crashes on start

### ISSUE THREAD

**Issue by Zadkielh** [Virtuoel/Pehkui#275]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

Forge 40.1.16

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Launched game and it crashed before ever opening the loading screen.

### Full list of installed mods

Pehkui 3.3.0

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output (Launcher Log seeing as game never launches properly and debug log doesn't give any info on crash):</summary>
<p>

[Info: 2022-05-11 13:06:24.8189253: NetQueue.cpp(632)] NetQueue: Starting net action https://api.minecraftservices.com/events
[Info: 2022-05-11 13:06:24.9490162: NetQueue.cpp(472)] NetQueue: Primary ip: 143.204.51.61, Host: api.minecraftservices.com
[Info: 2022-05-11 13:06:24.9490900: NetQueue.cpp(551)] NetQueue: Action finished: https://api.minecraftservices.com/events
[Info: 2022-05-11 13:06:24.9491706: NetQueue.cpp(579)] NetQueue: Action finalized: https://api.minecraftservices.com/events
[Info: 2022-05-11 13:06:26.7913409: GameCallbacks.cpp(177)] Game/game () Info Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[Info: 2022-05-11 13:06:26.7914184: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[Info: 2022-05-11 13:06:26.7914568: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[Info: 2022-05-11 13:06:26.7914811: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[Info: 2022-05-11 13:06:26.7915030: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
[Info: 2022-05-11 13:06:26.7915347: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
[Info: 2022-05-11 13:06:26.7915639: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[Info: 2022-05-11 13:06:26.7915852: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[Info: 2022-05-11 13:06:26.7916073: GameCallbacks.cpp(177)] Game/game () Info at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
[Info: 2022-05-11 13:06:26.7916343: GameCallbacks.cpp(177)] Game/game () Info Caused by: java.lang.reflect.InvocationTargetException
[Info: 2022-05-11 13:06:26.7916553: GameCallbacks.cpp(177)] Game/game () Info at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Info: 2022-05-11 13:06:26.7916753: GameCallbacks.cpp(177)] Game/game () Info at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[Info: 2022-05-11 13:06:26.7916960: GameCallbacks.cpp(177)] Game/game () Info at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Info: 2022-05-11 13:06:26.7917156: GameCallbacks.cpp(177)] Game/game () Info at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[Info: 2022-05-11 13:06:26.7917357: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.19/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
[Info: 2022-05-11 13:06:26.7917769: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[Info: 2022-05-11 13:06:26.7917985: GameCallbacks.cpp(177)] Game/game () Info ... 7 more
[Info: 2022-05-11 13:06:26.7918191: GameCallbacks.cpp(177)] Game/game () Info Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[Info: 2022-05-11 13:06:26.7918408: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.19/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
[Info: 2022-05-11 13:06:26.7918609: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:138)
[Info: 2022-05-11 13:06:26.7918850: GameCallbacks.cpp(177)] Game/game () Info ... 13 more
[Info: 2022-05-11 13:06:26.7919091: GameCallbacks.cpp(177)] Game/game () Info Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[Info: 2022-05-11 13:06:26.7919462: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[Info: 2022-05-11 13:06:26.7919862: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[Info: 2022-05-11 13:06:26.7920087: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[Info: 2022-05-11 13:06:26.7920297: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[Info: 2022-05-11 13:06:26.7920590: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
[Info: 2022-05-11 13:06:26.7920853: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
[Info: 2022-05-11 13:06:26.7921084: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[Info: 2022-05-11 13:06:26.7921456: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
[Info: 2022-05-11 13:06:26.7921770: GameCallbacks.cpp(177)] Game/game () Info at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
[Info: 2022-05-11 13:06:26.7921992: GameCallbacks.cpp(177)] Game/game () Info at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
[Info: 2022-05-11 13:06:26.7922195: GameCallbacks.cpp(177)] Game/game () Info at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
[Info: 2022-05-11 13:06:26.7922399: GameCallbacks.cpp(177)] Game/game () Info at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
[Info: 2022-05-11 13:06:26.7922604: GameCallbacks.cpp(177)] Game/game () Info at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
[Info: 2022-05-11 13:06:26.7922812: GameCallbacks.cpp(177)] Game/game () Info at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[Info: 2022-05-11 13:06:26.7923022: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/forge@40.1.19/net.minecraftforge.registries.GameData.init(GameData.java:123)
[Info: 2022-05-11 13:06:26.7923285: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/forge@40.1.19/net.minecraftforge.registries.GameData.<clinit>(GameData.java:108)
[Info: 2022-05-11 13:06:26.7923498: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.forge(Registry.java:407)
[Info: 2022-05-11 13:06:26.7923700: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.forge(Registry.java:391)
[Info: 2022-05-11 13:06:26.7923905: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:170)
[Info: 2022-05-11 13:06:26.7924112: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
[Info: 2022-05-11 13:06:26.7924386: GameCallbacks.cpp(177)] Game/game () Info at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:138)
[Info: 2022-05-11 13:06:26.7924606: GameCallbacks.cpp(177)] Game/game () Info at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[Info: 2022-05-11 13:06:26.7924813: GameCallbacks.cpp(177)] Game/game () Info at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Info: 2022-05-11 13:06:26.7925030: GameCallbacks.cpp(177)] Game/game () Info at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[Info: 2022-05-11 13:06:26.7925232: GameCallbacks.cpp(177)] Game/game () Info at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[Info: 2022-05-11 13:06:26.7925434: GameCallbacks.cpp(177)] Game/game () Info at java.base/java.lang.Thread.run(Thread.java:833)
[Info: 2022-05-11 13:06:26.7925688: GameCallbacks.cpp(177)] Game/game () Info Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector adjustMovementForCollisionsStepHeightProxy(Lnet/minecraft/world/entity/Entity;)F in pehkui.mixins.json:step_height.EntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Pehkui-refmap.json
[Info: 2022-05-11 13:06:26.7925981: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[Info: 2022-05-11 13:06:26.7926391: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[Info: 2022-05-11 13:06:26.7926620: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[Info: 2022-05-11 13:06:26.7926830: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[Info: 2022-05-11 13:06:26.7927109: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[Info: 2022-05-11 13:06:26.7927326: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[Info: 2022-05-11 13:06:26.7927528: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[Info: 2022-05-11 13:06:26.7927727: GameCallbacks.cpp(177)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[Info: 2022-05-11 13:06:26.7928007: GameCallbacks.cpp(177)] Game/game () Info ... 25 more
[Info: 2022-05-11 13:06:27.3443494: GameCallbacks.cpp(177)] Launcher/monitor (Process Monitor) Fatal Process crashed with exit code 1

**Comment by Jollyolsport** [comment]
getting the same problem

**Comment by otowm** [comment]
works in forge 40.1.2

**Comment by RedstoneFox** [comment]
From what I've found... It's an issue with Forge. A new step thingy was added in 40.1.3, breaking Pehqui, undone in 40.1.15, and redone in 40.1.16 onwards.

**Comment by Attyelep** [comment]
> From what I've found... It's an issue with Forge. A new step thingy was added in 40.1.3, breaking Pehqui, undone in 40.1.15, and redone in 40.1.16 onwards.

Switching to 40.1.2 Seems to fix it, Don't Know About 40.1.15

**Comment by mcwoodcraft** [comment]
40.1.15 works

**Comment by copygirl** [comment]
I would have to remove Tinkers' Construct for the time being because it depends on Forge 40.1.19, and no other 1.18.2 version exists. Also another mod needed to be downgraded. You can check this by setting the Forge version to 40.1.15, starting up the game, and looking at which mods say they need newer Forge versions. I then went through the changelogs of the mods to see which version I needed to downgrade to. In my case, the other conflicting mod, Botania, needed to be downgraded just single version - 1.18.2-431 works.

I hope this will be addressed soon, not just for my sake, but everyone playing with these mods together.

**Comment by Virtuoel** [comment]
Should now be resolved in Pehkui 3.3.1.
