### ISSUE TITLE
[Bug]: Reach don't work in 1.18.2

### ISSUE THREAD

**Issue by freerig** [Virtuoel/Pehkui#284]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

40.1.19

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

The pehkui:reach setting does not work, even when changing the pehkui:base setting. On the other hand, we can change the reach with /attribute NameOfPlayer forge:reach base set Value

### Full list of installed mods

Architectury API
Backpacked
bad packets
better third person
blockUI
Botania
Camera mod
CC: TWeaked
Chisels & Bits
Cloth Config API
Configured
CraftTweaker
Create
Curios API (forge)
Flywheel
Grappling Hook Mod
JEITweaker
JourneyMap
JustEnough Items
Little Logistics
McJtyLib
Not Enough Animations
Not Enough Wands
OpenBlocks Elevator
Patchouli
Pehkui
Pretty Pipes
Reliquary Reincarnations
RFTools Base
SecretRoomsMod
Security Craft
Simple Magnets
Storage Drawers
Structurize
SuperMartijn642's Config Lib
SuperMartijn642's Core Lib
Uppers
WorldEdit
WTHIT Forge Edition

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Can you first make sure Pehkui is at version 3.3.2 or newer, and then try updating Forge to 40.1.31 or newer?

**Comment by freerig** [comment]
Ok, thank, that work on forge 40.1.45 !

**Comment by freerig** [comment]
And thank you for your quick reaction 👍 !!!
