### ISSUE TITLE
[Bug]: Height and Width doesnt saves after death

### ISSUE THREAD

**Issue by Thspooks** [Virtuoel/Pehkui#285]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

1.18.2-forge-40.1.25

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

After death size of an origin im using doesnt saves, it resets me to the base size.
If its not a bug then im sorry for that, but i wanted to report it in case if its a bug

### Full list of installed mods

https://pastebin.com/1cAdcQdb

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by JadeJuno** [comment]
Works as intended. The scale changes won't persist unless you make them persist via `/scale persist`.

**Comment by Thspooks** [comment]
Not really. I didnt had to use that command time ago, it was saving size by its own without need to use that command. But to be honest ive seen forge has some net issues so it could be it. Not sure.

**Comment by Virtuoel** [comment]
If a size change is provided by an origin, it's up to that origin's code to make sure that your size is set back to the correct value after you die. Report to whoever made the origin.
