### ISSUE TITLE
[Bug]: Bitdefender Antirvirus False-flags v3.2.0+ as trojan

### ISSUE THREAD

**Issue by Mazereck** [Virtuoel/Pehkui#289]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

Forge 40.1.48

### In what environment did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Cant install the mod from Curseforge without letting the file through. Most people can just give the file a pass as they know it from a trusted source but the Bitdefender on the PC in question isn't managed by the person using it to play MC so they don't have the login for it to allow it to pass. Just wondering if there was a particular reason why it does this and if it could be fixed and if not that's fine, I just wanted to bring attention to it as I haven't really seen anyone else have this issue across google searches and reddit/forum results.

### Full list of installed mods

No modlist required for issue as far as I know, but I can supply if so desired.

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Mazereck** [comment]
If it comes up as a question, Bitdefender flags it as "Java.Trojan.GenericGBA.31501".

**Comment by Virtuoel** [comment]
Should now be resolved in 3.3.3 releases.
