### ISSUE TITLE
where can i find download for 1.18.1 fabric

### ISSUE THREAD

**Issue by squendan998** [Virtuoel/Pehkui#296]

**Comment by squendan998** [comment]
why did you remove it bring it back please please please please right now you have too so do it now please you need to do it i am going to die if you dont do help me fix it bring it back please please please please please please

**Comment by Virtuoel** [comment]
1.18.1 is no longer supported for getting fixes as of Pehkui 3.3.3 and newer. Pehkui 3.3.2 is known to work with 1.18.1. The latest Pehkui version is not guaranteed to work on 1.18.1, but most likely it will still work.

It is however recommended to update to 1.18.2 instead of staying on 1.18.1.
