### ISSUE TITLE
[Bug]: Pehkui Fails When Opening Minecraft

### ISSUE THREAD

**Issue by SinzicMC** [Virtuoel/Pehkui#301]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.19

### Mod loader

Fabric

### Mod loader version

1.19

### Fabric API version

1.19

### In what environment did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I downloaded Pehkui for other mods that I was planning to use for my Apex Hosting server, but when I try to join the server it tells me that the registry remapping failed and that the command argument type contains IDs unknown to the receiver. I've had problems with this server recently, so I'm not quite sure it's the mod or the server itself. 
![Screenshot (17)](https://user-images.githubusercontent.com/109635681/179872095-a6016ec5-65cf-47d6-af66-e7202ef52d3b.png)

### Full list of installed mods

Origins-1.19-1.6.2.jar
fabric-api-0.57.0+1.19.jar
medieval-origins-1.19.x-4.1.2.jar
Pehkui-3.3.3+1.14.4-1.19.1.jar

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by NIGHT214** [comment]
how did u solve it?
And give me ur discord I'll add u and let's talk?

**Comment by Virtuoel** [comment]
You have a mismatched or outdated version of Pehkui installed on your client. Make sure the Pehkui version you have on your client matches the Pehkui version used by the server you're connecting to.
