### ISSUE TITLE
[Bug]: Received ID map for minecraft:command _argument_type contains IDs unknown to the recriver! those are -pehkui:scale_type, pehkui:scale_operation and pehkui:scale_modifier

### ISSUE THREAD

**Issue by NIGHT214** [Virtuoel/Pehkui#302]
### Minecraft version(s)

1.19.1

### Mod loader

Fabric

### Mod loader version

Fabric 1.19

### Fabric API version

1.19

### In what environment did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

Received ID map for minecraft:command _argument_type contains IDs unknown to the recriver! those are -pehkui:scale_type, pehkui:scale_operation and pehkui:scale_modifier

### Full list of installed mods

animal Origins
BCLIB
Better End
Easier VillagerTrading 
Origins

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
You have a mismatched or outdated version of Pehkui installed on your client. Make sure the Pehkui version you have on your client matches the Pehkui version used by the server you're connecting to.
