### ISSUE TITLE
[Bug]: Severe mod incompat with VeryManyPlayers

### ISSUE THREAD

**Issue by Tempest-5ky** [Virtuoel/Pehkui#305]
### Minecraft version(s)

1.18.2

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.14.8

### Fabric API version

0.58.0

### In what environment did the problem occur?

A multiplayer server that I was connected to

### What went wrong? (Crash logs don't go here)

As of its v0.2.0+beta.3.73 1.18.2 release, VMP (https://modrinth.com/mod/vmp-fabric) completely breaks Pehkui. Neither generate any log errors, but when loaded together, Pehkui cannot modify the scales of players (and presumably any entity, though i'll admit i didn't think to test that). 
The /scale command will execute, and using "/scale get" will indicate that the scale _has_ been modified, but it obviously hasn't, as the jump height, entity scale, reach, or **any other scale type** will not change. Downgrading VMP to v0.2.0+beta.3.69 or lower gets rid of the issue. 

This bug also affects any mod that relies on Pehkui for its entity scaling, such as Origins and CPM.

### Full list of installed mods

No other mods besides those detailed above

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Does this still occur when using VMP 0.2.0+beta.3.76+1.18.2? Seems they recently fixed an issue to do with syncing entity data.

**Comment by Tempest-5ky** [comment]
Yes, it still occurs! That was the version I was using when I first noticed the issue in question.

**Comment by Virtuoel** [comment]
I think I might have figured out a simple fix for this on my end, thanks for the report. If the issue still occurs with the next Pehkui release, let me know on this issue and I'll reopen it.

**Comment by Tempest-5ky** [comment]
Thank you! I'll keep an eye out for that!

**Comment by Virtuoel** [comment]
Worth testing this again now that Pehkui 3.4.0 is released. Let me know if it seems to be fixed or if it still occurs.

**Comment by Tempest-5ky** [comment]
hello! Apologies for the late response, i'll be testing this today

**Comment by Tempest-5ky** [comment]
This has fixed the issue, thank you!!
