### ISSUE TITLE
ClassCastException attempting to cast Boolean to Entity

### ISSUE THREAD

**Issue by LemmaEOF** [Virtuoel/Pehkui#31]
[log](https://paste.ee/p/IJZid)
happened while looking at a recipe in REI, not sure if there was something else that happened

mc 1.16.5, pehkui 1.7.0+20w51a

**Comment by LemmaEOF** [comment]
it looks to be happening to a villager...?

**Comment by Virtuoel** [comment]
This should be fixed in 1.7.1+21w03a. Does updating fix the issue?

**Comment by LemmaEOF** [comment]
I'll give it a look when I'm awake tomorrow.

**Comment by LemmaEOF** [comment]
aaa sorry I haven't gotten around to testing yet but I'm gonna assume it's fixed and reopen if not
