### ISSUE TITLE
[Bug]: The latest version of Pehkui makes width scale and eye height scale zero right after teleporting through an ImmPtl portal. `getScale` returns a nearly 0 when tickDelta is not 1

### ISSUE THREAD

**Issue by qouteall** [Virtuoel/Pehkui#313]
### Minecraft version(s)

Other (specify below)

### Minecraft version details

1.16.x, 1.17.x, 1.18.x, 1.19.x

### Mod loader

Fabric

### Mod loader version

not important

### Fabric API version

not important

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

The symptom is described here https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1159

ImmPtl does client teleportation before rendering one frame (**not during ticking**). In teleportation it will change the scale **on client side first** (changing it from the server side will be too late) and then change the scale on server side.

Immediately after changing the scale on client side, `ScaleUtils.getEyeHeightScale(entity, 0.5f)` will return a very small number, but `ScaleUtils.getEyeHeightScale(entity, 0.5f)` returns the correct number. This cause the projection matrix to have near plane as 0 and break the frustum culling code.

### Full list of installed mods

Pehkui and the latest version of ImmPtl

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by qouteall** [comment]
This should be fixed on pehkui side. I don't want to update immptl's 1.16, 1.17, 1.18 and 1.19 version just to workaround a Pehkui bug.
Pehkui 3.3.3 does not have this issue. To fix this issue you can simply revert to 3.3.3

**Comment by Virtuoel** [comment]
Thanks for the report. Strange that the scale is returning that small of a number. That really shouldn't happen. Sounds very much like the issue is on Pehkui's end.
