### ISSUE TITLE
[Bug]: Visual Render bugs

### ISSUE THREAD

**Issue by ChromexUnderscore** [Virtuoel/Pehkui#317]
### Minecraft version(s)

1.19

### Mod loader

Fabric

### Mod loader version

0.14.9

### Fabric API version

0.58.0+1.19

### In what environment did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

3rd Person view completely black, no view bobbing, post processing shaders appear as deep black. (aka super secret settings, usable with origins mod).

### Full list of installed mods

Fabric API
ModMenu
Origins Mod 1.6.2
Pehkui

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
I am unable to reproduce this. If this is still a problem in Pehkui 3.6.1, please create a new issue.
