### ISSUE TITLE
[Bug]: Can't launch minecraft

### ISSUE THREAD

**Issue by jcianca** [Virtuoel/Pehkui#318]
Does this mean it is no longer compatible with 1.19 and I need to upgrade to 1.19.2? 

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.8 with version 0.14.9 or later.
Unmet dependency listing:
	 - Mod 'Pehkui' (pehkui) 3.4.1+1.14.4-1.19.2 requires version 0.14.9 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.8!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Inve1951** [comment]
you just gotta update fabric

**Comment by Virtuoel** [comment]
As mentioned above, you need to update Fabric. Specifically Fabric Loader, which is done by rerunning the Fabric Installer.
