### ISSUE TITLE
[Bug]: Crash with ArcLight

### ISSUE THREAD

**Issue by Adrigamer2950** [Virtuoel/Pehkui#319]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

42.0.0

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

Running ArcLight with Pehkui crashes the server

### Full list of installed mods and their version numbers

CustomPlayerModels v0.4.8a
Simple Voice Chat v2.3.7

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
https://gist.github.com/Adrigamer2950/a7cf8497422bf1035f57606d9117b276

**Comment by GodMorduk** [comment]
Exactly same issue appears on 1.16.5, would be nice if both versions can be fixed. Log seems same, will post if nessesary.
