### ISSUE TITLE
[Bug]: Origins requires 3.2.0 or above

### ISSUE THREAD

**Issue by RodriGC2009** [Virtuoel/Pehkui#320]
### Minecraft version(s)

1.19.2

### Minecraft version details

1.19.2

### Mod loader

Forge

### Mod loader version

Forge: 1.19.2 - 43.1.2

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

I install this mod because I was going to play with the origins plus plus mod that require this, so I install the las version (Pehkui-3.4.1+1.14.4-1.19.2) but it stills shows me that I need to install the mod in the version 3.2.0 or above when I already have it installed in the last version.

### Full list of installed mods and their version numbers

-[1.19.2] SecurityCraft v1.9.3.1.jar
3.03 MB
-badpackets-forge-0.2.0.jar
27.03 kB
-caelus-forge-1.19.2-3.0.0.6.jar
36.38 kB
-CreativeCore_FORGE_v2.8.2_mc1.19.2.jar
903.14 kB
-emotecraft-for-MC1.19.2-2.2.2-forge.jar
794.49 kB
-jei-1.19.2-forge-11.2.0.256.jar
0.97 MB
-origins-forge-1.19.2-1.5.0.6-all.jar
1.67 MB
-origins-plus-plus-1.6.2.jar
0.95 MB
-PlayerRevive_FORGE_v2.0.9_mc1.19.2.jar
5.05 MB
-wthit-forge-5.11.3.jar
364.60 kB
-Pehkui-3.4.1+1.14.4-1.19.2

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
You've installed the Fabric version of Pehkui, but you're running Forge. It should work once you remove the Fabric version and install the Forge version instead.
