### ISSUE TITLE
[Bug]: Fabric server not allowing op players

### ISSUE THREAD

**Issue by Nazerillo** [Virtuoel/Pehkui#327]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.14.9

### Fabric API version

Fabric API 0.62.0

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I was configuring a fabric server and I was kicked after give myself op. If I try to reconnect to this server I get disconnected instantly. There's no error or disconnect message. And disabling/enabling all mods I knew it was Pehkui. Maybe it's a problem with last fabric-api, or it could be related with tha fact that I'm trying to run this mod in a velocity proxy.

### Full list of installed mods and their version numbers

architectury-6.2.46
create-1.19.2-0.5.0.f
emotecraft-for-MC1.19.2-2.2.5
fabric-api-0.62.0+1.19.2
FabricProxy-Lite-2.3.0
identity-2.6.0-1.19.1-fabric
LuckPerms-Fabric-5.4.49
Pehkui-3.4.2+1.14.4-1.19.2
worldedit-mod-7.2.12

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by learle868** [comment]
I also have the same problem. Did you find a solution? I wanted to run Origins with some addon and I need Pehkui. I will try to install some older versions and see if it will work. If I find a solution I will write it here. 
EDIT: I see that we both use velocity because you have the FabricProxy-Lite mod installed. I was running the modpack on Waterfall/Bungeecord and I could OP myself but as I switched to velocity I can't join anymore if I am operator. If I don't have op, it funktions like normal.

**Comment by learle868** [comment]
I made a workaround through just giving yourself * permissions in luckperms. Don't write it witch a . just add it without any other symbol.

**Comment by Virtuoel** [comment]
Closing as this is just LuckPerms permissions needing to be set up on the server.

**Comment by gadget78** [comment]
not sure if this is the same on 1.19.3, but in 1.19.2 is still there... 

but this most defo is still a issue ! 
as ANY OP person just gets kicked.. (even if they join and THEN get OPed, instant kick...

and luckperms CANNOT always gain you full control of some commands even with * 
as Fabric doesn't have "vanilla" permissions like that .. 
so all vanilla commands don't work.. for example /give

PLUS some mods dont have permission's set up... 
even the this mod doesnt, so you cannot use `/scale` command !
