### ISSUE TITLE
[Suggestion]: Pixelmon Compatibility

### ISSUE THREAD

**Issue by DvnPMay** [Virtuoel/Pehkui#328]
### What is your suggestion?

I thought it would be pretty funny to see and own giant pixelmon, and while you can increase the size of them by using model_width and model_height, as soon as the pixelmon in brought inside of your pokeball, its size is reset. I even tried to use the persist command, and unfortunately it does not work like it does for players. I have no idea if this would be even possible, but I thought I would suggest it if it were possible. Thanks for reading!

**Comment by Virtuoel** [comment]
If the scale is resetting when they come out of the ball, it sounds like Pixelmon resets an entity's NBT to some default values every time they come out or perhaps only keeps some of the NBT. Nothing I can really do on my end unfortunately.
