### ISSUE TITLE
[Bug]: Scale reset

### ISSUE THREAD

**Issue by Flauridias** [Virtuoel/Pehkui#338]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

42.1.1

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

Hello,
Every time I disconnect and reconnect to the server, my scale is back to human scale...I tried everything I found but nothing seems to work...
Maybe someone can help me with that?

### Full list of installed mods and their version numbers

Origins(forge) 1.5.0.6-all
Caelus API (forge) 3.0.0.6
Origins++ 1.7.2
Pehkui 3.6.0
Clumps 9.0.0+11

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
I was not able to reproduce this. If this still occurs, report to Origins++.
