### ISSUE TITLE
Game crashes when a mob breeds

### ISSUE THREAD

**Issue by JpegIsMe** [Virtuoel/Pehkui#34]
When a mob makes a child mob that has a growth value, the game/server crashes. 
The following file contains the crash report and stacktrace
[crash.txt](https://github.com/Virtuoel/Pehkui/files/6007055/crash.txt)

**Comment by jxalexan56** [comment]
I have the same issue on a multiplayer server with my friends, it basically means we either have to get rid of pehkui altogether or not breed animals.

**Comment by entschri** [comment]
its been fixed in the latest update check the fixes in the new version of pehkui or immersive portals i forgot which one
