### ISSUE TITLE
[Bug]: keepAllScalesOnRespawn

### ISSUE THREAD

**Issue by Aspurgus** [Virtuoel/Pehkui#341]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

40.1.80

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I set the common config option to keep all scales on respawn to true, and in both a multiplayer server that I ran and a single player flat world I tested it in, the scales would still reset. I did have the origins mod, but to test it in single player i removed all powers from my player

### Full list of installed mods and their version numbers

<html>
<body>

another_furniture-forge-1.2.2-1.18.2
antiqueatlas-7.0.3-forge-mc1.18.2
Apotheosis-1.18.2-5.7.6
appleskin-forge-mc1.18.2-2.4.1
architectury-4.10.86-forge
blueprint-1.18.2-5.5.0
Bookshelf-Forge-1.18.2-13.2.50
BrewinAndChewin-1.18.2-1.0.1
caelus-forge-1.18.1-3.0.0.2
Chunky-1.2.164
cloth-config-6.4.90-forge
Clumps-forge-1.18.2-8.0.0+15
cofh_core-1.18.2-9.0.0.24
create-1.18.2-0.5.0.e
CustomPlayerModels-1.18-0.5.1a
DynamicTrees-1.18.2-0.11.0-Beta3
DynamicTreesTerraForged-1.18.2-1.0.0
EnchantmentDescriptions-Forge-1.18.2-10.0.9
ensorcellation-1.18.2-3.0.0.10
etched-forge-2.2.0+1.18.2
fantasyfurniture-1.18.2-3.12.0
FarmersDelight-1.18.2-1.2.0
FarmersRespite-1.18.2-1.3.0
ferritecore-4.2.1-forge
flywheel-forge-1.18.2-0.6.5
guardvillagers-1.18.2.1.4.3
hourglass-1.18.2-1.2.1.0
illuminations-forge-1.18.2-1.10.2.19
jei-1.18.2-9.7.1.255
kubejs-create-forge-1802.2.2-build.28
kubejs-forge-1802.5.5-build.554
libraryferret-forge-1.18.2-3.0.0
locksmith-forge-1.0.3+1.18.2
mannequins-forge-2.1.0+1.18.1
MouseTweaks-forge-mc1.18-2.21
NethersDelight-1.18.2-2.2.0
nightlights_1.18.2_1.1
Origins-1.18.2-1.4.1.4-unified
origins-classes-forge-1.1.6
Patchouli-1.18.2-71.1
Pehkui-3.6.0+1.18.2-forge
Placebo-1.18.2-6.6.6
pollen-forge-1.5.0+1.18.2
rhino-forge-1802.2.1-build.255
selene-1.18.2-1.17.9.jar
Serene Seasons-1.18.2-7.0.0.13
supplementaries-1.18.2-1.5.13
TerraForged-1.18.2-0.3.1-alpha-2
[Universal]CTOV-v2-9-2
woodworks-1.18.2-1.1.0

</body>
</html>

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
This appears to be caused by CustomPlayerModels [setting scales when respawning](https://github.com/tom5454/CustomPlayerModels/blob/master/CustomPlayerModels/src/shared/java/com/tom/cpm/shared/network/NetHandler.java#L241-L249) without first checking e.g. if the scale is persistent. If this still happens with the latest vesion of CustomPlayerModels, create an issue on [their issue tracker](https://github.com/tom5454/CustomPlayerModels/issues) instead.
