### ISSUE TITLE
[Bug]: Unable to connect to server

### ISSUE THREAD

**Issue by KeeveeKoomoo** [Virtuoel/Pehkui#343]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

Fabric loader 0.14.9

### Fabric API version

Fabric 0.66.0

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I ran my server, attempted to join, and then I got this error:
![image](https://user-images.githubusercontent.com/87249339/201748801-7f764b3f-a690-4234-83db-83036b9f262d.png)

### Full list of installed mods and their version numbers

![image](https://user-images.githubusercontent.com/87249339/201748991-cec8dab1-98a7-4ae1-93d0-f7c2ecb8c278.png)

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by KeeveeKoomoo** [comment]
Just double checked to make sure the server and the client had EXACTLY the same files, by deleting the server mod list, and selecting all, and copying to the server. It still did not work.

**Comment by Virtuoel** [comment]
I am unable to reproduce this. If this is still a problem in Pehkui 3.6.1, please create a new issue.
