### ISSUE TITLE
[Bug]: server crash on entering a server 

### ISSUE THREAD

**Issue by kuba26038** [Virtuoel/Pehkui#344]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

1.19.2-43.1.57

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

a player has done something in his base that causes a crash whenever he enters said area, be that by in-game travel or by joining the game in the place

### Full list of installed mods and their version numbers

modlist should be in the crashlog

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

https://pastebin.com/gzufthv8

**Comment by Virtuoel** [comment]
Seems like some entity has an excessively large scale that's lagging the server.

One course of action would be to set `max-tick-time=-1` in the `server.properties`.

Another possible solution to locate the entity in question could be to reduce the maximum scale limits by editing the config (`config/pehkui/config.json`) to values that definitely won't crash (e.g. 4.0), then loading whichever entity is causing the issue (which likely will be larger than others in the area). Then its scale could be set to something more managable via `/scale set` (or just reset its scale via `/scale reset`).
