### ISSUE TITLE
[Bug]: Compatability issue with create mod

### ISSUE THREAD

**Issue by ERBEpic** [Virtuoel/Pehkui#346]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

Fabric Loader 0.14.10

### Fabric API version

Fabric Api 0.67.1+1.19.2

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

For above, in both singleplayer and multiplayer. 

When attempting to use an item in create mod called the extendo grip, which increases range, block placing/breaking range is extended, however, attack range is not extended. This only occurs when Pehkui is installed, as without it the attack range is extended as normal. 

Due to it being a mod conflict, I was told to make an issue on both mods. Lmk if I'm doing something wrong

### Full list of installed mods and their version numbers

Pehkui 3.6.0+1.14.4-1.19.3
Create 0.5.0g-791+1.19.2
Fabric API 0.67.1+1.19.2

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by ERBEpic** [comment]
After a slight bit more testing, it seems it increases range by 1.  
![image](https://user-images.githubusercontent.com/70818523/205687653-ca108be4-a979-4f0b-887a-65f306aad7dd.png)
Left is without Pehkui, middle is with Pehkui, right is normal attack range

Ive also made an issue on Create, which github already has linked.

**Comment by Virtuoel** [comment]
From looking into this, seems it's on Create's end. See: my comment on their issue. If it turns out otherwise, I'll reopen this issue.
