### ISSUE TITLE
[Bug]: Can't open GUI blocks farther than normal reach

### ISSUE THREAD

**Issue by Xavienth** [Virtuoel/Pehkui#348]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

43.1.7

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

At larger scales, the player would expect their reach distance to scale too. Indeed, it does, with the block outlines showing up. The player should therefore be able to open, for example, a crafting table at a greater distance than a normally sized player.

What instead happens is the GUI briefly opens before the server rejects this action for being too far away and the GUI closes immediately.

I imagine this also happens in singleplayer due to the internal server.

### Full list of installed mods and their version numbers

Pehkui 3.6.0

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
Should now be resolved as of the 3.6.3 release.
