### ISSUE TITLE
[Bug]: Cause game crash 

### ISSUE THREAD

**Issue by KaiHaruki** [Virtuoel/Pehkui#349]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

Forge - 43.1.57

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

When updates other mods on my mod pack, it was unable to load and crash the game 

### Full list of installed mods and their version numbers

[KyuSekai (1) (1)-2.0.1.zip](https://github.com/Virtuoel/Pehkui/files/10185645/KyuSekai.1.1.-2.0.1.zip)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

[latest.log](https://github.com/Virtuoel/Pehkui/files/10185638/latest.log)

**Comment by Virtuoel** [comment]
Should now be fixed as of Pehkui 3.6.1.
