### ISSUE TITLE
[Bug]: Quilt loader is in lower polarity with fabric api.

### ISSUE THREAD

**Issue by netcore10** [Virtuoel/Pehkui#350]
### Minecraft version(s)

1.19.2

### Minecraft version details

1.19.2 

### Mod loader

Quilt

### Mod loader version

beta 19 

### Fabric API version

0.14.10

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Quilt is slow to update with polarity with fabric loader, is it possible to include 0.14.10 temporarily until quilt catches up?

![image](https://user-images.githubusercontent.com/181536/208446442-f7e51acf-c668-4fea-b298-c679f19dca8e.png)

### Full list of installed mods and their version numbers

na

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
You mentioned you're using Quilt Loader 0.18.1-beta.19. The latest stable (0.17.8) or latest beta (0.18.1-beta.25) already support mods using Fabric Loader 0.14.11.

**Comment by netcore10** [comment]
> You mentioned you're using Quilt Loader 0.18.1-beta.19. The latest stable (0.17.8) or latest beta (0.18.1-beta.25) already support mods using Fabric Loader 0.14.11.

odd, i couldn't get it to work even on the latest
