### ISSUE TITLE
damage and health scaling

### ISSUE THREAD

**Issue by oddvar812** [Virtuoel/Pehkui#36]
not sure if this is the right place to write suggestions, but i saw there was another suggestion about gravity so i thought i might as well share my two cents.

has "damage-output scaling" and "health scaling" been considered? for example by having a pehkui:health and  pehkui:damage scale type. to me this seems like the one thing missing from this mod, other than that it's perfect.

logically it makes sense, taking a hit from a 3 feet tall zombie should take more damage than taking a hit from a 1 inch zombie, a massive 10 feet pig should not die from getting punched a few times from regular sized steve. if this were to be implemented i think damage and health should be based on the volume of the mob. so a pig that is twice as tall, wide and long has 8 times the volume and should therefor has 8 times the health.

i think this would make the mod both more interesting and more fun. a big mob would suddenly be a lot more scary, as it should be. you could make monsters tiny and keep them as pets, since their low damage output wouldn't be dangerous. you could also make scenarios like "who would win, a zoglin-sized bee or a bee-sized zoglin" etc. and ofc, since it's just another scale type it also can be ignored by people who wouldn't want it, just like the other scale types.

i obviously don't expect anything and i have no idea how difficult or time consume this would be to implement, i just wanted to share the idea in case it hadn't been considered.

**Comment by GamyGamer** [comment]
I see that 3 types of scales has been added, health, attack and defense. It is not currently scalable by base scale, but if it would be activated then I would allow only scaling attack and defense.

My reason is that for example player jumping from 4 blocks will take 1 point of HP from fall damage surviving 20 of those jumps

If base was scaled to 0.25 then jump from 1 block is taking 1 point of HP and should be able to survive 20 jumps, but when also scaled health to 0.25 then player can survive only 5 of those jumps making it inconsisient with normal scale.

If I get defense corretly then setting it to 2 would block 50%  of incoming damage ( 6=>3) and setting to 0.5 would block -50% damage (6 => 12) from base health. If thats the case then I think this part should work correctly.

Althought I would keep health scale to be able to modify health easily via commands
