### ISSUE TITLE
[Bug]: Server Crash when any player joins

### ISSUE THREAD

**Issue by TheAyes** [Virtuoel/Pehkui#365]
### Minecraft version(s)

1.19.2

### Mod loader

Quilt

### Mod loader version

Quilt Loader 0.17.8

### Fabric API version

QFAPI 4.0.0 beta 26

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I've started the server and my friend tried to join but it only started heavily lagging and then showed "Disconnected".

### Full list of installed mods and their version numbers

	Quilt Mods: 
		| Index | Mod                                            | ID                                                    | Version                      |
		|------:|------------------------------------------------|-------------------------------------------------------|------------------------------|
		|    60 | Additionalentityattributes                     | additionalentityattributes                            | 1.0.0+1.19                   |
		|    88 | Adorn                                          | adorn                                                 | 3.8.1+1.19.2                 |
		|     1 | Alternate Current                              | alternate-current                                     | 1.4.0                        |
		|    63 | Apoli                                          | apoli                                                 | 2.6.1                        |
		|   124 | AppleSkin                                      | appleskin                                             | 2.4.1+mc1.19                 |
		|   166 | Architectury                                   | architectury                                          | 6.4.62                       |
		|    16 | Bad Packets                                    | badpackets                                            | 0.2.1                        |
		|    75 | Balm                                           | balm-fabric                                           | 4.5.2+0                      |
		|   184 | Better Animals Plus                            | betteranimalsplus                                     | 1.19.2-11.0.10               |
		|   114 | Better Combat                                  | bettercombat                                          | 1.5.4+1.19                   |
		|     4 | CICADA                                         | cicada                                                | 0.1.1                        |
		|    22 | Calio                                          | calio                                                 | 1.7.0                        |
		|    37 | Cardinal Components API (base)                 | cardinal-components-base                              | 5.0.2                        |
		|    40 | Cardinal Components API (blocks)               | cardinal-components-block                             | 5.0.2                        |
		|    46 | Cardinal Components API (chunks)               | cardinal-components-chunk                             | 5.0.2                        |
		|    36 | Cardinal Components API (entities)             | cardinal-components-entity                            | 5.0.2                        |
		|    43 | Cardinal Components API (items)                | cardinal-components-item                              | 5.0.1                        |
		|    52 | Cardinal Components API (worlds)               | cardinal-components-world                             | 5.0.2                        |
		|    93 | Charm                                          | charm                                                 | 4.4.4                        |
		|    89 | Cloth Config v8                                | cloth-config                                          | 8.2.88                       |
		|   188 | Continents                                     | continents                                            | 1.1                          |
		|   177 | Create                                         | create                                                | 0.5.0g-796+1.19.2            |
		|   168 | Debugify                                       | debugify                                              | 2.8.0                        |
		|    87 | Dripstone Fluid Lib                            | dripstone_fluid_lib                                   | 2.0.1                        |
		|   195 | Effective                                      | effective                                             | 1.6+1.19.2                   |
		|   137 | EldritchMobs                                   | eldritch_mobs                                         | 1.12.10                      |
		|   154 | Extra Origins                                  | extraorigins                                          | 1.19-2                       |
		|   158 | Fabric Language Kotlin                         | fabric-language-kotlin                                | 1.8.6+kotlin.1.7.21          |
		|    55 | Fake Player API                                | fake-player-api                                       | 0.5.0                        |
		|    92 | FallingTree                                    | fallingtree                                           | 3.10.0                       |
		|    76 | FastAnim                                       | faster_entity_animations                              | 1.5.7                        |
		|   205 | FerriteCore                                    | ferritecore                                           | 5.0.3                        |
		|   117 | Forge Config API Port                          | forgeconfigapiport                                    | 4.2.6                        |
		|    95 | Geckolib                                       | geckolib3                                             | 3.1.40                       |
		|   133 | Incendium                                      | incendium                                             | 5.1.4                        |
		|   160 | Iron Chests                                    | ironchests                                            | 1.7.7                        |
		|    19 | Jankson                                        | jankson                                               | 4.1.1+j1.2.1                 |
		|    62 | Java HotSpot(TM) 64-Bit Server VM              | java                                                  | 17                           |
		|    23 | Kanos Config                                   | kanos_config                                          | 0.3.1+1.14.4-1.19            |
		|    12 | Krypton                                        | krypton                                               | 0.2.1                        |
		|     8 | Langfiles Plus                                 | langfiles-plus                                        | 1.0.0                        |
		|   206 | Lanterns Belong on Walls                       | walllanterns                                          | 1.4.0-1.19                   |
		|    45 | LazyDFU                                        | lazydfu                                               | 0.1.3                        |
		|   170 | Let Me Despawn                                 | letmedespawn                                          | fabric-1.0.2                 |
		|   118 | LibGui                                         | libgui                                                | 6.2.0+1.19                   |
		|    21 | LibNinePatch                                   | libninepatch                                          | 1.1.0                        |
		|    99 | Lithium                                        | lithium                                               | 0.10.4                       |
		|   207 | LodestoneLib                                   | lodestone                                             | 413d9b4712                   |
		|    42 | Manningham Mills                               | mm                                                    | 2.3                          |
		|    17 | MidnightLib                                    | midnightlib                                           | 0.6.1                        |
		|    71 | Milk Lib                                       | milk                                                  | 1.0.51                       |
		|   136 | Mimic                                          | mimic                                                 | 1.2.38                       |
		|   111 | Minecraft                                      | minecraft                                             | 1.19.2                       |
		|    29 | MixinExtras                                    | com_github_llamalad7_mixinextras                      | 0.1.1                        |
		|    30 | Naturalist                                     | naturalist                                            | 2.1.1                        |
		|   200 | Nullscape                                      | nullscape                                             | 1.2                          |
		|   127 | OPAC Create Mod Support                        | opaccreatesupport                                     | 1.1.0                        |
		|    27 | Oh The Biomes You'll Go                        | byg                                                   | 2.0.0.13                     |
		|    24 | OmegaConfig                                    | omega-config                                          | 1.2.2-1.18.1                 |
		|    59 | Open Parties and Claims                        | openpartiesandclaims                                  | 0.16.6                       |
		|    84 | Origins                                        | origins                                               | 1.7.1                        |
		|   148 | Packet Tweaker                                 | packet_tweaker                                        | 0.3.0+1.18.2                 |
		|     6 | Pal                                            | playerabilitylib                                      | 1.6.0                        |
		|   101 | Pehkui                                         | pehkui                                                | 3.6.3+1.14.4-1.19.3          |
		|    54 | Player Animator                                | player-animator                                       | 0.4.0                        |
		|   110 | Polymer (Core)                                 | polymer                                               | 0.2.18+1.19.2                |
		|     5 | Polymer Blocks                                 | polymer-blocks-ext                                    | 0.1.0-alpha.9+1.19.2         |
		|   208 | Polymer Registry Sync Manipulator              | polymer-registry-sync-manipulator                     | 0.0.3+1.19.2                 |
		|   121 | Polymorph                                      | polymorph                                             | 0.46.1+1.19.2                |
		|   165 | Porting Lib                                    | porting_lib                                           | 2.1.623+1.19.2               |
		|   143 | Porting Lib Accessors                          | porting_lib_accessors                                 | 2.1.623+1.19.2               |
		|   123 | Porting Lib Attributes                         | porting_lib_attributes                                | 2.1.623+1.19.2               |
		|    73 | Porting Lib Base                               | porting_lib_base                                      | 2.1.623+1.19.2               |
		|   149 | Porting Lib Common                             | porting_lib_common                                    | 2.1.623+1.19.2               |
		|   196 | Porting Lib Constants                          | porting_lib_constants                                 | 2.1.623+1.19.2               |
		|   122 | Porting Lib Entity                             | porting_lib_entity                                    | 2.1.623+1.19.2               |
		|   132 | Porting Lib Extensions                         | porting_lib_extensions                                | 2.1.623+1.19.2               |
		|   176 | Porting Lib Lazy Register                      | porting_lib_lazy_registration                         | 2.1.623+1.19.2               |
		|   162 | Porting Lib Model Generators                   | porting_lib_model_generators                          | 2.1.623+1.19.2               |
		|   194 | Porting Lib Model Loader                       | porting_lib_model_loader                              | 2.1.623+1.19.2               |
		|   116 | Porting Lib Models                             | porting_lib_models                                    | 2.1.623+1.19.2               |
		|   180 | Porting Lib Networking                         | porting_lib_networking                                | 2.1.623+1.19.2               |
		|    64 | Porting Lib Obj Loader                         | porting_lib_obj_loader                                | 2.1.623+1.19.2               |
		|    81 | Porting Lib Tags                               | forge_tags                                            | 3.0                          |
		|    61 | Porting Lib Transfer                           | porting_lib_transfer                                  | 2.1.623+1.19.2               |
		|   126 | Puzzles Lib                                    | puzzleslib                                            | 4.3.12                       |
		|   131 | Qu Enchantments                                | qu-enchantments                                       | 1.2.4-1.19                   |
		|   128 | Quilt Advancement API                          | quilt_advancement                                     | 3.0.0-beta.25+1.19.2         |
		|   153 | Quilt Base API                                 | quilt_base                                            | 3.0.0-beta.25+1.19.2         |
		|   169 | Quilt Biome API                                | quilt_biome                                           | 3.0.0-beta.25+1.19.2         |
		|   125 | Quilt Block Content Registry API               | quilt_block_content_registry                          | 3.0.0-beta.25+1.19.2         |
		|   150 | Quilt Block Entity API                         | quilt_block_entity                                    | 3.0.0-beta.25+1.19.2         |
		|    68 | Quilt Block Extensions API                     | quilt_block_extensions                                | 3.0.0-beta.25+1.19.2         |
		|   139 | Quilt Command API                              | quilt_command                                         | 3.0.0-beta.25+1.19.2         |
		|    90 | Quilt Crash Info                               | quilt_crash_info                                      | 3.0.0-beta.25+1.19.2         |
		|   159 | Quilt DataFixerUpper API                       | quilt_datafixerupper                                  | 3.0.0-beta.25+1.19.2         |
		|    74 | Quilt Dimension API                            | quilt_dimension                                       | 3.0.0-beta.25+1.19.2         |
		|    82 | Quilt Entity API                               | quilt_entity                                          | 3.0.0-beta.25+1.19.2         |
		|   113 | Quilt Entity Events                            | quilt_entity_events                                   | 3.0.0-beta.25+1.19.2         |
		|   145 | Quilt Entity Networking API                    | quilt_entity_networking                               | 3.0.0-beta.25+1.19.2         |
		|   129 | Quilt Item Content Registry API                | quilt_item_content_registry                           | 3.0.0-beta.25+1.19.2         |
		|    83 | Quilt Item Extension API                       | quilt_item_extension                                  | 3.0.0-beta.25+1.19.2         |
		|    97 | Quilt Item Group API                           | quilt_item_group                                      | 3.0.0-beta.25+1.19.2         |
		|    56 | Quilt Item Setting API                         | quilt_item_setting                                    | 3.0.0-beta.25+1.19.2         |
		|   192 | Quilt Lifecycle Events                         | quilt_lifecycle_events                                | 3.0.0-beta.25+1.19.2         |
		|   171 | Quilt Loader                                   | quilt_loader                                          | 0.17.8                       |
		|    65 | Quilt Multipart Entity API                     | quilt_entity_multipart                                | 3.0.0-beta.25+1.19.2         |
		|   183 | Quilt Networking                               | quilt_networking                                      | 3.0.0-beta.25+1.19.2         |
		|   155 | Quilt Points of Interest                       | quilt_points_of_interest                              | 3.0.0-beta.25+1.19.2         |
		|   187 | Quilt Recipe API                               | quilt_recipe                                          | 3.0.0-beta.25+1.19.2         |
		|   174 | Quilt Registry API                             | quilt_registry                                        | 3.0.0-beta.25+1.19.2         |
		|   167 | Quilt Registry Entry Attachment                | quilt_registry_entry_attachment                       | 3.0.0-beta.25+1.19.2         |
		|   178 | Quilt Resource Loader                          | quilt_resource_loader                                 | 3.0.0-beta.25+1.19.2         |
		|   197 | Quilt Status Effect API                        | quilt_status_effect                                   | 3.0.0-beta.25+1.19.2         |
		|   191 | Quilt Surface Rule API                         | quilt_surface_rule                                    | 3.0.0-beta.25+1.19.2         |
		|   179 | Quilt Tags API                                 | quilt_tags                                            | 3.0.0-beta.25+1.19.2         |
		|   107 | Quilt Tooltip API                              | quilt_tooltip                                         | 3.0.0-beta.25+1.19.2         |
		|   146 | Quilt Vehicle API                              | quilt_vehicle                                         | 3.0.0-beta.25+1.19.2         |
		|    78 | Quilt Villager API                             | quilt_villager                                        | 3.0.0-beta.25+1.19.2         |
		|   185 | Quilted Fabric API                             | quilted_fabric_api                                    | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   164 | Quilted Fabric API Base                        | quilted_fabric_api_base                               | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   172 | Quilted Fabric API Lookup API (v1)             | quilted_fabric_api_lookup_api_v1                      | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   161 | Quilted Fabric Biome API (v1)                  | quilted_fabric_biome_api_v1                           | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   199 | Quilted Fabric Block API (v1)                  | quilted_fabric_block_api_v1                           | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   142 | Quilted Fabric Command API (v1)                | quilted_fabric_command_api_v1                         | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   144 | Quilted Fabric Command API (v2)                | quilted_fabric_command_api_v2                         | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    70 | Quilted Fabric Commands (v0)                   | quilted_fabric_commands_v0                            | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   152 | Quilted Fabric Containers (v0)                 | quilted_fabric_containers_v0                          | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   201 | Quilted Fabric Content Registries (v0)         | quilted_fabric_content_registries_v0                  | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    80 | Quilted Fabric Convention Tags API (v1)        | quilted_fabric_convention_tags_api_v1                 | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    67 | Quilted Fabric Crash Report Info (v1)          | quilted_fabric_crash_report_info_v1                   | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    91 | Quilted Fabric Data Generation API (v1)        | quilted_fabric_data_generation_api_v1                 | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   103 | Quilted Fabric Dimensions API (v1)             | quilted_fabric_dimensions_v1                          | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   151 | Quilted Fabric Entity Events (v1)              | quilted_fabric_entity_events_v1                       | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   106 | Quilted Fabric Events Interaction (v0)         | quilted_fabric_events_interaction_v0                  | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    86 | Quilted Fabric Events Lifecycle (v0)           | quilted_fabric_events_lifecycle_v0                    | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   141 | Quilted Fabric Game Rule API (v1)              | quilted_fabric_game_rule_api_v1                       | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   157 | Quilted Fabric Item API (v1)                   | quilted_fabric_item_api_v1                            | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   130 | Quilted Fabric Item Groups (v0)                | quilted_fabric_item_groups_v0                         | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    96 | Quilted Fabric Lifecycle Events (v1)           | quilted_fabric_lifecycle_events_v1                    | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   190 | Quilted Fabric Loot API (v2)                   | quilted_fabric_loot_api_v2                            | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    58 | Quilted Fabric Loot Tables (v1)                | quilted_fabric_loot_tables_v1                         | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    85 | Quilted Fabric Message API (v1)                | quilted_fabric_message_api_v1                         | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   204 | Quilted Fabric Mining Level API (v1)           | quilted_fabric_mining_level_api_v1                    | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   140 | Quilted Fabric Networking (v0)                 | quilted_fabric_networking_v0                          | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   135 | Quilted Fabric Networking API (v1)             | quilted_fabric_networking_api_v1                      | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    79 | Quilted Fabric Object Builder API (v1)         | quilted_fabric_object_builder_api_v1                  | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   202 | Quilted Fabric Particles (v1)                  | quilted_fabric_particles_v1                           | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   120 | Quilted Fabric Recipe API (v1)                 | quilted_fabric_recipe_api_v1                          | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   109 | Quilted Fabric Registry Sync (v0)              | quilted_fabric_registry_sync_v0                       | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   147 | Quilted Fabric Rendering Data Attachment (v1)  | quilted_fabric_rendering_data_attachment_v1           | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   175 | Quilted Fabric Rendering Fluids (v1)           | quilted_fabric_rendering_fluids_v1                    | 4.0.0-beta.26+0.72.0-1.19.2  |
		|    72 | Quilted Fabric Resource Conditions API (v1)    | quilted_fabric_resource_conditions_api_v1             | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   193 | Quilted Fabric Resource Loader (v0)            | quilted_fabric_resource_loader_v0                     | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   186 | Quilted Fabric Screen Handler API (v1)         | quilted_fabric_screen_handler_api_v1                  | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   181 | Quilted Fabric Transfer API (v1)               | quilted_fabric_transfer_api_v1                        | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   173 | Quilted Fabric Transitive Access Wideners (v1) | quilted_fabric_transitive_access_wideners_v1          | 4.0.0-beta.26+0.72.0-1.19.2  |
		|   104 | Reach Entity Attributes                        | reach-entity-attributes                               | 2.3.0                        |
		|   182 | Registrate for Fabric                          | registrate-fabric                                     | 1.1.44-MC1.19.2              |
		|    77 | Repurposed Structures                          | repurposed_structures                                 | 6.3.9+1.19.2                 |
		|    53 | Runtime Resource Pack                          | advanced_runtime_resource_pack                        | 0.6.2                        |
		|   203 | Serialization Hooks                            | serialization_hooks                                   | 0.3.26                       |
		|   134 | Server Translations API                        | server_translations_api                               | 1.4.18+1.19.2                |
		|   112 | Simple Voice Chat                              | voicechat                                             | 1.19.2-2.3.27                |
		|    49 | Smooth Boot                                    | smoothboot                                            | 1.19-1.7.1                   |
		|    66 | Sound Physics Remastered                       | sound_physics_remastered                              | 1.19.2-1.0.18                |
		|   115 | SpectreLib                                     | spectrelib                                            | 0.11.0+1.19                  |
		|   105 | Starlight                                      | starlight                                             | 1.1.1+fabric.ae22326         |
		|    18 | TerraBlender                                   | terrablender                                          | 2.0.1.136                    |
		|   189 | Terralith                                      | terralith                                             | 2.3                          |
		|    98 | The Graveyard                                  | graveyard                                             | 2.3                          |
		|    51 | This Rocks!                                    | rocks                                                 | 1.6.1                        |
		|   102 | Traveler's Backpack                            | travelersbackpack                                     | 1.19.2-8.2.10                |
		|   100 | Visual Workbench                               | visualworkbench                                       | 4.2.1                        |
		|   108 | When Dungeons Arise                            | dungeons_arise                                        | 2.1.54                       |
		|   119 | Xaero's Minimap                                | xaerominimap                                          | 22.17.1                      |
		|   138 | Xaero's World Map                              | xaeroworldmap                                         | 1.28.8                       |
		|    69 | YUNG's API                                     | yungsapi                                              | 1.19.2-Fabric-3.8.2          |
		|    57 | YUNG's Better Dungeons                         | betterdungeons                                        | 1.19.2-Fabric-3.2.1          |
		|    94 | YUNG's Better Mineshafts                       | bettermineshafts                                      | 1.19.2-Fabric-3.2.0          |
		|   163 | YUNG's Better Strongholds                      | betterstrongholds                                     | 1.19.2-Fabric-3.2.0          |
		|   198 | You're in Grave Danger                         | yigd                                                  | 1.4.7                        |
		|    10 | atomicfu-jvm                                   | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.18.5                       |
		|    48 | cloth-basic-math                               | cloth-basic-math                                      | 0.6.1                        |
		|    44 | core                                           | com_electronwill_night-config_core                    | 3.6.6                        |
		|    25 | jankson                                        | blue_endless_jankson                                  | 1.2.1                        |
		|    47 | javassist                                      | org_javassist_javassist                               | 3.28.0-GA                    |
		|    38 | jsr305                                         | com_google_code_findbugs_jsr305                       | 3.0.2                        |
		|    35 | kotlin-reflect                                 | org_jetbrains_kotlin_kotlin-reflect                   | 1.7.21                       |
		|    32 | kotlin-stdlib                                  | org_jetbrains_kotlin_kotlin-stdlib                    | 1.7.21                       |
		|     7 | kotlin-stdlib-jdk7                             | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.7.21                       |
		|     9 | kotlin-stdlib-jdk8                             | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.7.21                       |
		|    20 | kotlinx-coroutines-core-jvm                    | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                        |
		|    34 | kotlinx-coroutines-jdk8                        | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                        |
		|    15 | kotlinx-datetime-jvm                           | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                        |
		|    26 | kotlinx-serialization-cbor-jvm                 | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.4.1                        |
		|    41 | kotlinx-serialization-core-jvm                 | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.4.1                        |
		|     0 | kotlinx-serialization-json-jvm                 | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.4.1                        |
		|    28 | mclib                                          | com_eliotlash_mclib_mclib                             | 20                           |
		|     2 | megane                                         | megane                                                | 8.3.0                        |
		|    39 | megane-api                                     | megane-api                                            | 8.3.0                        |
		|    13 | megane-fabric-transfer                         | megane-fabric-transfer                                | 8.3.0                        |
		|    11 | megane-runtime                                 | megane-runtime                                        | 8.3.0                        |
		|     3 | megane-vanilla                                 | megane-vanilla                                        | 8.3.0                        |
		|    31 | reflections                                    | org_reflections_reflections                           | 0.10.2                       |
		|    50 | toml                                           | com_electronwill_night-config_toml                    | 3.6.6                        |
		|    33 | toml4j                                         | com_moandjiezana_toml_toml4j                          | 0.7.2                        |
		|    14 | velocity-native                                | com_velocitypowered_velocity-native                   | 3.1.2-SNAPSHOT               |
		|   156 | wthit                                          | wthit                                                 | 5.13.4                       |
		|------:|------------------------------------------------|-------------------------------------------------------|------------------------------|

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
[crash-2023-01-22_13.33.52-server.txt](https://github.com/Virtuoel/Pehkui/files/10474436/crash-2023-01-22_13.33.52-server.txt)
</p>

**Comment by TheAyes** [comment]
Tested with Pehkui 3.6.3 and 3.6.2.

**Comment by Virtuoel** [comment]
Seeing as the Watchdog killed the server, this doesn't appear to be a Pehkui issue, just that it happened to stop the server at the same time as Pehkui was doing stuff. Looking at your crash log, it appears that your server had 16019 item entities loaded in the world near where the player joined, which'll likely crash most servers with or without Pehkui. Maybe a Create contraption gone wrong making too many items?
