### ISSUE TITLE
Death bug

### ISSUE THREAD

**Issue by Rwstix** [Virtuoel/Pehkui#37]
I play with this mod and origins mod and i've created a origin which makes you change size but whenever I take certain damage like when I'm drowning the respawn screen show up and after that my character is all red and laggy cause the think i'm dead.

Here are some screenshots:
![2021-02-27_12 14 01](https://user-images.githubusercontent.com/79268223/109394520-73336200-78f5-11eb-8918-5aa21ca8f351.png)
![2021-02-27_12 14 11](https://user-images.githubusercontent.com/79268223/109394521-73336200-78f5-11eb-9c15-c844d96f7bf0.png)

**Comment by Rwstix** [comment]
I closed the issue thinking I've resolved the problem but not at all please help me !

**Comment by Virtuoel** [comment]
My guess is that this is related to how Origins handles health, seeing as you have fewer hearts than normal. As the version of Pehkui you're using doesn't affect health, this is not a Pehkui issue.
