### ISSUE TITLE
[Bug]: Pekhui crashed on startup Mixin Forge

### ISSUE THREAD

**Issue by MaharaTheOwl** [Virtuoel/Pehkui#371]
### Minecraft version(s)

1.18.2

### Mod loader

Forge

### Mod loader version

40.2.0

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Game doesn't launch and gives and exit code 1.

### Full list of installed mods and their version numbers

[Modlist.txt](https://github.com/Virtuoel/Pehkui/files/10691026/Modlist.txt)

### Did the problem cause the game to crash?

Yes.

### Full crash report contents (if you experienced a crash)

[latest.log](https://github.com/Virtuoel/Pehkui/files/10691027/latest.log)

**Comment by Virtuoel** [comment]
Resolved as of the 3.7.0 release.
