### ISSUE TITLE
Not working on fabric 0.14.13 or Minecraft 1.19.2

### ISSUE THREAD

**Issue by JackusS18** [Virtuoel/Pehkui#381]
I have added this so I can use some origins add-ons on the feather launcher. It's has fabric 0.14.13 and I can't change this but when I try and launch up fabric with the mod installs it crashed and says it's because of the fabric version. Is there anyway for me to use it on 0.14.13

**Comment by Virtuoel** [comment]
Not a Pehkui problem. Most launchers have a way to change the Fabric Loader version. Surely whatever Feather is, it can too somehow. If not, send them an issue report I guess. It's a fairly basic feature.
