### ISSUE TITLE
[Bug]: Server hangs, something to do with the AbstractArrow class

### ISSUE THREAD

**Issue by briarss** [Virtuoel/Pehkui#385]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

43.2.6

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

The server hung while fighting a pretty heavily modded raid. I will attach a thread dump, as it didn't crash but hang instead.

### Full list of installed mods and their version numbers

abundant_atmosphere-1.19.2-1.0.2.jar                                 
adaptive_performance_tweaks_1.19.2-6.5.0.jar                         
adaptive_performance_tweaks_core_1.19.2-6.6.0.jar                    
adaptive_performance_tweaks_gamerules_1.19.2-6.5.0.jar               
adaptive_performance_tweaks_items_1.19.2-6.6.0.jar                   
adaptive_performance_tweaks_mods_1.19.2-6.5.2.jar                    
adaptive_performance_tweaks_player_1.19.2-6.5.0.jar                  
adaptive_performance_tweaks_spawn_1.19.2-6.6.0.jar                   
AdvancedCompas-forge-1.19.2-1.2.14.jar                               
AI-Improvements-1.19.2-0.5.2.jar                                     
Alexs Armoury v1.4.1-1.19.2.jar                                      
alexsdelight-1.4.1.jar                                               
alexsmobs-1.21.1.jar                                                 
almostunified-forge-1.19.2-0.3.6.jar                                 
Apotheosis-1.19.2-6.1.2.jar                                          
appleskin-forge-mc1.19-2.4.2.jar                                     
aquamirae-5.6.API14.jar                                              
architectury-6.5.69-forge.jar                                        
areas-1.19.2-4.3.jar                                                 
arsarmiger-1.19.2-1.4.0.jar                                          
ars_creo-1.19.2-3.1.3.jar                                            
ars_instrumentum-1.19.2-3.2.3.jar                                    
ars_nouveau-1.19.2-3.12.3.jar                                        
art_of_forging-1.6.1-1.19.2.jar                                      
astikorcarts-1.19.2-1.1.2.jar                                        
asynclocator-1.19.2-1.2.0.jar                                        
AttributeFix-Forge-1.19.2-17.2.6.jar                                 
attribution-1.0.0.jar                                                
AutoRegLib-1.8.2-55.jar                                              
backpacked-2.1.10-1.19.jar                                           
balm-forge-1.19.2-4.5.7.jar                                          
beautifiedchatclient-1.19.2-2.2.jar                                  
BetterAdvancements-1.19.2-0.2.2.142.jar                              
bettercombat-forge-1.6.2+1.19.jar                                    
BetterCompatibilityChecker-1.0.10-build.50+mc1.19.2.jar              
BetterModsButton-v4.2.1-1.19.2-Forge.jar                             
BetterThirdPerson-Forge-1.19-1.9.0.jar                               
bigbrain-1.6.1.jar                                                   
biomancy-forge-1.19.2-2.0.48.0.jar                                   
BiomesOPlenty-1.19.2-17.1.1.162.jar                                  
blossom-forge-1.19.2-1.0.7.jar                                       
blueprint-1.19.2-6.1.2.jar                                           
blue_skies-1.19.2-1.3.20.jar                                         
Bookshelf-Forge-1.19.2-16.2.18.jar                                   
born_in_chaos_1.19_1.3.jar                                           
botarium-forge-1.19.2-1.8.2.jar                                      
bygonenether-1.2.2-1.19.2.jar                                        
caelus-forge-1.19.2-3.0.0.6.jar                                      
canary-mc1.19.2-0.1.9.jar                                            
casting_crystals-1.0.3.jar                                           
cave-enhancements-1.19.2-2.1.11-forge.jar                            
chat_heads-0.10.7-forge-1.19.2.jar                                   
chipped-forge-1.19.2-2.1.2.jar                                       
Chunky-1.3.38.jar                                                    
citadel-2.1.1-1.19.jar                                               
cloth-config-8.2.88-forge.jar                                        
Clumps-forge-1.19.2-9.0.0+14.jar                                     
collective-1.19.2-6.53.jar                                           
collectorsreap-1.19-1.2.jar                                          
comforts-forge-6.0.3+1.19.2.jar                                      
command_structures_forge-3.1.0+1.19.jar                              
compost-forge-1.19.2-1.1.2.jar                                       
configured-2.0.1-1.19.2.jar                                          
Continents_1.19.3_v1.1.2.jar                                         
Controlling-forge-1.19.2-10.0+7.jar                                  
CorgiLib-forge-1.19.2-1.0.0.32.jar                                   
CosmeticArmorReworked-1.19.2-v1a.jar                                 
create-1.19.2-0.5.0.i.jar                                            
createbigcannons-1.19.2-beta-0.5.b.jar                               
CreativeCore_FORGE_v2.9.3_mc1.19.2.jar                               
CTM-1.19.2-1.1.6+8.jar                                               
ctov-3.1.8.jar                                                       
culturaldelights-1.19.2-0.15.1.jar                                   
curios-forge-1.19.2-5.1.3.0.jar                                      
curiouslanterns-1.19.2-1.2.1.jar                                     
Delightful-1.19.2-3.2.2.jar                                          
dimdungeons-168-forge-1.19.0.jar                                     
DungeonsArise-1.19.2-2.1.54-release.jar                              
dungeons_gear-1.19.2-5.0.4-beta.jar                                  
dungeons_libraries-1.19.2-3.0.9-beta.jar                             
dungeons_mobs-1.19.2-4.0.6-beta.jar                                  
dungeons_plus-1.19.2-1.3.0.jar                                       
dynamiccrosshair-5.1+1.19.2-forge.jar                                
ears-forge-1.19-1.4.6.jar                                            
EE_Ars_Nouveau_Addon-1.0.0-build.4+mc1.19.2.jar                      
EE_Create_Addon-1.0.1-build.5+mc1.19.2.jar                           
EE_Occultism_Addon-1.0.0-build.4+mc1.19.2.jar                        
EmendatusEnigmatica-2.1.4-build.58+mc1.19.2.jar                      
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar                     
endersdelight-1.19-1.0.2.jar                                         
endrem_forge-5.2.1-R-1.19.X.jar                                      
EnigmaticGraves-1.19.2-1.7.6.jar                                     
EnigmaticLegacy-2.26.5.jar                                           
enlightened-end-1.19.2-v4.0.0.1.jar                                  
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar                      
EquipmentCompare-1.19.2-forge-1.3.2.jar                              
Essential-forge_1-18-2.jar                                           
everycomp-1.19.2-2.2.3.jar                                           
explorify-forge-1.19-1.3.0.jar                                       
faction_craft-1.19.2-1.1.5.jar.disabled                              
Fallingleaves-1.19.1-1.3.1.jar                                       
fantasydice-1.19.2-7.2.0.jar                                         
fantasyfurniture-1.19.2-6.7.0.jar                                    
FarmersDelight-1.19-1.2.0.jar                                        
FarmersRespite-1.19-2.0.jar                                          
Fastload-Reforged-2.6.9+1.19.2.jar                                   
FastSuite-1.19.2-4.0.0.jar                                           
feathers-1.0.4.jar                                                   
Female-Gender-Mod-forge-1.19.1-3.0.1.jar                             
ferdinandsflowers-2.01-1.19.2.jar                                    
ferritecore-5.0.3-forge.jar                                          
flywheel-forge-1.19.2-0.6.8.a.jar                                    
forbidden_arcanus-1.19.2-2.1.2.jar                                   
framework-0.4.2-1.19.2.jar                                           
ftb-library-forge-1902.3.15-build.188.jar                            
ftb-teams-forge-1902.2.12-build.95.jar                               
ftb_teams_nametag_addon-19.2.0.2.jar                                 
GatewaysToEternity-1.19.2-3.1.1.jar                                  
geckolib-forge-1.19-3.1.40.jar                                       
gentlepicking-1.19.2-1.0.0.jar                                       
Geolosys-1.19.2-7.0.10.jar                                           
getittogetherdrops-forge-1.19.2-1.3.jar                              
gnumus_settlement_1.19_v1.4.jar                                      
goblins-0.5.jar                                                      
GottschCore-mc1.19.2-f43.2.0-v2.0.5.jar                              
grappling_hook_mod-1.19.2-1.19.2-v13.jar                             
guardvillagers-1.19.2-1.5.5.jar.disabled                             
habitat-1.1.9.jar                                                    
harvestwithease-1.19.2-6.0.0.0-final-forge.jar                       
healingflasks1.2.1.jar                                               
hexal-forge-1.19.2-0.2.10.jar                                        
hexcasting-forge-1.19.2-0.10.3.jar                                   
hexerei-0.2.5.jar                                                    
hexfortress-0.0.2-1.19.2.jar                                         
HigherWorldDeeperOceans-1.19.x.jar                                   
hmag-forge-mc1.19.2-6.1.8.jar                                        
horse_colors-1.19.2-11.1.jar                                         
hourglass-1.19.1-1.2.1.1.jar                                         
Iceberg-1.19.2-forge-1.1.4.jar                                       
idas_forge-1.6.1+1.19.2.jar                                          
illageandspillage-1.19.2-1.2.4.jar                                   
illager_additions-1.19-0.0.2-alpha.jar                               
immersive_weathering-1.19.2-1.2.8-forge.jar                          
Incendium_1.19.3_v5.1.5.jar                                          
incontrol-1.19-7.1.3.jar                                             
InsaneLib-1.7.5-mc1.19.2.jar                                         
integrated_api_forge-1.2.2+1.19.2.jar                                
integrated_stronghold_forge-1.0.1+1.19.2.jar                         
ItemBorders-1.19.1-1.2.0.jar                                         
ItemPhysic_FORGE_v1.6.6_mc1.19.2.jar                                 
jmi-forge-1.19.2-0.13-33.jar                                         
journeymap-1.19.2-5.9.4-forge.jar                                    
Kiwi-1.19.1-forge-8.2.1.jar                                          
Kobolds-2.5.7.jar                                                    
konkrete_forge_1.6.0_MC_1.19-1.19.2.jar                              
kotlinforforge-3.11.0-all.jar                                        
kubejs-forge-1902.6.0-build.142.jar                                  
labels-1.19.2-1.8.jar                                                
LegendaryTooltips-1.19.2-forge-1.4.0.jar                             
leosillagers-1.1.2.jar                                               
letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar                           
LibX-1.19.2-4.2.8.jar                                                
lightspeed-1.19.2-1.0.2.jar                                          
list.txt                                                             
lootbeams-1.19.2-release-mar1123.jar                                 
lootjs-forge-1.19.2-2.7.9.jar                                        
lootr-1.19-0.3.22.59.jar                                             
loot_journal-2.1.jar                                                 
L_Enders_Cataclysm-0.73-1.19.2.jar                                   
majrusz-library-1.19.2-3.3.0.jar                                     
majruszs-accessories-1.19.2-1.1.4.jar                                
majruszs-difficulty-1.19.2-1.7.3.jar                                 
majruszs-enchantments-1.19.2-1.8.1.jar                               
MapFrontiers-1.19.1-2.4.0.jar                                        
meetyourfight-1.19.2-1.2.8.jar                                       
memorysettings-1.19.2-2.2.jar                                        
MerchantMarkers-1.19.2-1.3.0.jar                                     
MineMention-1.19.1-2.1.0.jar                                         
Mirabilis 1.0.7 1.19.2.jar                                           
mmoparties-2.4.2.1.19.2.jar.disabled                                 
MobDiceAttributes-mc1.19.2-f43.2.0-v1.0.1.jar                        
mobhealthbar-forge-1.19-41.0.100-2.1.1.jar                           
modernfix-mc1.19.2-3.1.1-1-g214015d.jar                              
modernworldcreation_forge_1.0.0_MC_1.19.jar                          
modonomicon-1.19.2-1.28.0.jar                                        
moonlight-1.19.2-2.2.16-forge.jar                                    
morejs-forge-1.19.2-0.0.7.jar                                        
MouseTweaks-forge-mc1.19-2.23.jar                                    
mutantmore-1.19.2-early-access-1.0.6.jar                             
mutil-1.19.2-5.1.0.jar                                               
mvs-3.1.6-1.19.2.jar                                                 
naturalist-forge-2.1.1-1.19.2.jar                                    
neapolitan-1.19.2-4.0.2.jar                                          
NethersDelight-1.19-3.0.jar                                          
notenoughanimations-forge-1.6.2-mc1.19.2.jar                         
nourished-nether-1.19.2-v24.jar                                      
Nullscape_1.19.3_v1.2.1.jar                                          
numismaticoverhaul-1.19.2-1.0.4.jar                                  
obscure_api-14.jar                                                   
observable-3.3.1.jar                                                 
occultism-1.19.2-1.73.0.jar                                          
oculus-mc1.19.2-1.2.8a.jar                                           
ogres-0.6.jar                                                        
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.1.jar                     
OpenLoader-Forge-1.19.2-15.0.1.jar                                   
origins-classes-forge-1.2.0.jar                                      
origins-forge-1.19.2-1.5.0.6-all.jar                                 
ParCool-1.19.2-3.0.0.2-R.jar                                         
PassableFoliage-1.19.1-forge-5.0.1.jar                               
Patchouli-1.19.2-77.jar                                              
paucal-forge-1.19.2-0.5.0.jar                                        
Pehkui-3.7.0+1.19.2-forge.jar                                        
personality-1.19-3.0.1.jar                                           
Philips-ruins1.19.2-5.0.jar                                          
physics-mod-pro-v136-forge-1.19.2.jar                                
Placebo-1.19.2-7.1.5.jar                                             
player-animation-lib-forge-1.0.2.jar                                 
PlayerRevive_FORGE_v2.0.14_mc1.19.2.jar                              
pluto-mc1.19.2-0.0.8.jar                                             
ponderjs-1.19.2-1.1.11.jar                                           
PresenceFootsteps-1.19.2-1.6.4.1-forge.jar                           
PrettyPipes-1.13.6.jar                                               
Prism-1.19.1-1.0.2.jar                                               
probejs-4.4.0-forge.jar                                              
ProgressiveBosses-3.7.5-mc1.19.2.jar                                 
PuzzlesLib-v4.3.12-1.19.2-Forge.jar                                  
Quark-3.4-394.jar                                                    
QuarkOddities-1.18.jar                                               
questapi-1.2.2-1.19.jar                                              
radiantgear-forge-2.0.1+1.19.2.jar                                   
Raided-1.19.2-0.1.3.jar                                              
randomvillagenames-1.19.2-3.2.jar                                    
RapidLeafDecay-1.19.2-2.0.2.jar                                      
Reblured-1.19.1-1.2.0.jar                                            
rechiseled-1.0.12a-forge-mc1.19.jar                                  
relics-1.19.2-0.4.2.2.jar                                            
repurposed_structures_forge-6.3.18+1.19.2.jar                        
resourcefullib-forge-1.19.2-1.1.23.jar                               
respawnobelisks-1.2-all.jar                                          
respiteful-1.19.2-1.0.0.jar                                          
rhino-forge-1902.2.2-build.264.jar                                   
roamers_v1.4.jar                                                     
RootsClassic-1.19.2-1.1.35.jar                                       
RoughlyEnoughItems-9.1.595.jar                                       
rpggods-19.2.2.jar                                                   
RpgSkillable-forge-1.19.2-1.1.1.jar                                  
rubidium-0.6.2.jar                                                   
Runelic-Forge-1.19.2-14.1.4.jar                                      
sanguis 1.1.0 1.19.2.jar                                             
saturn-mc1.19.2-0.0.1.jar                                            
ScalingHealth-1.19.2-7.0.0+6.jar                                     
seals-1.19.2-3.0.3.jar                                               
seamless_loading_screen-1.19.2-4.0.1.jar                             
seasonhud-1.19.2-1.4.8.jar                                           
seasontweaks-1.19.2-1.0.1.jar                                        
sereneseasonfix-1.19.2-1.0.7.jar                                     
SereneSeasons-1.19.2-8.1.0.24.jar                                    
ShieldExpansion-1.19.2-1.1.5.jar                                     
ShoulderSurfing-Forge-1.19.2-2.3.0.jar                               
silent-lib-1.19.2-7.0.3.jar                                          
SimpleDiscordRichPresence-forge-3.0.4-build.27+mc1.19.2.jar          
SkyVillages-1.0.1-1.19-forge-release.jar                             
sleep_tight-1.19.2-1.0.9.jar                                         
SmartBrainLib-forge-1.19.2-1.8.1.jar                                 
smoothboot(reloaded)-mc1.19.2-0.0.2.jar                              
soundphysics-forge-1.19.2-1.0.18.jar                                 
spark-1.10.34-forge.jar                                              
spelunkery-1.19.2-0.1.13-forge.jar                                   
spiderstpo-1.19.2-2.0.4.jar                                          
starbunclemania-1.19.2-1.0.5.4.jar                                   
starlight-1.1.1+forge.cf5b10b.jar                                    
Structory_1.19.3_v1.3.1a.jar                                         
Structory_Towers_1.19.3_v1.0.2.jar                                   
structureessentials-1.19.2-2.3.jar                                   
structure_gel-1.19.2-2.7.1.jar                                       
StylishEffects-v4.3.2-1.19.2-Forge.jar                               
sullysmod-2.3.1-beta.jar                                             
supermartijn642configlib-1.1.6b-forge-mc1.19.jar                     
supermartijn642corelib-1.1.5-forge-mc1.19.jar                        
supplementaries-1.19.2-2.2.58.jar                                    
swashbucklers2.4 1.19.jar                                            
takesapillage-1.0.3-1.19.2.jar                                       
tellme-forge-1.19.2-0.10.0.jar                                       
TerraBlender-forge-1.19.2-2.0.1.128.jar                              
Terralith_1.19.3_v2.3.7b.jar                                         
tetra-1.19.2-5.0.2.jar                                               
tetratic-combat-1.19-2.6.jar                                         
The_Undergarden-1.19.2-0.8.3.jar                                     
toomanyglyphs-1.19.2-2.2.45.12185.jar                                
Totemic-forge-1.19.2-0.12.2.jar                                      
Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar                           
TrampleStopper-3.8.1-build.35+mc1.19.2.jar                           
TravelersTitles-1.19.2-Forge-3.1.2.jar                               
TreeChop-1.19.2-forge-0.17.8a.jar                                    
trolls-0.5.jar                                                       
twilightforest-1.19.2-4.2.1518-universal.jar                         
UndeadUnleashed-1.0.1-1.19.2.jar                                     
Undergarden-Tetra Patch-1.3.2-1.19.2.jar                             
UndergroundVillages-1.19-1.1.1.jar                                   
unidentifiedenchantments-1.0.13.jar                                  
valhelsia_core-forge-1.19.2-0.5.0.jar                                
valhelsia_furniture-forge-1.19.2-1.0.2.jar                           
valhelsia_structures-forge-1.19.2-1.0.2.jar                          
vanilla_animations-1.19.2-0.0.2-alpha.jar                            
Villager Comfort-1.19.2-1.0.0.jar                                    
villagernames-1.19.2-5.2.jar                                         
villagespawnpoint-1.19.2-4.0.jar                                     
vinery-1.19.2-1.1.1.jar                                              
vmh-1.1.6-1.19.2.jar                                                 
voicechat-forge-1.19.2-2.3.28.jar                                    
Wabi-Sabi-Structures-1.1.2-Forge.jar                                 
waystones-forge-1.19.2-11.3.1.jar                                    
WorldPreGenerator-1.19.2-3.0.1.jar                                   
xlpackets-1.18.2-2.1.jar                                             
YungsApi-1.19.2-Forge-3.8.9.jar                                      
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar                      
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar                           
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar                         
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar                     
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar                          
YungsBridges-1.19.2-Forge-3.1.0.jar                                  
YungsExtras-1.19.2-Forge-3.1.0.jar                                   

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

```java
"Server thread" #285 prio=5 os_prio=0 cpu=105843.75ms elapsed=5501.46s tid=0x000001a1ade2b380 nid=0x8e24 runnable  [0x000000579135d000]
   java.lang.Thread.State: RUNNABLE
        at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap.get(it.unimi.dsi.fastutil@8.5.6/Object2ObjectOpenHashMap.java:352)
        at it.unimi.dsi.fastutil.objects.Object2ObjectFunctions$SynchronizedFunction.get(it.unimi.dsi.fastutil@8.5.6/Object2ObjectFunctions.java:215)
        - locked <0x00000005182693b8> (a it.unimi.dsi.fastutil.objects.Object2ObjectMaps$SynchronizedMap)
        at net.minecraft.world.entity.Entity.pehkui_getScaleData(minecraft@1.19.2/Entity.java:9356)
        at virtuoel.pehkui.api.ScaleType.getScaleData(pehkui@3.7.0+1.19.2-forge/ScaleType.java:36)
        at virtuoel.pehkui.util.ScaleUtils.getTypedScale(pehkui@3.7.0+1.19.2-forge/ScaleUtils.java:616)
        at virtuoel.pehkui.util.ScaleUtils.getInteractionBoxHeightScale(pehkui@3.7.0+1.19.2-forge/ScaleUtils.java:416)
        at virtuoel.pehkui.util.ScaleUtils.getInteractionBoxHeightScale(pehkui@3.7.0+1.19.2-forge/ScaleUtils.java:411)
        at net.minecraft.world.level.entity.EntitySection.redirect$cdg000$pehkui$forEach$getBoundingBox(minecraft@1.19.2/EntitySection.java:1027)
        at net.minecraft.world.level.entity.EntitySection.m_188352_(minecraft@1.19.2/EntitySection.java:34)
        at net.minecraft.world.level.entity.EntitySectionStorage.m_188365_(minecraft@1.19.2/EntitySectionStorage.java:120)
        at net.minecraft.world.level.entity.EntitySectionStorage$$Lambda$53205/0x0000000805b5edf8.accept(minecraft@1.19.2/Unknown Source)
        at net.minecraft.world.level.entity.EntitySectionStorage.consumeSection(minecraft@1.19.2/EntitySectionStorage.java:1081)
        at net.minecraft.world.level.entity.EntitySectionStorage.forEachInColumn(minecraft@1.19.2/EntitySectionStorage.java:1070)
        at net.minecraft.world.level.entity.EntitySectionStorage.handler$dgp000$forEachInBox(minecraft@1.19.2/EntitySectionStorage.java:1057)
        at net.minecraft.world.level.entity.EntitySectionStorage.m_188362_(minecraft@1.19.2/EntitySectionStorage.java:54)
        at net.minecraft.world.level.entity.EntitySectionStorage.m_156890_(minecraft@1.19.2/EntitySectionStorage.java:120)
        at net.minecraft.world.level.entity.LevelEntityGetterAdapter.m_142232_(minecraft@1.19.2/LevelEntityGetterAdapter.java:42)
        at net.minecraft.world.level.Level.m_6249_(minecraft@1.19.2/Level.java:588)
        at net.minecraft.world.entity.projectile.ProjectileUtil.m_150175_(minecraft@1.19.2/ProjectileUtil.java:87)
        at net.minecraft.world.entity.projectile.ProjectileUtil.m_37304_(minecraft@1.19.2/ProjectileUtil.java:79)
        at net.minecraft.world.entity.projectile.AbstractArrow.m_6351_(minecraft@1.19.2/AbstractArrow.java:420)
        at net.minecraft.world.entity.projectile.AbstractArrow.m_8119_(minecraft@1.19.2/AbstractArrow.java:174)
        at net.minecraft.world.entity.projectile.Arrow.m_8119_(minecraft@1.19.2/Arrow.java:104)
        at net.minecraft.server.level.ServerLevel$$Lambda$53141/0x0000000805b3dcb8.accept(minecraft@1.19.2/Unknown Source)
        at net.minecraft.server.level.ServerLevel.track(minecraft@1.19.2/ServerLevel.java:9240)
        at net.minecraft.server.level.ServerLevel.redirect$ejh000$onTickNonPassenger(minecraft@1.19.2/ServerLevel.java:9256)
        at net.minecraft.server.level.ServerLevel.m_8647_(minecraft@1.19.2/ServerLevel.java:658)
        at net.minecraft.server.level.ServerLevel$$Lambda$53139/0x0000000805b3d638.accept(minecraft@1.19.2/Unknown Source)
        at net.minecraft.world.level.Level.m_46653_(minecraft@1.19.2/Level.java:457)
        at net.minecraft.server.level.ServerLevel.m_184063_(minecraft@1.19.2/ServerLevel.java:323)
        at net.minecraft.server.level.ServerLevel$$Lambda$52990/0x0000000805b0f638.accept(minecraft@1.19.2/Unknown Source)
        at net.minecraft.world.level.entity.EntityTickList.m_156910_(minecraft@1.19.2/EntityTickList.java:54)
        at net.minecraft.server.level.ServerLevel.m_8793_(minecraft@1.19.2/ServerLevel.java:303)
        at net.minecraft.server.MinecraftServer.m_5703_(minecraft@1.19.2/MinecraftServer.java:866)
        at net.minecraft.server.MinecraftServer.m_5705_(minecraft@1.19.2/MinecraftServer.java:806)
        at net.minecraft.client.server.IntegratedServer.m_5705_(minecraft@1.19.2/IntegratedServer.java:84)
        at net.minecraft.server.MinecraftServer.m_130011_(minecraft@1.19.2/MinecraftServer.java:654)
        at net.minecraft.server.MinecraftServer.m_206580_(minecraft@1.19.2/MinecraftServer.java:244)
        at net.minecraft.server.MinecraftServer$$Lambda$52044/0x00000008059e8000.run(minecraft@1.19.2/Unknown Source)
        at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)

   Locked ownable synchronizers:
        - None
```

**Comment by Virtuoel** [comment]
Your log appears to only be a partial log. Please post the full contents. With watchdog crashes there's typically a non-Pehkui cause, e.g. an excessive amount of entities, which I may be able to figure out from the full log.

**Comment by Virtuoel** [comment]
With hangs or watchdog crashes there's typically a non-Pehkui cause, e.g. an excessive amount of entities. If the server were to have crashed, I may be able to figure out the cause from that kind of log. Can you let me know what `max-tick-time` is set to in your `server.properties`?
