### ISSUE TITLE
hitboxes, and portals. [bug?] (game version is: 1.19.2)

### ISSUE THREAD

**Issue by EllaTheIceQueen** [Virtuoel/Pehkui#387]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.14

### Fabric API version

0.75.1

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I have noticed that because of something with pehkui, the hit boxes need to touch the portal blocks themselves, this breaks every single kind of iron portal based farm. I was wondering if this was a bug, or intentional. since I can no longer progress without this being fixed.
examples:
![image](https://user-images.githubusercontent.com/128281501/226162891-c6cb9297-211c-41de-9581-e93673d60e53.png)
![image](https://user-images.githubusercontent.com/128281501/226162895-78755c4c-6f42-4955-968f-02f61bff0afb.png)

### Full list of installed mods and their version numbers
![image](https://user-images.githubusercontent.com/128281501/226163307-e863ba14-3957-4d40-a52a-8d7222e5ce21.png)
![image](https://user-images.githubusercontent.com/128281501/226163309-c64d5dbf-100c-4ca2-aa83-64e231bda544.png)

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
This is a feature, not a bug. To disable it, you can set `accurateNetherPortals` in the config to `false` instead of `true`.
