### ISSUE TITLE
[Bug]: Player scale staying the same once going through differently sized portals.

### ISSUE THREAD

**Issue by dragin1356** [Virtuoel/Pehkui#388]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

36.2.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I made two differently sized portals, walked through the bigger one to come out in the smaller one (expected to come out smaller e.g: scale = 1:0 --> scale = 0.5) And the game shifted my height to stay 2 blocks tall.  I played this mod before and it didn't shift my height.

### Full list of installed mods and their version numbers

Pehkui: 2.0.0+1.16.5
Immersive Portals: 0.14

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
If I remember correctly, the Forge version of Immersive Portals for 1.16.5 does not have compatibility with Pehkui. I think the Forge versions of Immersive Portals got Pehkui compat starting in 1.18.2? The Fabric ones have compat in 1.16.5 and above though.
