### ISSUE TITLE
Player skin helmet layer not showing when shrunken?

### ISSUE THREAD

**Issue by SnazzyGator** [Virtuoel/Pehkui#39]
Playing a modded server with Origins and most of the popular expansion mods for it; the helmet layer doesn't render on the playermodel for anyone on the server, though sometimes it'll show only for the shrunken player themselves. Toggling the skin layers does nothing, there's no error in the console or logs for it either.

Minecraft version: 1.16.5
Pehkui version: 1.7.1 21w03a
Origins version: 0.5.1
Fabric version: 0.6.1.51
Fabric API version: 0.31.0

**Comment by Virtuoel** [comment]
My guess is you're using the Inchling from Extra Origins? If so, this is an issue on their end.
