### ISSUE TITLE
[Crash] 1.19.2 Server and Client

### ISSUE THREAD

**Issue by CantWeAllDisagree** [Virtuoel/Pehkui#390]
### Minecraft version(s)

1.19.2

### Mod loader

Quilt

### Mod loader version

Quilt 0.18.6

### Fabric API version

[1.19.2] QFAPI 4.0.0-beta.29 and QSL 3.0.0-beta.29

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong?

Crashing with newest Pehkui-3.7.1+1.14.4-1.19.4

Downgrading to Pehkui-3.7.0 causes no issues.

Same error was reproducible on client.

https://pastebin.com/5BdaRPnL

**Comment by Sunconure11** [comment]
Having the same error.

https://pastebin.com/WcnzjW18

@Virtuoel
