### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by SGZ-Creations** [Virtuoel/Pehkui#391]
### Minecraft version(s)

1.19.2

### Minecraft version details

1.19.2

### Mod loader

Forge

### Mod loader version

Forge 43.2.7

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong?

![image](https://user-images.githubusercontent.com/59801736/227973683-23a64644-b1f2-4a2b-afbd-74adda8ee58d.png)
Just pressing play caused crash

[main/FATAL]: Mixin apply failed pehkui.mixins.json:compat116plus.compat1193minus.LivingEntityMixin -> net.minecraft.world.entity.LivingEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyConstant annotation on pehkui$updateLimbs$limbDistance could not find any targets matching 'updateLimbs(Lnet/minecraft/entity/LivingEntity;Z)V' in net.minecraft.world.entity.LivingEntity. Using refmap Pehkui-refmap.json [PREINJECT Applicator Phase -> pehkui.mixins.json:compat116plus.compat1193minus.LivingEntityMixin -> Prepare Injections ->  -> constant$bhk000$pehkui$updateLimbs$limbDistance(F)F -> Parse]

### Full list of installed mods and their version numbers

ad_astra-forge-1.19.2-1.12.6.jar
Ad-Astra-Giselle-Addon-forge-1.19.2-1.13.jar
AI-Improvements-1.19.2-0.5.2.jar
AkashicTome-1.6-23.jar
alloyed-1.19.2-v1.5.jar
AllTheCompressed-1.19.2-2.0.0.jar
allthemodium-2.1.6-1.19.2-43.1.1.jar
alltheores-2.0.2-1.19.2-43.1.3.jar
almostunified-forge-1.19.2-0.3.6.jar
AngelRing2-1.19.2-2.1.5.jar
Apotheosis-1.19.2-6.1.5.jar
appleskin-forge-mc1.19-2.4.2.jar
architectury-6.5.69-forge.jar
ars_nouveau-1.19.2-3.12.3.jar
AttributeFix-Forge-1.19.2-17.2.6.jar
AutoRegLib-1.8.2-55.jar
balm-forge-1.19.2-4.5.6.jar
balm-forge-1.19.2-4.5.7.jar
baubley-heart-canisters-1.19.2-1.3.0.jar
BetterAdvancements-1.19.2-0.2.2.142.jar
BetterF3-4.0.0-Forge-1.19.2.jar
biggerreactors-1.19.2-0.6.0-beta.6.1.jar
Bookshelf-Forge-1.19.2-16.2.18.jar
BotanyPots-Forge-1.19.2-9.0.28.jar
BotanyPotsTiers-Forge-1.19.2-3.3.2.jar
BotanyTrees-Forge-1.19.2-5.0.4.jar
botarium-forge-1.19.2-1.8.2.jar
cabletiers-1.19.2-0.5471.jar
caelus-forge-1.19.2-3.0.0.6.jar
chipped-forge-1.19.2-2.1.3.jar
cloth-config-8.2.88-forge.jar
Clumps-forge-1.19.2-9.0.0+14.jar
CodeChickenLib-1.19.2-4.3.1.481-universal.jar
cofh_core-1.19.2-10.2.1.40.jar
CommonCapabilities-1.19.2-2.9.0.jar
configured-2.0.1-1.19.2.jar
constructionwand-1.19.2-2.10.jar
Controlling-forge-1.19.2-10.0+7.jar
cookingforblockheads-forge-1.19.2-13.3.1.jar
craftingtweaks-forge-1.19-15.1.6.jar
crashutilities-6.2.jar
create_enchantment_industry-1.19.2-for-create-0.5.0.i-1.1.14.jar
create-1.19.2-0.5.0.i.jar
createaddition-1.19.2-20230315b.jar
createbigcannons-1.19.2-beta-0.5.b.jar
create-stuff-additions1.19.2_v2.0.2b.jar
creativecrafter-1.19.2-1.0.jar
creativewirelesstransmitter-1.19.2-1.2.jar
CTM-1.19.2-1.1.6+8.jar
Cucumber-1.19.2-6.0.6.jar
culinaryconstruct-forge-5.0.0+1.19.2.jar
curios-forge-1.19.2-5.1.3.0.jar
Cyclic-1.19.2-1.7.14.jar
CyclopsCore-1.19.2-1.18.2.jar
DarkModeEverywhere-1.19.1-1.0.3.jar
DarkUtilities-Forge-1.19.2-13.1.7.jar
deeperdarker-forge-1.1.6-forge.jar
DungeonCrawl-1.19-2.3.12.jar
EdivadLib-1.19.2-1.2.0.jar
elevatorid-1.19.2-1.8.9.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
enderchests-forge-1.19.0-1.10.1.01.jar
EnderStorage-1.19.2-2.10.1.181-universal.jar
endertanks-forge-1.19.0-1.12.1.02.jar
EvilCraft-1.19.2-1.2.16.jar
ExtendedCrafting-1.19.2-5.1.5.jar
ExtraStorage-1.19.2-3.0.1.jar
FarmersDelight-1.19-1.2.0.jar
FastLeafDecay-30.jar
flatbedrock-forge-2.0.0-build.14+mc1.19.2.jar
FluxNetworks-1.19.2-7.1.3.12.jar
flywheel-forge-1.19.2-0.6.8.a.jar
forbidden_arcanus-1.19.2-2.1.2.jar
frozen_delight_1.3.1_forge_1.19.2.jar
frozenup-1.19.2-2.1.2-forge.jar
ftbbackups2-forge-1.19.2-1.0.18.jar
ftb-chunks-forge-1902.3.18-build.248.jar
ftb-essentials-1902.1.10-build.47.jar
ftb-library-forge-1902.3.16-build.193.jar
ftb-teams-forge-1902.2.12-build.95.jar
ftb-ultimine-forge-1902.4.0-build.77.jar
geckolib-forge-1.19-3.1.40.jar
ImmersiveEngineering-1.19.2-9.2.0-162.jar
industrial-foregoing-1.19.2-3.3.2.3-5.jar
integrated_api_forge-1.2.7+1.19.2.jar
integrated_stronghold_forge-1.0.1+1.19.2.jar
IntegratedCrafting-1.19.2-1.1.1.jar
IntegratedDynamics-1.19.2-1.16.2.jar
integratednbt-1.19.2-1.6.0.jar
IntegratedREST-1.19.2-1.1.8.jar
IntegratedTerminals-1.19.2-1.4.5.jar
IntegratedTunnels-1.19.2-1.8.18.jar
ironchest-1.19.2-14.2.7.jar
ironfurnaces-1.19.2-3.6.5.jar
jei-1.19.2-forge-11.6.0.1013.jar
jeimultiblocks-1.19.2-0.0.3.jar
jmi-forge-1.19.2-0.13-33.jar
journeymap-1.19.2-5.9.4-forge.jar
JustEnoughResources-1.19.2-1.2.2.200.jar
kotlinforforge-3.11.0-all.jar
kubejsarsnoveau-1.0.1.jar
kubejsbotanypots-1.0-SNAPSHOT.jar
kubejs-create-forge-1902.1.1-build.32.jar
kubejs-forge-1902.6.0-build.142.jar
kubejspowah-1.0.jar
kubejsprojecte-1.0.jar
kubejs-thermal-1902.1.6-build.22.jar
laserio-1.5.2.jar
libIPN-forge-1.19-2.0.4.jar
lootjs-forge-1.19.2-2.7.9.jar
lootr-1.19-0.3.22.59.jar
mcjtylib-1.19-7.1.5.jar
Mekanism-1.19.2-10.3.8.477.jar
MekanismGenerators-1.19.2-10.3.8.477.jar
MekanismTools-1.19.2-10.3.8.477.jar
metalbarrels-1.19.2-5.0.1.jar
mob_grinding_utils-1.19.2-0.4.47.jar
moonlight-1.19.2-2.2.27-forge.jar
moredragoneggs-3.2.jar
MouseTweaks-forge-mc1.19-2.23.jar
MysticalAgradditions-1.19.2-6.0.2.jar
MysticalAgriculture-1.19.2-6.0.8.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
netherportalfix-forge-1.19-10.0.1.jar
NoChatReports-FORGE-1.19.2-v1.5.1.jar
nomowanderer-1.19.2_1.3.6.jar
nutritionalbalance-1.19.2-4.1.4.jar
oculus-flywheel-compat-1.19.2-0.1.6-ALPHA.jar
oculus-mc1.19.2-1.2.8a.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar
origins-forge-1.19.2-1.5.0.6-all.jar
origins-plus-plus-2.0-forge.jar
PackMenu-1.19.2-5.1.0.jar
Patchouli-1.19.2-77.jar
Pehkui+Resizer+V2.1.0___1.19.2.jar
Pehkui-3.7.0+1.19.2-forge.jar
phosphophyllite-1.19.2-0.6.0-beta.7.jar
PigPen-Forge-1.19.2-11.1.2.jar
pipez-1.19.2-1.0.1.jar
Placebo-1.19.2-7.1.7.jar
polylib-forge-1900.0.2-build.42.jar
polymorph-forge-0.46.1+1.19.2.jar
ponderjs-1.19.2-1.1.11.jar
Powah-4.0.6.jar
ProjectE-1.19.2-PE1.0.1B.jar
ProjectExpansion-1.19.2-1.0.8.jar
Quark-3.4-394.jar
quartz-1.19.2-0.1.0-beta.2.1.jar
rechiseled-1.0.12a-forge-mc1.19.jar
refinedcooking-3.0.3.jar
refinedstorage-1.11.5.jar
refinedstorageaddons-0.9.0.jar
ResourceChickens-1.19.2-1.1.jar
resourcefulbees-1.0.0-alpha.15.jar
resourcefulconfig-forge-1.19.2-1.0.20.jar
resourcefullib-forge-1.19.2-1.1.23.jar
rftoolsbase-1.19.1-4.1.5.jar
rftoolsbuilder-1.19.1-5.2.3.jar
rhino-forge-1902.2.2-build.264.jar
RSInfinityBooster-1.19.2-3.0+27.jar
rsrequestify-2.3.0.jar
rubidium-0.6.2a.jar
Runelic-Forge-1.19.2-14.1.4.jar
sebastrnlib-2.0.2.jar
shetiphiancore-forge-1.19.0-3.11.3.01.jar
shutupexperimentalsettings-1.0.5.jar
sophisticatedbackpacks-1.19.2-3.18.40.779.jar
sophisticatedcore-1.19.2-0.5.38.203.jar
spark-1.10.34-forge.jar
spirit-forge-1.19.2-2.2.4.jar
Steam_Rails-1.19.2-1.1.1.jar
StorageDrawers-1.19-11.1.2.jar
summoningrituals-1.19.2-2.0.4.jar
supermartijn642configlib-1.1.6b-forge-mc1.19.jar
supermartijn642corelib-1.1.6-forge-mc1.19.jar
supplementaries-1.19.2-2.2.64.jar
TerraBlender-forge-1.19.2-2.0.1.128.jar
theoneprobe-1.19-6.2.2.jar
thermal_cultivation-1.19.2-10.2.0.17.jar
thermal_dynamics-1.19.2-10.2.1b.14.jar
thermal_expansion-1.19.2-10.2.0.21.jar
thermal_foundation-1.19.2-10.2.0.47.jar
thermal_innovation-1.19.2-10.2.0.18.jar
thermal_integration-1.19.2-10.2.0.17.jar
thermal_locomotion-1.19.2-10.2.0.14.jar
titanium-1.19.2-3.7.2-26.jar
tombstone-8.2.6-1.19.2.jar
torchmaster-19.2.0.jar
universalgrid-1.19.2-1.033.jar
UniversalTrading_Forge_1.19.2.jar
upgradedcore-1.19.2-4.1.0.1-release.jar
upgradednetherite_ultimate-1.19.2-4.1.0.3-release.jar
upgradednetherite-1.19.2-5.1.0.6-release.jar
valhelsia_core-forge-1.19.2-0.5.0.jar
voidtotem-forge-1.19.2-2.1.0.jar
xlpackets-1.18.2-2.1.jar
ZeroCore2-1.19.2-2.1.32.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)
[latest.log](https://github.com/Virtuoel/Pehkui/files/11079880/latest.log)

The crash happened after updating mod to to Pehkui-3.7.1 from 3.7.0

**Comment by SGZ-Creations** [comment]
what release version would that be?

**Comment by Virtuoel** [comment]
Shoud now be resolved as of the 3.7.2 release.

**Comment by SGZ-Creations** [comment]
Awsome Thanks
