### ISSUE TITLE
Incompatibility with Fabrication

### ISSUE THREAD

**Issue by Lucipo** [Virtuoel/Pehkui#40]
No idea why but Fabrication v1.3.3 on Fabric 1.16.5, changing your size and then opening your inventory to a window where the avatar/player renders will reset your size but only client-side, so jumping and moving bugs out and may randomly kill you. 

This only happens if Omniscient Player Config is turned on
![image](https://user-images.githubusercontent.com/36358294/109617544-253c7b00-7afc-11eb-9123-309a6d13230c.png)
turned off in the screenshot of course

it entirely breaks the mod please fix :)

**Comment by Virtuoel** [comment]
Fixed on Fabrication's end. Once they release a new version this should work properly.
