### ISSUE TITLE
[Bug]: "distance=.." doesn't work

### ISSUE THREAD

**Issue by dooble-22** [Virtuoel/Pehkui#403]
### Minecraft version(s)

1.19.4

### Mod loader

Forge

### Mod loader version

1.19.4-forge-45.0.40

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

when using a command like "execute as @e[distance=..7]" on an enlarged mob, the affected area wasn't expanded, so it only affects a small area of the mob, likely where it's original detection was.

### Full list of installed mods and their version numbers

Pehkui
NoChatReports

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
The `distance` selector only detects if the center of an entity is in range and does not take the hitbox size into account. For detecting an entity's hitbox, the `dx=, dy=, dz= ` selectors may be more useful.
