### ISSUE TITLE
[Bug]: Untitled bug report

### ISSUE THREAD

**Issue by mastrerfail** [Virtuoel/Pehkui#407]
### Minecraft version(s)

1.19.4

### Mod loader

Fabric

### Mod loader version

fabric-server-mc.1.19.4-loader.0.14.19-launcher.0.11.2.jar

### Fabric API version

fabric-api-0.79.0+1.19.4.jar

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

When I type /scale no option labeled set is showing, and typing it doesnt work either
![2023-05-04_19 54 24](https://user-images.githubusercontent.com/81631578/236288492-5959141c-437b-43bc-8676-488e2e894dcd.png)

### Full list of installed mods and their version numbers

-armor-stand-editor-2.1.0+1.19.4-rc2
-cloth-config-10.0.96-fabric
-essential_commands-0.33.0-mc1.19.4
-fabric-api-0.79.0+1.19.4
-headindex-1.1.1
-htm-1.1.8
-lithium-fabric-mc1.19.4-0.11.1
-mostructures-1.4.3+1.19.4
-Pehkui-Mod-Fabric-Quilt-1.19.4
-repurposed_structures-6.3.25+1.19.4-quilt
-starlight-1.1.1+fabric.ae22326
-Terralith_1.19.4_v2.3.7b

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by mastrerfail** [comment]
So I Updated the fabric API to 0.80.0 but nothing changed sadly

**Comment by Virtuoel** [comment]
Please let me know if you still have this issue after removing `essential_commands`.
