### ISSUE TITLE
[Bug]: Specifying `fabricloader` in mod.json causes Quilt to be unable to load

### ISSUE THREAD

**Issue by Merith-TK** [Virtuoel/Pehkui#409]
### Minecraft version(s)

1.19.4

### Minecraft version details

https://modrinth.com/mod/pehkui/version/3.7.3+1.14.4-1.20

### Mod loader

Quilt

### Mod loader version

N/A

### Fabric API version

N/A

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

Tried to start server after updating mods, 
Quilt said could not find `fabricloader` dependancy

### Full list of installed mods and their version numbers

N/A

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

---- Quilt Loader: Failed to load ----
Date/Time: 2023/05/07 01:26:33.8337

-- Error 1 --

Pehkui requires version [0.14.19, ∞) of fabricloader, which is missing!
Pehkui is loaded from ./mods/Pehkui-3.7.3+1.14.4-1.20.jar

**Comment by Virtuoel** [comment]
Your Quilt Loader version appears to be out of date. Try rerunning the Quilt installer and picking a newer version of Quilt Loader, e.g. 0.18.10 or above.
