### ISSUE TITLE
Desync between clients and server with Fabrication

### ISSUE THREAD

**Issue by CammiePone** [Virtuoel/Pehkui#41]
So with the latest version of Pehkui, we're seeing that sometimes the player just randomly becomes normal sized again, and other players see the shrunken or larger player as normal sized, including the hitboxes.

**Comment by Virtuoel** [comment]
Can you provide more info, e.g. MC, Fabric Loader, and Fabric API versions, as well as versions of any other mods that are installed?

**Comment by Lucipo** [comment]
This happened to me with Fabrication Omniscient player on, if it helps

**Comment by CammiePone** [comment]
**Minecraft:** 1.16.5
**Fabric Loader:**  0.11.1
**Fabric API:** 0.31.0+1.16

Other mods we have are as follows (all are updated to their latest version according to GDLauncher, minus Starlight which is on 0.0.3):
Amecs
Angerable Patch
Anthropophagy
Antique Atlas
AppleSkin
Art of Alchemy: Memorium
Auth Me
BackSlot
Basic Materials
Draylar's Battle Towers
Bedspreads
Better Enchanted Books
Bewitchment
Biome Makeover
Blockus
BYG
Cammie's Wearable Backpacks
Camp Fires Cook Mobs
Carve My Pumpkin
Charcoal Block
Chat Heads
chatplus
Chest Cavity
Chicken Nerf
Cinderscapes
CleanCut
Cloth API
Colored Slime Blocks
Connectible Chains
Controlling
Door Couplings
Dark Loading Screen
Dracomelette
Dynamic Sound Filters
Extra Alchemy
Extra Origins
Fabric Language Scala
Fabric Language Kotlin
Fabrication
FallingTree
FastFurnace
Geckolib
Held Item Info
Here be no Dragons!
Hookshot
Horse Stats Vanilla
Hourai Elixir
Illuminations
Impersonate
Inventory Sorter
Invisible Frames
LambDynamicLights
LazyDFU
Lithium
Maelstrom Library
MAmbience
MinimalMenu
MixinTrace
Mo' Structures
Mobs Attempt Parkour
Mod Menu
Modify Drops API
Mojank Logo
Krypton
Netherite Horse Armor
No More Glowing Pots
No Player Labels
Nomad Books
Not Enough Crashes
Ok Zoomer
Origins
Origins: Classes
Overworld 2
ParadoxSlabs
Patchouli
Pling
Pride Lib
Rare Ice
Rat's Mischief
Realistic Fire Spread
Repurposed Structures
Requiem
Requiem: Pandemonium
Respawnable Pets
Roughly Enough Items
Roughly Enough Resources
Screenshot To Clipboard
Shulker Box Tooltip
Simple Voice Chat
Smooth Scrolling Everywhere
Snow Mercy
Sodium
Somnus API
Spellbound Enchantments
StairDoors
Starlight
Straw Dummy
Terrestria
This is Fine
Tom's Simple Storage Mod
Traverse
Trinkets
True Darkness
Upstream
Vangaurd
VehicleFix
Vertical Redstone
Voyager
YUNG's API
YUNG's Better Caves
YUNG's Better Mineshafts

**Comment by Virtuoel** [comment]
Ah, in that case this issue is likely #40. Once Fabrication releases the updated version the issue should be fixed.

**Comment by CammiePone** [comment]
Yea I disabled Omniscient Player and it appears to be fixed. Idk why the other guy deleted their message, but it seems that's specifically the issue.

**Comment by exaskye** [comment]
I just released v1.3.4 which includes unascribed/Fabrication#169 - sorry I took so long to finally release it.
