### ISSUE TITLE
pekhui and immersive portals 1.19.4 [Bug]: change fabric loader

### ISSUE THREAD

**Issue by omegaminetilles** [Virtuoel/Pehkui#424]
### Minecraft version(s)

1.19.4

### Mod loader

Fabric

### Mod loader version

0.14.17

### Fabric API version

0.74

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

brings me to fabric loader 

### Full list of installed mods and their version numbers

pehkui immersive portals fabric api

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.17 with version 0.14.21 or later.
	 - Replace mod 'Immersive Portals' (immersive_portals) 2.7.2 with any version that is compatible with:
		 - fabricloader, version 0.14.21 or later
		 - pehkui 0.0.0+forge
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.84.0+1.19.4 requires version 0.14.21 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.17!
	 - Mod 'Immersive Portals' (immersive_portals) 2.7.2 is incompatible with any version before 3.4.1 of mod 'Pehkui (Forge Version)' (pehkui), but a matching version is present: 0.0.0+forge!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by omegaminetilles** [comment]
sorry its forge version here Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.17 with version 0.14.21 or later.
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.84.0+1.19.4 requires version 0.14.21 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.17!
	 - Mod 'Pehkui' (pehkui) 3.7.3+1.14.4-1.20 requires version 0.14.19 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.17!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Virtuoel** [comment]
Your Fabric Loader version (0.14.17) is outdated. You'll need to rerun the Fabric installer and pick a newer version of Fabric Loader (0.14.21).
