### ISSUE TITLE
Game Crashes on load up 

### ISSUE THREAD

**Issue by Xvslife** [Virtuoel/Pehkui#432]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

Forge 1.20.1

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

I load it up and it crash!!

### Full list of installed mods and their version numbers

This one

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

Exit code 1

**Comment by purejosh** [comment]
"This one", really? What one? What version? You haven't included a crash report, and the rest of the info is entirely useless. How can you expect a developer to help you if you put zero effort into your report? Actually try, and you might have the issue looked at.
