### ISSUE TITLE
[Bug]: Portal based iron farms

### ISSUE THREAD

**Issue by Rozti17** [Virtuoel/Pehkui#436]
### Minecraft version(s)

1.20.1, 1.19.4, 1.19.3, 1.19.2

### Mod loader

Fabric

### Mod loader version

Fabric loader

### Fabric API version

Fabric api 0.86.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Portal based iron farms not really work, more precisely they spawn next to the portal or into the portal frame.
I tested all my mods what can cause this problem and when i turned off the pehkui mod (and the origins++, because its only compatible with pehkui) its solved it.

### Full list of installed mods and their version numbers

3dskinlayers-fabric-1.5.4-mc1.20.1.jar
advancementinfo-1.20-fabric0.83.0-1.4.jar
alternate-current-mc1.20-1.7.0.jar
appleskin-fabric-mc1.20-2.5.0.jar
balm-fabric-1.20-7.0.4.jar
BetterF3-7.0.1-Fabric-1.20.1.jar
bettermounthud-1.2.2.jar
BetterThirdPerson-Fabric-1.20-1.9.0.jar
bobby-5.0.0.jar
camerautils-1.20.1-1.0.4.jar
capes-1.5.2+1.20-fabric.jar
chat_heads-0.10.16-fabric-1.20.jar
CITResewn-1.1.3+1.20.jar
clickthrough-1.20-fabric0.83.0-0.4.1.jar
clienttweaks-fabric-1.20-11.0.0.jar
cloth-config-11.0.99-fabric.jar
Clumps-fabric-1.20.1-12.0.0.3.jar
completeconfig-2.4.0.jar
continuity-3.0.0-beta.2+1.20.jar
CreativeCore_FABRIC_v2.10.24_mc1.20.1.jar
dark-loading-screen-1.6.14.jar
diamondNuggets-fabric-1.3-1.20.x.jar
do-a-barrel-roll-3.0.1+1.20-fabric.jar
dynamic-fps-2.4.0.jar
eating-animation-1.9.4+1.20.jar
elytra-chestplate-swapper-1.3.0-MC1.20.jar
entityculling-fabric-1.6.2-mc1.20.jar
Essential-fabric_1-20-1.jar
fabric-api-0.86.0+1.20.1.jar
fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar
fastquit-3.0.0-beta.2+1.20+.jar
ferritecore-6.0.0-fabric.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
freecam-fabric-modrinth-1.2.1+1.20.jar
indium-1.0.21+mc1.20.1.jar
InventoryProfilesNext-fabric-1.20-1.10.6.jar
InvMove-1.20-0.8.4-Fabric.jar
iris-mc1.20-1.6.4.jar
ItemPhysicLite_FABRIC_v1.6.1_mc1.20.1.jar
krypton-0.2.3.jar
lambdynamiclights-2.3.1+1.20.1.jar
lazydfu-0.1.3.jar
libIPN-fabric-1.20-3.0.2.jar
litematica-fabric-1.20.1-0.15.0.jar
lithium-fabric-mc1.20.1-0.11.2.jar
make_bubbles_pop-0.1.1.jar
malilib-fabric-1.20.1-0.16.0.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
minihud-fabric-1.20.1-0.27.0.jar
modmenu-7.2.1.jar
morechathistory-1.19.1-1.1.1.jar
MouseTweaks-fabric-mc1.20-2.25.jar
NoChatReports-FABRIC-1.20.1-v2.2.1.jar
notenoughanimations-fabric-1.6.4-mc1.20.jar
open-parties-and-claims-fabric-1.20.1-0.19.0.jar
Origins-1.20.1-1.10.0.jar
origins-plus-plus-2.0.1.jar
Pehkui-3.7.7+1.14.4-1.20.1.jar
reeses_sodium_options-1.5.1+mc1.20-build.74.jar
replaymod-1.20.1-2.6.13.jar
shulkerboxtooltip-fabric-4.0.3+1.20.jar
sit-1.20-24.jar
smoke-suppression-1.0.16+MC1.20-1.20.1.jar
smoothswapping-0.9.2-1.20-fabric.jar
sodium-extra-0.4.23+mc1.20.1-build.106.jar
sodium-fabric-mc1.20-0.4.10+build.27.jar
splash_milk-2.1.0.jar
starlight-1.1.2+fabric.dbc156f.jar
toggleableitemframes-2.1.2-1.20.x.jar
tweakeroo-fabric-1.20.1-0.17.0.jar
voicechat-fabric-1.20.1-2.4.11.jar
worldedit-mod-7.2.15.jar
Xaeros_Minimap_23.5.0_Fabric_1.20.jar
XaerosWorldMap_1.30.6_Fabric_1.20.jar

### Did the problem cause the game to crash?

No.

**Comment by Virtuoel** [comment]
This can be disabled by going to Pehkui's config file and setting `accurateNetherPortals` to `false`.

**Comment by Rozti17** [comment]
> This can be disabled by going to Pehkui's config file and setting `accurateNetherPortals` to `false`.

Really thanks for the fast reply <3
