### ISSUE TITLE
/scale Freezes Game for 10 Minutes

### ISSUE THREAD

**Issue by TheyCallMeFatbird** [Virtuoel/Pehkui#438]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

0.14.22

### Fabric API version

0.76.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I was lagging just a little bit from playing around with the command, and I wanted to put my scale to 500. Nothing. Thought the game didn't realise I was sending the commands. So I sent It again. And Again. I could still move and do stuff. But then I was met with a blank screen. I decided to save the world and log back in, and then it just said "Loading Terrain..." it was softlocked. Now I can't access my world. What do I do?

### Full list of installed mods and their version numbers

Pehkui 3.7.5 1.19.2
Immersive Portals 2.3.1 1.19.2
sodium 0.4.4 1.19.2

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by TheyCallMeFatbird** [comment]
It also bricked* my game
_*I had to end it with Task Manager_

**Comment by Virtuoel** [comment]
For reference, a scale of 500 would make you just under 1000 blocks tall and 500 blocks wide. I'd be surprised if any computer could handle that.

Anyways, one workaround would be to go to another creative world, run the command `/scale debug delete_scale_data username YourUsernameHere`, then go back into the world where you were big and your scale should be reset.

**Comment by TheyCallMeFatbird** [comment]
Biggest Thanks to you, you saved literally more than 2 months of progress for me 😅

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
