### ISSUE TITLE
[Bug]: Crash due to villager ticks

### ISSUE THREAD

**Issue by nekorissu** [Virtuoel/Pehkui#449]
### Minecraft version(s)

1.19.2

### Mod loader

Forge

### Mod loader version

Forge: 43.2.21

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Crash happens both on the server/client (in case of single-player game)

The crash happens mostly when rendering/attempting to spawn villagers (server crash and/or single game crash), but sometimes other entities as well. 

I've tried compiling the mod from source/doing a downgrade and the error still appears. 
I found a post where someone wrote about a conflict with citadel (I tried removing it and the error still remains)

### Full list of installed mods and their version numbers

antiqueatlas-7.0.3-forge-mc1.19.2
Apoli-1.19.2-2.6.1
architectury-6.5.85-forge
armor-weight-1.19.2-1.0.1
AutoRegLib-1.8.2-55
balm-forge-1.19.2-4.5.7
better-end-2.1.6
better-nether-7.1.4
bettercombat-forge-1.7.1+1.19
bettervillage-forge-1.19.2-3.2.0
Bookshelf-Forge-1.19.2-16.3.20
BotanyPots-Forge-1.19.2-9.0.36
bushierflowers-0.0.2-1.19.2
caelus-forge-1.19.2-3.0.0.6
carpeted-1.19.2-1.4
clickthrough-forge-1.0
cloth-config-8.3.103-forge
collective-1.19.2-6.65
combatroll-forge-1.1.5+1.19
Connectible+Chains-forge-1.19.2-1.1.0
connectivity-1.19.2-4.5
cookingforblockheads-forge-1.19.2-13.3.2
create-1.19.2-0.5.1.c
createarmoryv0.6
createdeco-1.3.3-1.19.2
CreativeCore_FORGE_v2.9.4_mc1.19.2
crittersandcompanions-1.19.2-2.0.2
cupboard-1.19.2-1.8
curios-forge-1.19.2-5.1.4.1
DiagonalFences-v4.2.6-1.19.2-Forge
doapi-1.1.0b
doubledoors-1.19.2-5.0
DoubleSlabs-1.19-6.1.0
ecologics-forge-1.19.2-2.1.11
effective_fg-1.3.4
emotecraft-for-MC1.19.2-2.2.1-forge
EnhancedVisuals_FORGE_v1.5.9_mc1.19.2
EnigmaticLegacy-2.26.5
entityculling-forge-1.6.1-mc1.19.2
epicsamurai-0.0.16-1.19.2-forge
everycomp-1.19.2-2.5.5
fantasyfurniture-1.19.2-6.7.0
FarmersDelight-1.19.2-1.2.3
Fastload-Reforged-mc1.19.2-3.4.0
ferritecore-5.0.3-forge
furnish-23-forge
Galosphere-1.19.2-1.3.0-Forge
geckolib-forge-1.19-3.1.40
harvestwithease-1.19.2-6.0.1.4-final-forge
Iceberg-1.19.2-forge-1.1.4
illuminations-forge-1.19.2-1.10.9.20
immersive_weathering-1.19.2-1.2.10-forge
inventorio-1.19-forge-1.9.1
InventoryProfilesNext-forge-1.19-1.10.7
ItemPhysic_FORGE_v1.6.6_mc1.19.2
Jade-1.19.1-forge-8.8.1
kleeslabs-forge-1.19.2-12.3.0
konkrete_forge_1.6.1_MC_1.19-1.19.2
kotlinforforge-3.12.0-all
letsdo-vinery-forge-1.3.9
libIPN-forge-1.19-4.0.0
libraryferret-forge-1.19.2-4.0.0
mcw-bridges-2.1.1-mc1.19.2forge
midnightlib-forge-1.0.0
MOAdecor+ART+1.19.2
MOAdecor+COOKERY+1.19.2
moonlight-1.19.2-2.2.44-forge
moveboats-1.19.2-3.0
multibeds-forge-1.19.0-1.10.2.03
naturalist-forge-3.0.4-1.19.2
nekoration-1.19.2-1.8.1
origins-classes-forge-1.2.0
origins-forge-1.19.2-1.7.1.2-all
origins-plus-plus-2.1.1-forge   (required: Pehkui)
Patchouli-1.19.2-77
Pehkui-3.7.7+1.19.2-forge   (i tried from 3.6.3 to 3.7.8)
player-animation-lib-forge-1.0.2
pluto-mc1.19.2-0.0.9
PresenceFootsteps-1.19.2-1.6.4.1-forge
Prism-1.19.1-1.0.2
PuzzlesLib-v4.4.3-1.19.2-Forge
Quark-3.4-409
RegionsUnexploredForge-0.4.1_1+1.19.2
RoughlyEnoughItems-9.1.643
shetiphiancore-forge-1.19.0-3.11.3.04
SkyVillages-1.0.1-1.19-forge-release
smoothboot(reloaded)-mc1.19.2-0.0.2
soulfired-1.19.2-3.2.0.0-forge
soundphysics-forge-1.19.2-1.0.18
spiderstpo-1.19.2-2.0.4
TerraBlender-forge-1.19.2-2.0.1.166
Towns-and-Towers-v.1.10-_FORGE-1.19.2_
visuality-forge-2.0.2
voicechat-forge-1.19.2-2.4.21
xlpackets-1.18.2-2.1
YungsApi-1.19.2-Forge-3.8.9
YungsBetterDesertTemples-1.19.2-Forge-2.2.2
YungsBetterDungeons-1.19.2-Forge-3.2.2
YungsBetterMineshafts-1.19.2-Forge-3.2.0
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0
YungsBetterStrongholds-1.19.2-Forge-3.2.0
YungsBetterWitchHuts-1.19.2-Forge-2.1.0
YungsBridges-1.19.2-Forge-3.1.0
YungsExtras-1.19.2-Forge-3.1.0

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

I uploaded the crash log because the issue was too big (>65536 chars):
https://paste.ee/p/VJiEg

**Comment by Virtuoel** [comment]
Should now be resolved as of the 3.7.9 release.
