### ISSUE TITLE
[Bug]:Incompatibility with MC Dungeons Weapons

### ISSUE THREAD

**Issue by Jafooleryy** [Virtuoel/Pehkui#452]
### Minecraft version(s)

1.20.1

### Mod loader

Fabric

### Mod loader version

0.14.22

### Fabric API version

0.87.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

When both mc dungeon weapons and penkui are installed, I am using the latest version of both.

### Full list of installed mods and their version numbers

Fabric API - 0.87.0
Sodium - 0.5.2
Iris - 1.6.8
MC Dungeon Weapons - 8.0.3
Penkui - 3.7.8
Better Combat - 1.7.3

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Made some compatibility tweaks from my end in the 3.7.9 release, but definitely tricky to fix properly as both modify attack reach. Seems that mod also has compatibility code for when [ReachEntityAttributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes/) is installed, so I'd recommend [getting it](https://maven.jamieswhiteshirt.com/libs-release/com/jamieswhiteshirt/reach-entity-attributes/2.4.0/reach-entity-attributes-2.4.0.jar) or a mod that uses it, which should crash less when all three are present.
