### ISSUE TITLE
[Bug]: "requires fabric loader 0.14.17,∞"

### ISSUE THREAD

**Issue by beesul** [Virtuoel/Pehkui#453]
### Minecraft version(s)

1.19.2

### Mod loader

Fabric

### Mod loader version

Quilt: 0.18.1-beta41/Fabric: 0.14.12

### Fabric API version

0.76.1

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

as said in the title, it says "requires fabric loader 0.14.17,∞" whereas i have no idea what this version is, and cannot download it,

it isnt a crash issue, rather quilt warns this mod isn't compatible in this state, and its the only mod with an issue seemingly

### Full list of installed mods and their version numbers

3dskinlayers-fabric-1.5.2-mc1.19.1
AdaptiveTooltips-1.0.1-fabric-1.19.2
advancementinfo-1.19.1-fabric0.58.5-1.3.1
amecs-1.3.8+mc.1.19-rc2
animatica-0.5+1.19
antighost-1.19.1-fabric0.58.5-1.1.5
appleskin-fabric-mc1.19-2.4.1
architectury-6.5.85-fabric
bclib-2.1.7
better-end-2.1.6
BetterF3-4.0.0-Fabric-1.19.2
bettermounthud-1.2.0
better-nether-7.1.4
BetterPingDisplay-Fabric-1.19.2-1.1.1
Blanket Client tweaks-1.1.2
blast-1.10
Bookshelf-Fabric-1.19.2-16.3.20
boosted-brightness-2.1.2+1.19
borderless-mining-1.1.5+1.19
c2me-fabric-mc1.19.2-0.2.0+alpha.9.11
capes-1.5.2+1.19.2-fabric
cem-0.7.1
CITResewn-1.1.2+1.19.2
cloth-config-8.2.88-fabric
Clumps-fabric-1.19.2-9.0.0+14
colormatic-3.1.2+mc.1.19
continuity-2.0.1+1.19
ctov-3.2.5
cullleaves-fabric-3.0.1
CullLessLeaves-1.0.6
Debugify-2.8.0
deeperdarker-fabric-1.1.6-fabric
draggable-resource-packs-mc1.19-3.0.1+build.9
dynamic-fps-2.2.0
e4mc-4.0.1+1.19.4-fabric
Easeify-1.19.2-fabric-1.1.0
effective-2.1.1+1.19.2
enchancement-1.19-14 <---- the mod that needs pekhui
EnchantmentDescriptions-Fabric-1.19.2-13.0.16
enhanced_attack_indicator-1.0.4+1.19
enhancedblockentities-0.7.2+1.19.2
entity_model_features_fabric_1.19.2-1.0.1
entity_texture_features_fabric_1.19.2-4.5.1
entityculling-fabric-1.5.2-mc1.19
Essential Dependencies
Essential-fabric_1-19-2
extraorigins-1.19-2
fabric-api-0.76.1+1.19.2
fabrication-3.1.4+1.19
fabric-carpet-1.19.2-1.4.84+v221018
fabric-chunkpregen-0.3.5
fabric-language-kotlin-1.9.0+kotlin.1.8.0
fabricskyboxes-0.6.1+mc1.19.2
fallingleaves-1.13.0+1.19.2
Fastload+1.19.2-2.6.10
ferritecore-5.0.3-fabric
FpsReducer2-fabric-1.19.2-2.1
freecam-1.1.6+1.19
fsb-interop-1.1.3+mc1.19.2-build.25
geckolib-quilt-1.19-3.1.41
horse-stats-vanilla-4.2.2
illuminations-1.10.11
impaled-1.1.4
indium-1.0.9+mc1.19.2
inspecio-1.6.0+1.19
iris-mc1.19.2-1.5.0
item-model-fix-1.0.3+1.19
kappa-3.0.3
krypton-0.2.1
lambdabettergrass-1.3.0+1.19
lambdynamiclights-2.2.0+1.19.2
language-reload-1.5.4+1.19.2
lazydfu-0.1.3
letmedespawn-1.18.x-1.19.x-fabric-1.0.2
lithium-fabric-mc1.19.2-0.10.4
lucium-1.1
main-menu-credits-1.1.1
memoryleakfix-1.19.1-0.7.0
mixintrace-1.1.1+1.17
modelfix-1.8-fabric
modmenu-4.1.2
moonlight-1.19.2-2.2.45-fabric
moreculling-1.19.1-0.14.0
NoChatReports-FABRIC-1.19.2-v1.13.12
notenoughanimations-fabric-1.6.2-mc1.19.2
optigui-1.1.6
Origins-1.19.2-1.7.1
Pehkui-3.7.8+1.14.4-1.20.1
phosphor-fabric-mc1.19.x-0.8.1
pickyourpoison-1.0.11
puzzle-1.4.0-1.19
qfapi-4.0.0-beta.26_qsl-3.0.0-beta.25_fapi-0.72.0_mc-1.19.2
quiltgoslightlyfasterlol-0.0.3
quilt-kotlin-libraries-1.0.2+kt.1.8.0+flk.1.9.0
ratsmischief-2.0.1
reeses_sodium_options-1.4.9+mc1.19.2-build.67
replaymod-1.19.2-2.6.13
requiem-2.0.0-beta.16
RoughlyEnoughItems-9.1.657
Rrls-1.19.2-3.1.1-fabric
shulkerboxtooltip-fabric-3.2.2+1.19.2
smoothboot-fabric-1.19-1.7.1
sodium-extra-0.4.16+mc1.19.2-build.90
sodium-fabric-mc1.19.2-0.4.4+build.18
soundphysics-fabric-1.19.2-1.2.1
starlight-1.1.1+fabric.ae22326
supplementaries-1.19.2-2.3.24-fabric
Terralith_v2.3.5
tooltipfix-1.1.1-1.19
trinkets-3.4.2
wmch-1.19.2-1.5.7
YetAnotherConfigLib-1.7.1
yosbr-0.1.1
Zoomify-2.9.0

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Your Quilt Loader appears to be out of date. You'll need to rerun the Quilt installer and select a newer version, e.g. `0.21.1` instead of `0.18.1-beta41`.
