### ISSUE TITLE
game does not open because of a "missing" mod i actually have

### ISSUE THREAD

**Issue by WinkMouse** [Virtuoel/Pehkui#459]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

0.14.23

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

i was opening the game, but a screen appeared, that said that i needed a mod, the fabric API base, but i have the fabric API and still does not load
![image](https://github.com/Virtuoel/Pehkui/assets/147747948/d79cd7a9-2684-45a5-98f2-d8f60ceda2ee)

### Full list of installed mods and their version numbers

Fabric API
Pehkui

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Since you didn't provide the version number of Fabric API, I can only assume you installed Fabric but not the API.
All I can suggest is to add [Fabric API](https://modrinth.com/mod/fabric-api/version/0.90.4+1.20.1) and try again, as the Fabric Loader on its own is not enough.

**Comment by WinkMouse** [comment]
> Since you didn't provide the version number of Fabric API, I can only assume you installed Fabric but not the API. All I can suggest is to add [Fabric API](https://modrinth.com/mod/fabric-api/version/0.90.4+1.20.1) and try again, as the Fabric Loader on its own is not enough.

ok, ill try to
