### ISSUE TITLE
[Bug]: Moving while easing `motion` causes erratic view bobbing / shake

### ISSUE THREAD

**Issue by sisby-folk** [Virtuoel/Pehkui#462]
### Minecraft version(s)

1.20.1

### Mod loader

Fabric

### Mod loader version

0.14.23

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

While motion scaling is occurring, the view bobbing progress appears to fluctuate erratically during movement - i assume this is because the interpolation per-frame between each tick for the view bobbing progress is very messed up if the movement speed is slowly changed. This would probably require careful correction to fix, but it's worth documenting.

https://github.com/Virtuoel/Pehkui/assets/55819817/168cfaac-fd6f-4b24-90e6-212b59b4ff2d

Because motion is included in base, this unfortunately affects scaling base as well - In all versions i remember trying pehkui on, this shaking has occurred when changing base.

Bodge workarounds would include freezing view bobbing in-place while motion scaling is happening, or trying force motion delay to 0 ticks including in base, but both of those are pretty messy.

### Full list of installed mods and their version numbers

Mods:
  [✔] fabric-api-0.90.0+1.20.1
  [✔] Pehkui-3.7.8+1.14.4-1.20.1

### Did the problem cause the game to crash?

No.

**Comment by AndrewScripter587** [comment]
also happens while easing the view bobbing scale, but much worse.
