### ISSUE TITLE
[Bug]: Crash when Joining World on Recent Update

### ISSUE THREAD

**Issue by Camawama** [Virtuoel/Pehkui#465]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

Forge 1.20.1-47.1.3

### Fabric API version

Forgified Fabric API 0.90.4+1.9.29+1.20.1

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Could be caused by a conflict in my Modpack but the problem only started after updating to Pehkui version **3.7.9**

1. Update Pehkui to v3.7.9
2. Load my Modpack
3. Attempt to join a world
4. Experience Crash

### Full list of installed mods and their version numbers

        - ad_astra 1.15.4
	- additionalstructures 4.2.1
	- aeroblender 1.20.1-1.0.1-neoforge
	- aether 1.20.1-1.0.0-beta.1.4-neoforge
	- aether_redux 1.20.1
	- alexsmobs 1.22.6
	- ambientsounds 5.2.24
	- apotheosis 7.0.5
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.0
	- aquamirae 6.API15
	- architectury 9.1.12
	- ars_creo 4.0.1
	- ars_nouveau 4.7.0
	- arss 1.20.1-0.4.0
	- artifacts 9.1.0
	- athena 3.1.1
	- attributefix 21.0.2
	- attributeslib 1.1.4
	- automobility 0.4.2+1.20.1-forge
	- balm 7.1.4
	- bbs 1.20.1-0.1.3
	- bcc 3.0.1-build.58+mc1.20
	- bellsandwhistles 0.4.1-1.20.x
	- betteradvancements 0.3.2.161
	- betterburning 9.0.2
	- bettercombat 1.8.0+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterendisland 1.20-Forge-2.0.4
	- betterfortresses 1.20-Forge-2.0.5
	- betterfpsdist 1.20.1-3.9
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.3
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomeinfo 1.5
	- biomemakeover 1.20.1-1.11.4
	- biomesoplenty 18.0.0.592
	- blue_skies 1.3.29
	- blueprint 7.0.0
	- bookshelf 20.1.6
	- borderlesswindow 1.20-1.6.0
	- bossrifts 1.3
	- botarium 2.2.0
	- bridgingmod 2.1.1+1.20.1.forge
	- bygonenether 1.3.2
	- camera 1.20.1-1.0.6
	- carryon 2.1.2.5
	- catalogue 1.8.0
	- ceilingtorch 1.26
	- cfm 7.0.0-pre36
	- chat_heads 0.10.22
	- chipped 3.0.1
	- chiselsandbits 1.4.144
	- chunkanimator 1.20.1-1.3.7
	- chunky 1.3.92
	- cicada 0.4.4
	- citadel 2.4.4
	- clickadv 1.20.1-3.5
	- clientresetpacket 0.0.6
	- clienttweaks 11.1.0
	- cloth_config 11.1.106
	- collective 6.66
	- com_github_llamalad7_mixinextras 0.2.0-beta.8
	- combatroll 1.2.3+1.20.1
	- comforts 6.3.4+1.20.1
	- computercraft 1.108.3
	- connectormod 1.0.0-beta.21+1.20.1
	- consecration 7.0.1+1.20.1
	- constructionwand 1.20.1-2.11
	- controlling 12.0.2
	- corgilib 4.0.0.4
	- crafttweaker 14.0.17
	- craterlib 1.0.2
	- create 0.5.1.e
	- create_structures 0.1.1
	- create_things_and_misc 1.0.0
	- createaddition 1.20.1-1.1.1
	- createpickywheels 1.20.1-230708T15
	- createtweaker 4.0.7
	- creativecore 2.11.7
	- creeperoverhaul 3.0.1
	- cristellib 1.1.3
	- cucumber 7.0.3
	- cumulus_menus 1.20.1-1.0.0-beta.1-neoforge
	- cupboard 1.20.1-2.0
	- curios 5.4.0+1.20.1
	- daily_rewards 5.2.0
	- damagevignette 2.0.2
	- deep_aether 1.20.1-1.0.10
	- deeperdarker 1.2.1
	- denseores 1.2.1
	- diet 2.1.1+1.20.1
	- do_a_barrel_roll 3.3.51.20
	- domesticationinnovation 1.7.0
	- dummmmmmy 1.20-1.8.5
	- dungeons_arise 2.1.56.1-1.20.1
	- elevatorid 1.20.1-1.8.15
	- emi 1.0.23+1.20.1+forge
	- emojitype 2.2.1+1.20
	- enchdesc 17.0.8
	- enderchests 1.20.1-1.1
	- endertanks 1.20.1-1.1
	- endrem 5.2.3-R-1.20.1
	- enhancedcelestials 5.0.0.2
	- enlightened_end 5.0.9
	- entangled 1.3.16
	- entityculling 1.6.2
	- everycomp 1.20-2.6.12
	- expandability 9.0.0
	- expandedstorage 10.0.0-beta.3
	- explosiont 2.4.7
	- fabric_api 0.90.4+1.9.29+1.20.1
	- fabric_api_base 0.4.30+ef105b4977
	- fabric_api_lookup_api_v1 1.6.35+561530ec77
	- fabric_biome_api_v1 13.0.12+dd0389a577
	- fabric_block_api_v1 1.0.10+0e6cb7f777
	- fabric_block_view_api_v2 1.0.0+0767707077
	- fabric_blockrenderlayer_v1 1.1.40+8005d10d77
	- fabric_client_tags_api_v1 1.1.1+5d6761b877
	- fabric_command_api_v1 1.2.33+f71b366f77
	- fabric_command_api_v2 2.2.12+561530ec77
	- fabric_content_registries_v0 4.0.10+a670df1e77
	- fabric_convention_tags_v1 1.5.4+fa3d1c0177
	- fabric_data_generation_api_v1 12.3.2+369cb3a477
	- fabric_dimensions_v1 2.1.53+8005d10d77
	- fabric_entity_events_v1 1.5.22+b909fbe377
	- fabric_events_interaction_v0 0.6.1+25d9948677
	- fabric_game_rule_api_v1 1.0.38+22f4bbd577
	- fabric_item_api_v1 2.1.27+2272fc7f77
	- fabric_item_group_api_v1 4.0.11+369cb3a477
	- fabric_key_binding_api_v1 1.0.36+561530ec77
	- fabric_lifecycle_events_v1 2.2.21+afab492177
	- fabric_loot_api_v2 1.2.0+eb28f93e77
	- fabric_message_api_v1 5.1.8+369cb3a477
	- fabric_mining_level_api_v1 2.1.49+561530ec77
	- fabric_model_loading_api_v1 1.0.2+731e429d77
	- fabric_models_v0 0.4.1+7c3892a477
	- fabric_networking_api_v1 1.3.10+47fce50c77
	- fabric_object_builder_api_v1 11.1.2+2174fc8477
	- fabric_particles_v1 1.1.1+7802dd6f77
	- fabric_permissions_api_v0 0.2-SNAPSHOT
	- fabric_recipe_api_v1 1.0.20+514a076577
	- fabric_registry_sync_v0 2.3.2+1c0ea72177
	- fabric_renderer_api_v1 3.2.0+6f53282b77
	- fabric_renderer_indigo 1.5.0+837512f977
	- fabric_rendering_data_attachment_v1 0.3.36+a6081afc77
	- fabric_rendering_fluids_v1 3.0.27+4ac5e37a77
	- fabric_rendering_v1 3.0.7+1c0ea72177
	- fabric_resource_conditions_api_v1 2.3.6+369cb3a477
	- fabric_resource_loader_v0 0.11.9+65ee760177
	- fabric_screen_api_v1 2.0.7+e7e7fde177
	- fabric_screen_handler_api_v1 1.3.29+561530ec77
	- fabric_sound_api_v1 1.0.12+4f23bd8477
	- fabric_transfer_api_v1 3.3.1+4c6d1bcd77
	- fabric_transitive_access_wideners_v1 4.3.0+1880499877
	- fallingtrees 0.6-beta
	- fancymenu 2.14.9
	- farlanders 1.4.1
	- farmersdelight 1.20.1-1.2.3
	- fastload 3.4.0
	- ferritecore 6.0.1
	- fishingreal 1.20.1-1.7.1
	- flywheel 0.6.10-7
	- forbidden_arcanus 1.20.1-2.2.1
	- forge 47.1.3
	- forgivingvoid 10.0.0
	- framedblocks 9.1.5
	- framework 0.6.16
	- gamestages 15.0.1
	- geckolib 4.2.3
	- goprone 3.1.1
	- grapplemod 1.20.1-v13
	- gravelminer 16.0.2
	- hammersandexcavators 1.1
	- immediatelyfast 1.2.6+1.20.2
	- imst 2.1.0
	- incendium 5.3.2
	- infernalmobs 1.20.1.0
	- inventorysorter 23.0.1
	- invmove 0.8.4
	- ironfurnaces 3.9.0
	- itemphysic 1.6.15
	- itemstages 8.0.1
	- jei 15.2.0.27
	- jeitweaker 8.0.6
	- jeresources 1.4.0.238
	- jrftl 1.6.0
	- kiwi 11.1.1
	- konkrete 1.6.1
	- kotlinforforge 4.5.0
	- l2library 2.4.11
	- libx 1.20.1-5.0.7
	- lightingwand 8.0.0
	- lim_lib 1.20.1-0.2.0
	- lootr 0.7.29.68
	- lost_aether_content 1.2.2
	- majruszsenchantments 1.9.2
	- maxhealthfix 12.0.2
	- mes 1.3-1.20-forge
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.9
	- mixinsquared 0.1.1
	- mlib 5.1.2
	- mob_grinding_utils 1.20.1-1.0.2
	- modernfix 5.8.1+mc1.20.1
	- moonlight 1.20-2.8.51
	- morevanillalib 1.20.1-5.0.1
	- mousetweaks 2.25
	- mr_dungeons_andtaverns 3.0.3
	- mr_reds_morestructures 1.0.8R
	- multimine 1.20.1.2
	- nitrogen_internals 1.20.1-0.1.3-neoforge
	- nohostilesaroundcampfire 5.6
	- notenoughanimations 1.6.4
	- notenoughcrashes 4.4.6+1.20.1
	- nullscape 1.2.3
	- nyfsspiders 2.1.1
	- obscure_api 15
	- observable 4.4.0
	- openloader 19.0.3
	- openpartiesandclaims 0.20.1
	- oresabovediamonds 10.0.1b
	- packingtape 0.14.1
	- patchouli 1.20.1-81-FORGE
	- pehkui 3.7.9+1.20.1-forge
	- placebo 8.3.7
	- playeranimator 1.0.2-rc1+1.20
	- potionbundles 1.7
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.3
	- radium 0.12.1+git.915d28d
	- railways 1.5.2+forge-mc1.20.1
	- reap 1.20.1-1.0.2
	- rebind_narrator 2.0.2
	- recipestages 8.0.0.1
	- refinedstorage 1.12.3
	- relics 0.4.8.6
	- repurposed_structures 7.1.10+1.20.1-forge
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.13
	- restrictedportals 1.5.0
	- rrls 3.2.0-1.20.1-forge
	- scalinghealth 8.0.1+8
	- scena 1.0.102
	- searchables 1.0.2
	- secondchanceforge 1.5.1
	- securitycraft 1.9.8
	- shetiphiancore 1.20.1-1.1
	- shieldexp 1.1.6a
	- shimmer 1.20.1-0.1.20
	- silentlib 8.0.0
	- simplefarming 1.20.1-2.0.6
	- simplerpc 3.2.4
	- simplyswords 1.51.0-1.20.1
	- sliceanddice 3.2.0
	- snowballsfreezemobs 3.1
	- solapplepie 1.20.1-2.3.0
	- some_assembly_required 1.20.1-4.0.0
	- sound_physics_remastered 1.20.1-1.2.1
	- spark 1.10.53
	- spectrelib 0.13.14+1.20.1
	- spelunkers_charm 1.0.0
	- spyglass_improvements 1.4+mc1.20.x
	- starlight 1.1.2+forge.1cda73c
	- stellarview 0.1.5
	- structure_gel 2.15.0
	- suggestionproviderfix 1.20.1-1.0.0
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.15
	- supplementaries 1.20-2.6.17
	- t_and_t 0.0NONE
	- taniwha 1.20.0-5.4.4
	- tarotcards 1.20-1.5.5
	- tectonic 2.1.1
	- terrablender 3.0.0.169
	- terralith 2.4.7
	- theoneprobe 1.20.1-10.0.0
	- thirst 1.20.1-1.3.4
	- tht 6.0.0
	- tintedcampfires 1.20.1-1.2.10
	- tipsmod 12.0.3
	- torchbowmod 1.0.0
	- trade_cycling 1.20.1-1.0.7
	- treechop 0.18.3
	- twilightdelight 2.0.1
	- twilightforest 4.3.1850
	- undergarden 0.8.8
	- usefulbackpacks 2.0.1.122
	- uteamcore 5.1.4.269
	- valhelsia_core 1.1.1
	- vanillatweaks 1.5.70
	- visuality 2.0.2
	- voicechat 1.20.1-2.4.27
	- walljump 1.20.1-1.0.1-forge
	- wandering_bags 2.0.6
	- watching 1.9.2
	- waystones 14.0.2
	- weakerspiderwebs 3.2
	- xaerominimapfair 23.8.2
	- xaeroworldmap 1.36.0
	- xbob 1.2
	- xpbook 2.1.8
	- yungsapi 1.20-Forge-4.0.2
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
CRASH REPORT WAS TOO LONG TO PASTE ENTIRE CONTENTS SO HERE IS THE TXT FILE

[crash-2023-10-28_21.34.08-client.txt](https://github.com/Virtuoel/Pehkui/files/13197067/crash-2023-10-28_21.34.08-client.txt)

**Comment by Virtuoel** [comment]
Should now be resolved as of the 3.7.10 release.

**Comment by Virtuoel** [comment]
Whoops, slight mistake during that fix. Should now actually be resolved as of 3.7.11.

**Comment by Camawama** [comment]
I'll test it out, thank you.

**Comment by Camawama** [comment]
Completely forgot to respond to this. Can confirm it is working.
