### ISSUE TITLE
[Bug]: Pehkui + Apotheosis Step Height locked

### ISSUE THREAD

**Issue by AnonymousUser456** [Virtuoel/Pehkui#471]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

47.2.0

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

when combined with Apotheosis Pehkui is unable alter the players step height. this is likely due to code in apotheosis that alters the players step height. this does not occur in lower versions of minecraft (to my knowledge)

### Full list of installed mods and their version numbers

Placebo 1.20.1-8.5.6
Apotheosis 1.20.1-7.1.0
Apothic Attributes 1.20.1-1.2.0
Patchouli 1.20.1-81
Pehkui 3.7.11+1.20.1

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Should now be fixed as of the 3.7.12 release.
