### ISSUE TITLE
[Bug]: Quilt crash

### ISSUE THREAD

**Issue by ninjaguardian** [Virtuoel/Pehkui#472]
### Minecraft version(s)

1.19.2

### Mod loader

Quilt

### Mod loader version

Quilt loader 0.21.2

### Fabric API version

qfapi-4.0.0-beta.30_qsl-3.0.0-beta.29_fapi-0.76.0_mc-1.19.2

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

When I boot minecraft, Quilt says to update quilt loader but im on the newest.

![image](https://github.com/Virtuoel/Pehkui/assets/110734253/359870b6-644f-4bf5-a53f-fce5cdbf33f3)

### Full list of installed mods and their version numbers

![image](https://github.com/Virtuoel/Pehkui/assets/110734253/efe07f3b-2847-4eae-83dc-c39326f3ed9f)
![image](https://github.com/Virtuoel/Pehkui/assets/110734253/059482ec-90eb-448e-ab40-751816881b12)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
https://pastebin.com/PpVfqsh8

**Comment by Virtuoel** [comment]
Looking at your log, your Quilt Loader is outdated. It mentions that you have 0.19.12 installed. You'll need to rerun the Quilt installer and pick 0.22.0 or newer.
