### ISSUE TITLE
[Bug]: Server crashes when joining the server

### ISSUE THREAD

**Issue by Vili-B** [Virtuoel/Pehkui#475]
### Minecraft version(s)

1.19.2

### Mod loader

Quilt

### Mod loader version

Fabric Loader 0.14.22

### Fabric API version

Fabric API 0.76.1

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

I joined the server and immediately one of the cpu cores will be totally taxed out and after 30sec or so it will crash. Before joining the server the cpu load is averaged out normally on the cpu cores

### Full list of installed mods and their version numbers

ad_astra-fabric-1.19.2-1.12.7.jar
advdebug-2.3.0.jar
adventurez-1.4.18.jar
AE2WTLib-12.9.5.jar
almostunified-fabric-1.19.2-0.7.0.jar
alternate-current-mc1.19-1.7.0.jar
animal_feeding_trough-1.0.3+1.19.2.jar
another_furniture-fabric-1.19.2-2.1.4.jar
Applied-Botanics-fabric-1.4.5.jar
appliedenergistics2-fabric-12.9.8.jar
architects-palette-fabric-3.0.0.jar
architectury-6.5.85-fabric.jar
archon-0.5.0.jar
Armorful-2.0.2+WWA_COMPAT.jar
artifacts-7.1.1+fabric.jar
AttributeFix-Fabric-1.19.2-17.2.7.jar
autoconfig1u-3.4.0.jar
autotag-2.0.0+1.19.jar
auto-workstations-[MC1.19]-v1.0-SNAPSHOT-19.jar
auudio_fabric_1.0.3_MC_1.19.jar
balm-fabric-1.19.2-4.6.0.jar
BarteringStation-v4.0.3-1.19.2-Fabric.jar
Basket-Fabric 1.19.2.jar
bclib-2.1.7.jar
BeaconOverhaul-1.7.3+1.19.2.jar
befixment-2.0.0.jar
besmirchment-1.19.2-11.jar
betterchunkloading-fabric-1.19.2-2.1.jar
bettercombat-fabric-1.7.1+1.19.jar
BetterCompatibilityChecker-Fabric-2.0.2-build.16+mc1.19.1.jar
better-end-2.1.6.jar
betterfpsdist-fabric-1.19-2.4.jar
better-nether-7.1.4.jar
betterstats-2.9.3+1.19.2.jar
BetterTridents-v4.0.2-1.19.2-Fabric.jar
bewitchment-1.19-7.jar
bewitchmentplus-1.19-11.jar
blockus-2.5.11+1.19.2.jar
BoatBreakFix-Universal-1.0.2.jar
BOMD-1.4.6-1.19.2.jar
BoneZone-Fabric-1.19.2-1.0.3.jar
Bookshelf-Fabric-1.19.2-16.3.20.jar
Botania-1.19.2-440-FABRIC.jar
BotanyPots-Fabric-1.19.2-9.0.38.jar
BotanyTrees-Fabric-1.19.2-5.0.12.jar
botarium-fabric-1.19.2-1.8.2.jar
BountifulFabric-4.0.0.jar
BowInfinityFix-1.19.x-fabric-2.5.0.jar
brewinandchewin-fabric-2.1.5+1.19.2.jar
BuildingWands-mc1.19.2-2.6.8-release-fabric.jar
bwncr-fabric-1.19.2-3.14.1.jar
bygonenether-1.19-1.3.2.jar
capsey-archeology-1.19.2-0.2.5.jar
cardinal-components-api-5.0.2.jar
carryon-fabric-1.19.2-2.1.1.21.jar
cc-restitched-1.101.2.jar
chalk-2.2.0+1.19.jar
charm-fabric-1.19.2-4.4.4.jar
charmofundying-fabric-6.2.1+1.19.2.jar
chefs-delight-1.0.3-fabric-1.19.2.jar
Chimes-v2.0.1-1.19.2-Fabric.jar
chisels-and-bits-fabric-1.3.142.jar
chunksending-fabric-1.19.2-2.6.jar
cloth-api-4.0.65.jar
cloth-config-8.3.103-fabric.jar
Clumps-fabric-1.19.2-9.0.0+14.jar
collective-1.19.2-6.66.jar
ColorfulAzaleas-fabric-1.19.2-2.3.1.jar
combatroll-fabric-1.1.5+1.19.jar
comforts-fabric-6.0.4+1.19.2.jar
Companion-1.19.2-fabric-3.2.2.jar
configured-fabric-2.0.0-1.19.2.jar
connectivity-fabric-1.19.2-4.5.jar
CorgiLib-fabric-1.19.2-1.0.0.34.jar
CraftTweaker-fabric-1.19.2-10.1.50.jar
crawl-0.11.1.jar
createaddition-fabric+1.19.2-20230723a.jar
create-fabric-0.5.1-c-build.1160+mc1.19.2.jar
CreativeCore_FABRIC_v2.9.4_mc1.19.2.jar
crittersandcompanions-fabric-1.19.2-2.0.2.jar
Croptopia-1.19.2-FABRIC-2.2.2.jar
croptopia-chocolaterie-1.2-1.19.jar
ctov-3.2.6c.jar
cultural-delights-fabric-0.14.10+1.19.2.jar
cupboard-fabric-1.19.2-2.0.jar
DarkPaintings-Fabric-1.19.2-13.1.5.jar
DarkUtilities-Fabric-1.19.2-13.1.9.jar
dataattributes-1.4.6+1.19.2.jar
dawn-3.5.0.jar
Debugify-2.8.0.jar
Decorative Blocks-fabric-1.19.2-3.0.0.jar
deeperdarker-fabric-1.1.6-fabric.jar
deepslatecutting-fabric-1.5.0.jar
DEUF_Refabricated-MC1.19.2-1.0.0.jar
DiagonalFences-v4.2.6-1.19.2-Fabric.jar
Display Case-fabric-1.19-1.0.7.jar
do-a-barrel-roll-2.6.2+1.19.2-fabric.jar
dragonfight-fabric-1.19.2-4.1.jar
dragonloot-1.1.2.jar
dummmmmmy-1.19.2-1.7.1-fabric.jar
DungeonsArise-1.19.2-2.1.54-fabric.jar
EasyAnvils-v4.0.11-1.19.2-Fabric.jar
ecologics-fabric-1.19.2-2.1.11.jar
eden-ring-0.6.4.jar
elytraslot-fabric-6.1.1+1.19.2.jar
expandeddelight-0.2.5.2.jar
expert_armor-2.5.1.jar
explorify-fabric-1.19-1.3.0.jar
extended-armor-bars-1.2.1.jar
fabric-api-0.76.1+1.19.2.jar
fabric-end-remastered-5.2.0.jar
fabric-experiencebugfix-1.19-19.jar
fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
FabricShieldLib-1.7.1-1.19.2.jar
fabric-the-lost-castle-1.0.0.jar
farmers-delight-fabric-mc1.19-1.19.2-1.3.10.1.jar
farmersknives-2.4.1.jar
Farmersrespite-Fabric-2.2.5.jar
farsight-fabric-1.19.2-3.5.jar
FauxCustomEntityData-fabric-1.19.2-2.0.2.jar
ferritecore-5.0.3-fabric.jar
Fertilizer 1.19 Forge v.1.2.jar
findme-3.1.0-fabric.jar
fish_of_thieves-mc1.19.2-v2.2.4-fabric.jar
food-plus-1.4.1.jar
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
frame-0.26.2+1.19-fabric.jar
friendsandfoes-fabric-mc1.19.2-1.8.10.jar
frostiful-0.5.6.jar
ftb-library-fabric-1902.4.1-build.236.jar
ftb-quests-fabric-1902.5.6-build.304.jar
ftb-teams-fabric-1902.2.14-build.123.jar
ftb-ultimine-fabric-1902.4.1-build.90.jar
geckolib-fabric-1.19-3.1.40.jar
goblintraders-fabric-1.8.1-1.19.2.jar
go-fish-1.6.0-1.19.1.jar
goodall-1.2.0-fabric.jar
GottschCore-fabric-mc1.19.2-2.2.0.jar
Grass_Overhaul-Fabric-23.05.28_MC1.17.1-1.19.2.jar
guardvillagers-2.0.6-1.19.2.jar
handcrafted-fabric-1.19.2-2.0.6.jar
healing bed 1.19.2 (Fabric).jar
hexal-fabric-1.19.2-0.2.18.jar
hexcasting-fabric-1.19.2-0.10.3.jar
highlight-1.0.0-fabric.jar
HorseExpert-v4.0.0-1.19.2-Fabric.jar
icarus-1.14.jar
Iceberg-1.19.1-fabric-1.0.46.jar
immersive_armors-1.5.6+1.19.2-fabric.jar
impaled-1.1.4.jar
indrev-1.15.1-BETA.jar
IngredientExtensionAPI-fabric-1.19.2-3.0.6.jar
InventorySorter-1.8.10-1.19.jar
ironchests-3.1.3-fabric.jar
item-filters-fabric-1902.2.9-build.51.jar
Item_Obliterator-Fabric_Quilt-1.2.0.jar
Jade-1.19.1-fabric-8.7.3.jar
jamlib-0.6.1+1.19-1.19.2.jar
Jewelry-1.1.0+1.19.2.jar
jumpoverfences-fabric-1.19.2-1.1.0.jar
Kambrik-4.0-1.19.2.jar
Kiwi-1.19.1-fabric-8.3.4.jar
kleeslabs-fabric-1.19.2-12.3.0.jar
konkrete_fabric_1.6.1_MC_1.19.1-1.19.2.jar
krypton-0.2.1.jar
labels-1.19.2-1.10-fabric.jar
LeavesBeGone-v4.0.1-1.19.2-Fabric.jar
letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar
letsdo-api-fabric-1.1.0.jar
letsdo-meadow-fabric-1.2.4.jar
letsdo-vinery-fabric-1.3.10.jar
libz-1.0.0.jar
lithium-fabric-mc1.19.2-0.11.1.jar
Log-Begone-Fabric-1.19.x-1.0.6.jar
lootintegrations-fabric-1.19.2-3.2.jar
lootr-1.19-0.4.27.67.jar
Luna-FABRIC-MC1.19.X-1.0.1.jar
MageFlame-fabric-mc1.19.2-v1.5.0.jar
magicvibedecorations-HALLOWEEN 1.10.0 1.19.2 fabric.jar
MagnumTorch-v4.2.3-1.19.2-Fabric.jar
Measurements-fabric-1.19.2-1.3.1.jar
memoryleakfix-fabric-1.17+-1.1.2.jar
mes-1.3-1.19.2-fabric.jar
midnightlib-fabric-1.0.0.jar
minecells-1.5.3.jar
minelib11-0.1.3+1.19.jar
mixintrace-1.1.1+1.17.jar
mobscarecrow-2.2.1-1.19.1.jar
modernfix-fabric-5.8.1+mc1.19.2.jar
Modern-Industrialization-1.6.16.jar
Mo-Glass-1.6.1-MC1.19.2.jar
moonlight-1.19.2-2.2.45-fabric.jar
more-geodes-1.7+1.19.jar
more-totems-mod-2.13.0.jar
morevillagers-fabric-1.19-4.0.2.jar
mvs-2.2-1.19.2.jar
mythic-mounts-1.19.2-7.2.jar
mythicupgrades-1.5.1+1.19.2.jar
naturalist-fabric-3.0.4-1.19.2.jar
NaturesCompass-1.19.2-2.1.0-fabric.jar
nbtcrafting-2.2.3+mc1.19.jar
Necronomicon-Fabric-1.1.0.jar
nerb-1.19.2-0.3-FABRIC.jar
netherportalfix-fabric-1.19-10.0.1.jar
NethersDelight-1.0.1.jar
NightConfigFixes-v4.0.7-1.19.2-Fabric.jar
NoChatReports-FABRIC-1.19.2-v1.13.12.jar
observable-3.3.1.jar
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.4.jar
onsoulfire-1.19-2.jar
opac-fabric-create-support-1.3.0.jar
open-parties-and-claims-fabric-1.19.2-0.20.0.jar
OreClumps-fabric-1.19.2-0.1.1.jar
owo-lib-0.9.3+1.19.jar
oxidized-1.7.2.jar
Paintings-fabric-1.19.2-10.2.4.0.jar
paladins-fabric-0.9.6+1.19.2.jar
paradise-lost-2.1.0-beta+1.19.2.jar
Patchouli-1.19.2-77-FABRIC.jar
paucal-fabric-1.19.2-0.5.0.jar
Paxi-1.19.2-Fabric-3.0.1.jar
Pehkui-3.7.11+1.14.4-1.20.2.jar
PigPen-Fabric-1.19.2-11.1.2.jar
player-animation-lib-fabric-1.0.2.jar
plushie-mod-1.2.jar
polymorph-fabric-0.46.4+1.19.2.jar
Powah-4.0.11.jar
Prism-1.19.2-fabric-1.0.3.jar
probablychests-0.5.5-1.19.2.jar
projectile_damage-fabric-3.2.1+1.19.jar
promenade-2.7.1.jar
Prominent-FABRIC-MC1.19.2-1.2.2b.jar
Public GUI Announcement-fabric-1.19.2-4.3.3.jar
puffish_skills-0.9.0-1.19.2-fabric.jar
PuzzlesLib-v4.4.3-1.19.2-Fabric.jar
quartz-elevator-2.1.5+1.19.jar
rare-ice-0.5.0.jar
reacharound+1.19-1.1.2.jar
RebornCore-5.4.0.jar
redbits-1.16.2.jar
redirectionor-1.19.2-3.3.2-fabric.jar
RegionsUnexploredFabric-0.4.1+1.19.2.jar
repurposed_structures_fabric-6.3.26+1.19.2.jar
rer-2.6.0.jar
resourcefulconfig-fabric-1.19.2-1.0.20.jar
resourcefullib-fabric-1.19.2-1.1.24.jar
revelationary-1.3.5.jar
right-click-harvest-3.2.3+1.19.x-1.20.1-fabric.jar
riverredux-0.3.0+fabric.jar
rottencreatures-fabric-1.19.2-1.0.1.jar
RoughlyEnoughItems-9.1.663.jar
RoughlyEnoughLootTables-1.19-1.0.jar
RoughlyEnoughProfessions-fabric-1.19.2-1.1.4.jar
Runelic-Fabric-1.19.2-14.1.4.jar
runes-fabric-0.9.8+1.19.jar
ServerBrowser-1.19.2-FABRIC-1.1.0.jar
Shield_Overhaul-FABRIC-MC1.19.2-1.0.3.jar
ShowMeWhatYouGot-1.19.2-1.0.3.jar
simplyswords-fabric-1.47.0-1.19.2.jar
SkyVillages-1.0.3.1-1.19.2-1.20.1-fabric.jar
smallships-fabric-1.19.2-2.0.0-a2.3.jar
smarterfarmers-1.19.2-1.7.2-fabric.jar
smoothchunk-fabric-1.19.2-3.2.jar
snow-under-trees-fabric-1.0.0+1.19.2.jar
soulslike-weaponry-0.9.9.3.jar
soundphysics-fabric-1.19.2-1.0.18.jar
spark-1.10.37-fabric.jar
spectrum-1.6.12-1.19.2-leisure_time.jar
spellbladenext-fabric-1.19.2-1.0.27.5.jar
spell_engine-fabric-0.9.25+1.19.jar
spell_power-fabric-0.9.12+1.19.jar
spirit-fabric-1.19.2-2.2.6.jar
starlight-1.1.1+fabric.ae22326.jar
starterkit-1.19.2-5.2.jar
Steam_Rails-1.5.1+fabric-mc1.19.2.jar
Strawgolem-fabric-1.19.2-2.0.0-beta.5.jar
Structory-1.19-v1.3.jar
Structory_Towers_1.19_v1.0.1.jar
structureessentials-fabric-1.19.2-3.0.jar
supplementaries-1.19.2-2.3.24-fabric.jar
takesapillage-1.19-1.0.4.jar
talkbubbles-1.0.4.jar
TechReborn-5.4.0.jar
TerraBlender-fabric-1.19.2-2.0.1.136.jar
the_bumblezone_fabric-6.7.36+1.19.2.jar
The_Graveyard_2.3.3_(FABRIC)_for_1.19.2.jar
thermoo-1.4.jar
things-0.3.0+1.19.jar
thonkutil-2.15.4+1.19.jar
tiered-1.2.7.jar
TinySkeletons-v4.2.2-1.19.2-Fabric.jar
ToolStats-Fabric-1.19.2-12.1.4.jar
Towns-and-Towers-v.1.10.1-FABRIC-1.19.2.jar
TradingPost-v4.2.0-1.19.2-Fabric.jar
transparent-5.1.2+1.19-fabric.jar
travelers-backpack-1.19.2-8.2.30.jar
TreeChop-1.19.2-fabric-0.18.3.jar
trinkets-3.4.2.jar
trofers-1.19.2-3.1.2.jar
tr-patchouli-2.1.1.jar
Tumbleweed-fabric-1.19-0.5.1.jar
twigs-3.0.0-fabric-1.19.2.jar
twilightforest-fabric-1.19.2-4.2.357.jar
VanitySlots-1.2.8.jar
variantbarrels-2.4.6.jar
variant_bookshelves-1.2.5.jar
variantcomposters-1.0.7.jar
variantcraftingtables-3.3.3.jar
variant_grindstones-1.1.2.jar
variant_lanterns-1.0.4.jar
variant_shields-1.0.3.jar
villager-hats-1.4.3.jar
villagernames-1.19.2-5.2.jar
VisualWorkbench-v4.2.4-1.19.2-Fabric.jar
vitalize-fabric-1.19.2-1.1.1.jar
vivecraft-1.19.2-1.1.2-fabric.jar
voidz-1.0.9.jar
wanderingcollector-1.1.3+mc1.19.jar
wetlands-1.1.1-1.19.2.jar
winterly-0.8.3.jar
wizards-fabric-0.9.17+1.19.jar
wolf-armor-compat-1.0.3-1.19.2.jar
wraith-croptosis-1.5.1.jar
wraith-harvestscythes-2.5.4+mc1.19.2.jar
wraith-waystones-3.0.8+mc1.19.2.jar
Xaeros_Minimap_23.8.2_Fabric_1.19.1.jar
XaerosWorldMap_1.34.1_Fabric_1.19.1.jar
xlpackets-1.19.2-4.jar
xp_obelisk-0.4.9-r+1.19.2-Fabric.jar
xp_obelisk_additions-0.1.9-r+1.19.2-Fabric.jar
YetAnotherConfigLib-2.2.0-for-1.19.2.jar
yosbr-0.1.2.jar
YOSBY-Forge-1.1.0.jar
youre-in-grave-danger-1.4.9.jar
YSNS-FFQ-1.0.3.jar
YungsApi-1.19.2-Fabric-3.8.9.jar
YungsBetterDesertTemples-1.19.2-Fabric-2.2.2.jar
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Fabric-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.1.jar
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
YungsBridges-1.19.2-Fabric-3.1.0.jar
YungsExtras-1.19.2-Fabric-3.1.0.jar
zenith-0.7.1+1.19.2.jar

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

[crash-2023-11-22_22.37.15-server.txt](https://github.com/Virtuoel/Pehkui/files/13444247/crash-2023-11-22_22.37.15-server.txt)

**Comment by ZiLenTz** [comment]
Similar situation here on Fabric 1.20.1.
After including Pehkui, running server, and applying /scale set pehkui:base to an entity, TPS reduced to around 2-4 until it crashed.
Removing Pehkui solved the issue.

Crash report: https://mclo.gs/KCWFr0z

**Comment by Virtuoel** [comment]
For Vili-B's crash report, it appears you had 60,000 items loaded in your world at once, which'll cause a crash with or without Pehkui.

For ZiLenTz's crash report, please test out the 3.8.0 release. If the base scale you set wasn't something excessively large and you still have crashes happen, please create a new issue.
