### ISSUE TITLE
Pehkui keeps disconnecting me from minecraft world and won't let me join

### ISSUE THREAD

**Issue by IronMurr** [Virtuoel/Pehkui#476]
### Minecraft version(s)

1.20.2

### Minecraft version details

1.20.2

### Mod loader

Fabric

### Mod loader version

0.14.24

### Fabric API version

0.90.7 + 1.20.2

### In what kind of world or server did the problem occur?

A singleplayer world opened to LAN that I was connected to

### What went wrong? (Crash logs don't go here)

It keeps crashing seconds from joining and has this error: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(rid

### Full list of installed mods and their version numbers

immersive portals, do a barrel roll, axiom, essential, gravity changer (qouteall fork), Fabric api, cloth config api, architectury api, indium iris shaders, jade, krypton, lithium, mod menu, no chat reports, pehkui(odiously), Reese's sodium options, roughly enough items, and sodium all in  1.20.2 and fabric

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
![Screenshot 2023-11-24 234912](https://github.com/Virtuoel/Pehkui/assets/109236311/e3f5a131-b778-4442-bfd3-bd86bf54ec92)

**Comment by Virtuoel** [comment]
Since you're using Essential, update Immersive Portals and Pehkui to their latest versions and then in Immersive Portals' `config/immersive_portals.json` set `serverRejectClientWithoutImmPtl` to `false`.
