### ISSUE TITLE
Forge crash on 1.20.1

### ISSUE THREAD

**Issue by Flamegunter** [Virtuoel/Pehkui#479]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

Forge 47.1.29

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

the game crashes once its done scanning the mod list, the last two things I see mentioned is "launching Minecraft" then "loading bootstrap resource" and it crashes near immediately.

### Full list of installed mods and their version numbers

pehkui

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

ive opened up mc with the pehkui mod multiple times now, and none have come up with a crash report.

**Comment by Virtuoel** [comment]
Should now be resolved as of the 3.8.0 release.
