### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by meitsi13** [Virtuoel/Pehkui#487]
### Minecraft version(s)

1.16.5

### Mod loader

Forge

### Mod loader version

forge 36.2.34

### In what kind of world or server did the problem occur?

Other (specify in "What went wrong?" section)

### What went wrong? (Crash logs don't go here)

I was playing with my friend on essentials mod and i maby accidentally did an oopsy woopsy oopsy daisy on my friend and reduced his size by 1000 and now when he tries to join it says invalid player move packet

### Full list of installed mods and their version numbers

a lot of mods

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

-1

**Comment by Poopooracoocoo** [comment]
Upload a crash report and log. Crash reports are in your crash-reports folder. Logs are in your logs folder.

**Comment by Virtuoel** [comment]
In cases like this, you can run `/scale debug delete_scale_data username YourFriend`, and then when your friend joins they should be back to normal.
