### ISSUE TITLE
[Bug]: Unable to run development client with pehkui

### ISSUE THREAD

**Issue by kittech0** [Virtuoel/Pehkui#491]
### Minecraft version(s)

1.20.2

### Mod loader

Fabric

### Mod loader version

0.15.6

### Fabric API version

0.91.6+1.20.2

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

Im trying to develope an addon for origin based on pehkui but the logs keeps warning about crash with ProjectileUtil and when trying to run a client it just crashes .

### Full list of installed mods and their version numbers

- fabric-api 0.91.6+1.20.2
- fabricloader 0.15.6
- minecraft 1.20.2
- origins 1.12.4
- pehkui 3.7.12+1.14.4-1.20.4
- ventur 2.0+1.20.2

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

[latest.log](https://github.com/Virtuoel/Pehkui/files/14250981/latest.log)
[crash-2024-02-12_22.08.12-client.txt](https://github.com/Virtuoel/Pehkui/files/14250997/crash-2024-02-12_22.08.12-client.txt)

</p>

**Comment by Virtuoel** [comment]
Should now be resolved in the 3.8.0 release.
