### ISSUE TITLE
[1.20.1]: Nether Stalling on server

### ISSUE THREAD

**Issue by aking4125** [Virtuoel/Pehkui#492]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

47.1.3 [Sinytra Connector]

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

Hello,

Upon exploring or generating chunks in The Nether. The server hangs. The Watchdog crashes the server with Pehuki being listed.

This is most likely a dupe of https://github.com/Virtuoel/Pehkui/issues/429 but that issue is closed.

### Full list of installed mods and their version numbers

Refer to the crash report file below. 

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

[crash-2024-02-14_15.08.21-server.txt](https://github.com/Virtuoel/Pehkui/files/14285764/crash-2024-02-14_15.08.21-server.txt)

**Comment by Virtuoel** [comment]
Can you edit the server's `config/modernfix-mixins.properties`, add a new line to the very bottom: `mixin.bugfix.chunk_deadlock=false`, and then provide a new crash log?

**Comment by aking4125** [comment]
Apologies on the delay, work has taken over for me. We will attempt this probably tomorrow night. I'll get back to you with the results.

**Comment by aking4125** [comment]
Apologies for the delay. I have attempted the above configuration for Modernfix. Server watchdog still crashes after some time with the Nether stalling upon Chunk generation (Used Chunky): 

[crash-2024-02-19_10.10.46-server.txt](https://github.com/Virtuoel/Pehkui/files/14333355/crash-2024-02-19_10.10.46-server.txt)

**Comment by Virtuoel** [comment]
Should now be resolved as of the 3.8.0 release.
