### ISSUE TITLE
1.19.2 [Bug][Suggestion]:Size 3 or above cause damage by simply walking can this be solved?

### ISSUE THREAD

**Issue by SGZ-Creations** [Virtuoel/Pehkui#494]
* Jumping as a Size 3 or above causes player to take damage so i was wondering if there could be a solution/fix.

* Idea on my end is:
By increasing height you increase how many blocks u can go down. So a player being 1x survives 3 blocks. Then 2x tall sustains 6 block fall to not ruin walking. Like climbing down a ladder or a rock as sprint jumping becomes a death sentence other wise hope this is possible but also make any smaller than base 1 is not effected for not getting an opposite effect. unless there is some details to add that would be fun play wise.

Note:
The step height dose not work regardless of using [pehkui:base] or [pehkui:step_height] nether works.

**Comment by Virtuoel** [comment]
Getting fall damage when at larger scales was definitely a bug. This should now be fixed as of the 3.8.0 release.

If you still have problems with the latest release, please create a ticket as a bug report instead of a feature request.
