### ISSUE TITLE
[Bug]: Mixin Class 1.20.1 Forge 47.2.7

### ISSUE THREAD

**Issue by Krimatoria** [Virtuoel/Pehkui#498]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

47.2.7

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I'll think about the class mismatch errors. I don't understand which version of Java I need to fix this. I used 17 and 18 Java, I'll think the same on 21 Java.

### Full list of installed mods and their version numbers

ftb-library-forge-2001.1.5.jar
InsaneLib-1.11.1-mc1.20.1.jar
InsaneLib-1.13.1-mc1.20.1.jar
Jade-1.20.1-forge-11.8.0.jar
kubejs-forge-2001.6.4-build.138.jar
lootjs-forge-1.20.1-2.11.0.jar
MobsPropertiesRandomness-4.10.0-mc1.20.1.jar
Pehkui-3.7.12+1.20.1-forge.jar
rhino-forge-2001.2.2-build.18.jar
superbosses-1.2.0-1.20.1.jar
architectury-9.2.14-forge.jar
catalogue-forge-1.20.1-1.8.0.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

> [10Mar2024 02:14:16.464] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat116plus.AbstractBlockStateMixin from pehkui.mixins.json into net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase
> [10Mar2024 02:14:16.465] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat116plus.AbstractBlockStateMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.479] [pool-4-thread-1/DEBUG] [mixin/]: Mixing LevelMixin from kubejs-common.mixins.json into net.minecraft.world.level.Level
> [10Mar2024 02:14:16.527] [pool-4-thread-1/DEBUG] [mixin/]: Mixing ServerLevelMixin from kubejs-common.mixins.json into net.minecraft.server.level.ServerLevel
> [10Mar2024 02:14:16.561] [pool-4-thread-1/DEBUG] [mixin/]: Mixing EntityMixin from kubejs-forge.mixins.json into net.minecraft.world.entity.Entity
> [10Mar2024 02:14:16.562] [pool-4-thread-1/DEBUG] [mixin/]: Mixing EntityMixin from kubejs-common.mixins.json into net.minecraft.world.entity.Entity
> [10Mar2024 02:14:16.567] [pool-4-thread-1/DEBUG] [mixin/]: Mixing EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
> [10Mar2024 02:14:16.568] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:EntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.601] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat116plus.EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
> [10Mar2024 02:14:16.601] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat116plus.EntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.602] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat117plus.EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
> [10Mar2024 02:14:16.602] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat117plus.EntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.605] [pool-4-thread-1/DEBUG] [mixin/]: Mixing step_height.compat1194plus.EntityMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
> [10Mar2024 02:14:16.605] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:step_height.compat1194plus.EntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.607] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat117plus.patchwork.compat.EntityCalculateDimensionsMixin from pehkui.mixins.json into net.minecraft.world.entity.Entity
> [10Mar2024 02:14:16.608] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.608] [pool-4-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$pehkui$calculateDimensions$0(Lnet/minecraft/world/entity/Entity;DLnet/minecraft/world/phys/Vec3;)V to mdc2534e$lambda$pehkui$calculateDimensions$0$0 in pehkui.mixins.json:compat117plus.patchwork.compat.EntityCalculateDimensionsMixin
> [10Mar2024 02:14:16.707] [pool-4-thread-1/DEBUG] [mixin/]: Mixing step_height.IForgeEntityMixin from pehkui.mixins.json into net.minecraftforge.common.extensions.IForgeEntity
> [10Mar2024 02:14:16.707] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:step_height.IForgeEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.725] [pool-4-thread-1/DEBUG] [mixin/]: Mixing LivingEntityMixin from kubejs-common.mixins.json into net.minecraft.world.entity.LivingEntity
> [10Mar2024 02:14:16.727] [pool-4-thread-1/DEBUG] [mixin/]: Mixing LivingEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.LivingEntity
> [10Mar2024 02:14:16.727] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:LivingEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.728] [pool-4-thread-1/DEBUG] [mixin/]: Renaming synthetic method lambda$pehkui$tickMovement$minVelocity$0(I)Z to mdc2534e$lambda$pehkui$tickMovement$minVelocity$0$0 in pehkui.mixins.json:LivingEntityMixin
> [10Mar2024 02:14:16.748] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat117plus.LivingEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.LivingEntity
> [10Mar2024 02:14:16.748] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat117plus.LivingEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.749] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat1194plus.LivingEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.LivingEntity
> [10Mar2024 02:14:16.749] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat1194plus.LivingEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.749] [pool-4-thread-1/DEBUG] [mixin/]: Mixing LivingEntityMixin from insanelib.mixins.json into net.minecraft.world.entity.LivingEntity
> [10Mar2024 02:14:16.749] [pool-4-thread-1/DEBUG] [mixin/]: insanelib.mixins.json:LivingEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.750] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat115plus.LivingEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.LivingEntity
> [10Mar2024 02:14:16.751] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat115plus.LivingEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.840] [pool-4-thread-1/DEBUG] [mixin/]: Mixing ItemEntityMixin from kubejs-common.mixins.json into net.minecraft.world.entity.item.ItemEntity
> [10Mar2024 02:14:16.841] [pool-4-thread-1/DEBUG] [mixin/]: Mixing client.compat116plus.ItemEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.item.ItemEntity
> [10Mar2024 02:14:16.841] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:client.compat116plus.ItemEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.841] [pool-4-thread-1/DEBUG] [mixin/]: Mixing ItemEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.item.ItemEntity
> [10Mar2024 02:14:16.841] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:ItemEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.856] [pool-4-thread-1/DEBUG] [mixin/]: Mixing reach.PlayerEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.856] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:reach.PlayerEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.856] [pool-4-thread-1/DEBUG] [mixin/]: Mixing PlayerEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.856] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:PlayerEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.859] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat115plus.PlayerEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.859] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat115plus.PlayerEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.859] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat117plus.PlayerEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.859] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat117plus.PlayerEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.860] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat1194plus.PlayerEntityMixin from pehkui.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.860] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat1194plus.PlayerEntityMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.861] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat1201minus.EntityVehicleHeightOffsetMixin from pehkui.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.861] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat1201minus.EntityVehicleHeightOffsetMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.863] [pool-4-thread-1/DEBUG] [mixin/]: Mixing PlayerMixin from insanelib.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.863] [pool-4-thread-1/DEBUG] [mixin/]: insanelib.mixins.json:PlayerMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.868] [pool-4-thread-1/DEBUG] [mixin/]: Mixing PlayerMixin from kubejs-common.mixins.json into net.minecraft.world.entity.player.Player
> [10Mar2024 02:14:16.916] [pool-4-thread-1/DEBUG] [mixin/]: Mixing reach.IForgePlayerMixin from pehkui.mixins.json into net.minecraftforge.common.extensions.IForgePlayer
> [10Mar2024 02:14:16.916] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:reach.IForgePlayerMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.950] [pool-4-thread-1/DEBUG] [mixin/]: Mixing inject.MixinFluid from architectury-common.mixins.json into net.minecraft.world.level.material.Fluid
> [10Mar2024 02:14:16.956] [pool-4-thread-1/DEBUG] [mixin/]: Mixing ItemMixin from ftblibrary-common.mixins.json into net.minecraft.world.item.Item
> [10Mar2024 02:14:16.956] [pool-4-thread-1/DEBUG] [mixin/]: ftblibrary-common.mixins.json:ItemMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.957] [pool-4-thread-1/DEBUG] [mixin/]: Mixing inject.MixinItem from architectury-common.mixins.json into net.minecraft.world.item.Item
> [10Mar2024 02:14:16.959] [pool-4-thread-1/DEBUG] [mixin/]: Mixing reach.compat116plus.ItemMixin from pehkui.mixins.json into net.minecraft.world.item.Item
> [10Mar2024 02:14:16.959] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:reach.compat116plus.ItemMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
> [10Mar2024 02:14:16.959] [pool-4-thread-1/DEBUG] [mixin/]: Mixing ItemMixin from kubejs-common.mixins.json into net.minecraft.world.item.Item
> [10Mar2024 02:14:16.991] [pool-4-thread-1/DEBUG] [mixin/]: Mixing compat117plus.patchwork.compat.IForgeItemMixin from pehkui.mixins.json into net.minecraftforge.common.extensions.IForgeItem
> [10Mar2024 02:14:16.991] [pool-4-thread-1/DEBUG] [mixin/]: pehkui.mixins.json:compat117plus.patchwork.compat.IForgeItemMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_8 supports class version 52)
>

**Comment by Virtuoel** [comment]
Should now be resolved as of the 3.8.0 release.
