### ISSUE TITLE
I need help compiling the mod

### ISSUE THREAD

**Issue by MrFesli** [Virtuoel/Pehkui#499]
I am not into modding, but I wanted to modifiy the pehkui mod, but when I tried to compile the mod, it gave me the following error:
[error.txt](https://github.com/Virtuoel/Pehkui/files/14575698/error.txt)
I kindly ask for help on what I need to do to compile this mod,

**Comment by MrFesli** [comment]
P.S _how do I attach a label I dont use github very often_

**Comment by Virtuoel** [comment]
Building via Gradle should be a bit better as of the 3.8.0 release. Please do try it out again, making sure that you're running Gradle using Java 17.
