### ISSUE TITLE
Вылет майнкрафта при установке cloth config api

### ISSUE THREAD

**Issue by susindus** [Virtuoel/Pehkui#500]
### Minecraft version(s)

1.20.1

### Mod loader

Forge

### Mod loader version

47.2.0

### Fabric API version

у меня фордж

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

при запуске без клоф конфиг у меня betterf3 требует установки Cloth_config_API и при запуске с Cloth_config_API майн вылетает с ошибкой -1
![Снимок экрана 2024-03-15 230245](https://github.com/Virtuoel/Pehkui/assets/134128897/a68dee65-9de0-47be-b486-4781e7371492)

![Снимок экрана 2024-03-15 230245](https://github.com/Virtuoel/Pehkui/assets/134128897/a8053738-72bc-4a99-a2fc-3e110bd8d8a4)

### Full list of installed mods and their version numbers

мне лень писать весь список но без Cloth_config_API сборка работает

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>

**Comment by Virtuoel** [comment]
Should now be fixed as of the 3.8.0 release.

If you still have crash issues with this latest release, please be sure to include the crash report from the `crash-reports` folder in your `.minecraft` folder.
