### ISSUE TITLE
[Suggestion]: Update to 1.20.6

### ISSUE THREAD

**Issue by MaGyul** [Virtuoel/Pehkui#513]
### What is your suggestion?

It looks like the 1.20.x version ended with 1.20.6, is it possible to update to 1.20.6?

**Comment by Clexus** [comment]
1.20.6 has entity scale in vanilla Minecraft, do we still need this?

**Comment by MaGyul** [comment]
The scaling in vanilla Minecraft is only applicable to entities that are LivingEntities and not to entities such as items, and there is no speedup without screen fov effect like pehkui:motion, so it's a bit inconvenient, and the various scaling in Pehkui mod is more helpful than I expected. So I'm requesting the 1.20.6 update.

**Comment by Virtuoel** [comment]
Fabric version is (finally) out as 3.8.1.
NeoForge version is still in progress, so I'll keep this issue open until that's released as well.

**Comment by MaGyul** [comment]
Thank you. I needed the Fabric version. I won't close the issue, as some people might want NeoForge.

**Comment by Virtuoel** [comment]
Resolved for both Fabric and NeoForge as of the 3.8.2 release.
