### ISSUE TITLE
Third person camera moves through blocks at small scales

### ISSUE THREAD

**Issue by ghost** [Virtuoel/Pehkui#52]
At small scales the third person camera moves through blocks, instead of moving closer to the player. It's noticeable at 0.125, and at  0.03125 the camera completely ignores blocks. 
![](https://user-images.githubusercontent.com/45744247/110808734-e61fcf80-8249-11eb-8855-65602c0dbee0.png)
![](https://user-images.githubusercontent.com/45744247/110808728-e5873900-8249-11eb-84b1-726dc141a3cf.png)

**Comment by ImSpaceLover** [comment]
Issue is fixed on the latest version
