### ISSUE TITLE
[Suggestion]: Forgified Fabric Compatibility

### ISSUE THREAD

**Issue by Youhadabadday** [Virtuoel/Pehkui#528]
### What is your suggestion?

I want to suggest the possibility of finding a way to make the Pehkui library properly compatible with Forgified Fabric. 90% of the fabric mods I use like Arcadian Dream and Origins++ require the FABRIC version of Pehkui to work, yet using that version instantly hard crashes the game before it can load. Same thing happens if you use the Forge version of Pehkui with Fabric mods. It can't call the proper libraries, and therefore, still crashes. Please add this compatibility, or I will not be able to use this mod the way I want to.

**Comment by Virtuoel** [comment]
For compatibility with other mods when using Sinytra Connector and Forgified Fabric API, you should try out [ConnectorExtras](https://github.com/Sinytra/ConnectorExtras). If that still crashes, they recommend reporting to them instead of to individual mods.

**Comment by Youhadabadday** [comment]
Aight, thanks for the information. I apparentally already had it and had no idea for some reason, and I still crash. I'll let them know I'm having these issues.
