### ISSUE TITLE
First person camera clips through blocks at very small scales

### ISSUE THREAD

**Issue by ghost** [Virtuoel/Pehkui#53]
At scales of <0.001, the first person camera clips partially through the ground and nearby walls. As the scale approaches 0 it becomes almost impossible to see the floor.

Scale of 0.0005: 
![Image](https://user-images.githubusercontent.com/45744247/110813287-fb96f880-824d-11eb-84a3-6b6d9d33b718.png)

Scale of 0.0001:
![Image](https://user-images.githubusercontent.com/45744247/110813624-49abfc00-824e-11eb-83cc-b4681dc4b64f.png)

**Comment by Virtuoel** [comment]
Resolved in c8738bcf54f12b3077c4e1143c38b1a5984e1bd4 and 7e60a4d83cdd7ddc015e9d9653c323caa9333a44
