### ISSUE TITLE
[Bug] Watchdog server crash

### ISSUE THREAD

**Issue by burdoto** [Virtuoel/Pehkui#531]
### Minecraft version(s)

1.20.1

### Mod loader

Fabric

### Mod loader version

0.15.11

### Fabric API version

0.92.2

### In what kind of world or server did the problem occur?

My multiplayer server that I was running

### What went wrong? (Crash logs don't go here)

World started timing out out of nowhere ("Timed out waiting for world statistics"; ultimately leading to this watchdog crash)

### Full list of installed mods and their version numbers

[mods.txt](https://github.com/user-attachments/files/16090395/mods.txt)

### Did the problem cause the game to crash?

Yes. (paste crash report below)

### Full crash report contents (if you experienced a crash)

[crash-2024-07-03_13.40.27-server.txt](https://github.com/user-attachments/files/16090379/crash-2024-07-03_13.40.27-server.txt)

**Comment by Virtuoel** [comment]
Looking at the crash log, your watchdog crash is actually caused by your server lagging from having 52276 item entities loaded at once, not a Pehkui problem.
