### ISSUE TITLE
[Bug]: 3.8.3 is a Not Found on jitpack

### ISSUE THREAD

**Issue by Psychpsyo** [Virtuoel/Pehkui#543]
### Minecraft version(s)

1.21.0

### Mod loader

Fabric

### Mod loader version

0.15.11

### Fabric API version

0.100.1+1.21

### In what kind of world or server did the problem occur?

My singleplayer world

### What went wrong? (Crash logs don't go here)

I tried building a mod that that build process tried to access https://jitpack.io/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom but that returns "Not found".

### Full list of installed mods and their version numbers

I was trying to build the 1.21 version of Custom Player Models. ( https://github.com/tom5454/CustomPlayerModels/tree/master/CustomPlayerModelsFabric-1.21 )

### Did the problem cause the game to crash?

No.

### Full crash report contents (if you experienced a crash)

<details>
<summary>Crash report output:</summary>
<p>
A problem occurred configuring root project 'CustomPlayerModelsFabric-1.21'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not find com.github.Virtuoel:Pehkui:3.8.3.
     Searched in the following locations:
       - file:/D:/Files/Project Files/CustomPlayerModels/CustomPlayerModelsFabric-1.21/.gradle/loom-cache/remapped_mods/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
       - file:/C:/Users/Cameron/.gradle/caches/fabric-loom/minecraftMaven/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
       - file:/D:/Files/Project Files/CustomPlayerModels/CustomPlayerModelsFabric-1.21/.gradle/loom-cache/minecraftMaven/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
       - https://maven.fabricmc.net/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
       - https://libraries.minecraft.net/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
       - https://libraries.minecraft.net/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.jar
       - https://repo.maven.apache.org/maven2/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.jar
       - https://repo.maven.apache.org/maven2/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
       - https://jitpack.io/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
       - https://maven.terraformersmc.com/releases/com/github/Virtuoel/Pehkui/3.8.3/Pehkui-3.8.3.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Virtuoel** [comment]
Thanks for letting me know. I've poked the Jitpack to make it rebuild and it seems to be good now.
