### ISSUE TITLE
Conflict with recent REA versions

### ISSUE THREAD

**Issue by Draylar** [Virtuoel/Pehkui#57]
Hi Virtuoel,
   I received a [crash report ](https://paste.ubuntu.com/p/kDqWP7286k/)for a project that bundles [Reach Entity Attributes](https://github.com/JamiesWhiteShirt/reach-entity-attributes) version [1.1.0](https://github.com/JamiesWhiteShirt/reach-entity-attributes/releases/tag/1.1.0). It seems like the hooks for inventory-access-reach between both projects are conflicting:

```
Warn @ModifyConstant conflict. 
Skipping mixins.reach-entity-attributes.json:InventoryValidationMixin
->@ModifyConstant::getActualReachDistance(DLnet/minecraft/class_1657;)D with priority 1000, 
     already redirected by pehkui.mixins.json:BlockEntityUseDistanceMixin
->@ModifyConstant::canPlayerUseModifyDistance(DLnet/minecraft/class_1657;)D with priority 1000

...

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: 
    Critical injection failure: 
        Constant modifier method getActualReachDistance(DLnet/minecraft/class_1657;)D in mixins.reach-entity- 
        attributes.json:InventoryValidationMixin failed injection check, 
(0/1) succeeded. 
Scanned 1 target(s). 
Using refmap refmap.reach-entity-attributes.json
```
This is with REA **1.1.0** and Pehkui **1.7.1+21w03a** on **1.16.5**.

---
 
I did some investigation, and it seems like the mixins in question are [[here, from REA]](https://github.com/JamiesWhiteShirt/reach-entity-attributes/blob/496d7761d0855011f00667897236d9dedcda7515/src/main/java/com/jamieswhiteshirt/reachentityattributes/mixin/InventoryValidationMixin.java) and [[here, from Pehkui]](https://github.com/Virtuoel/Pehkui/blob/1.17/src/main/java/virtuoel/pehkui/mixin/reach/BlockEntityUseDistanceMixin.java). Let me know if there is anything I can do to help. Thanks for your time! :)

edit: let me know if this was fixed in a more recent version, was looking through code and can't exactly figure it out

[Game log](https://paste.ubuntu.com/p/kDqWP7286k/)

**Comment by Virtuoel** [comment]
This crash was already fixed in version 1.8.0 of Pehkui, and currently the latest is 1.9.0. 
In terms of the code from Pehkui you referenced, any mixins in the `reach` package are not applied when `reach-entity-attributes` is loaded.
