### ISSUE TITLE
Some issues with scaling

### ISSUE THREAD

**Issue by ImSpaceLover** [Virtuoel/Pehkui#6]
1)Player's movement animation aren't fit with player's real movement. I don't think that the animation speed should change.
2)Projectile aren't detect properly when target are smaller than normal.

**Comment by ImSpaceLover** [comment]
>1)You can't ride any vehicle if it's scaled
Oops. Sorry, you can. I had some bug.

**Comment by Jarfeh** [comment]
Why did you close this?
