### ISSUE TITLE
Velocity/Bungeecord connection fails 

### ISSUE THREAD

**Issue by tmshader** [Virtuoel/Pehkui#63]
When joining through a velocity proxy the server goes into a join loop and than crashes.

It seems like the proxy can't encode a packet related to pehkui. Here is the error from the proxy log:
![image](https://user-images.githubusercontent.com/43723765/112123120-40f9e500-8bc1-11eb-9165-e58eac4d31fc.png)

And here is the cause (it's on the end of the previous image, I just wanted to make it easier by sending the separated cause):
![image](https://user-images.githubusercontent.com/43723765/112123312-7272b080-8bc1-11eb-8df7-670b531c7ad1.png)

**Comment by Virtuoel** [comment]
Looks like you'll need to add [CrossStitch](https://www.curseforge.com/minecraft/mc-mods/crossstitch) to your Fabric server in order for it to support Pehkui's custom argument types through Velocity.
