### ISSUE TITLE
[1.16.5] Crashes when I walk through portal.

### ISSUE THREAD

**Issue by Stanlyhalo** [Virtuoel/Pehkui#65]
I'm using Immersive Portals 0.88 for Minecraft 1.16.5, and I'm using Pehkui 1.6.2 for Minecraft 1.16.3.
The issue is I made a 3x3 portal goto a 1x1 portal, and right when I enter the portal, the game will crash giving me this error:
`virtuoel.pehkui.api.ScaleType.getScaleData(Lnet/minecraft/class_1297;)Lvirtuoel/pehkui/api/ScaleData;`

Here is my crash report if it helps:
[crash-2021-03-31_08.44.09-client.txt](https://github.com/Virtuoel/Pehkui/files/6237776/crash-2021-03-31_08.44.09-client.txt)

**Comment by Virtuoel** [comment]
Pehkui 1.6.2 is a very outdated version. Update to 1.9.0 and it should work fine.
