### ISSUE TITLE
Random crashing with random mods.

### ISSUE THREAD

**Issue by Alkiasan** [Virtuoel/Pehkui#69]
Have noticed when adding completely unrelated mods to installs with pehkui (For example, the Leaf decay fabric mod), Pehkui will crash upon loading the world.
Log: 
[latest.log](https://github.com/Virtuoel/Pehkui/files/6290899/latest.log)

**Comment by Alkiasan** [comment]
Seems to be no reliable reproduction with this. Some mods don't work, some mods do. Sometimes they'll randomly work too. No clue the specifics of why this happens.

**Comment by Virtuoel** [comment]
You're on an old version (1.8.0). This issue has been fixed in 1.9.0. Latest version is 1.10.0.
