### ISSUE TITLE
Game crahses when i load the game with the mod. 

### ISSUE THREAD

**Issue by ghost** [Virtuoel/Pehkui#70]
I've been stuck with a problem on 1.16.4, and as any other problem, the game simply doesn't load and it crashes. I have immersive portals mod and also Pehkui on it (last version of Pehkui); Any help is welcome.

ps: Also, here's the logs (yes i was using inertia, and?)
[2021-04-12-6.log](https://github.com/Virtuoel/Pehkui/files/6296931/2021-04-12-6.log)

**Comment by Virtuoel** [comment]
"Client"s used for cheating are not supported here.

Also: `Setting user: DonRaviollone`
That username is not in use by any paid MC accounts. Piracy will not be tolerated.
