### ISSUE TITLE
[Forge] Changing scale does not change the camera's position

### ISSUE THREAD

**Issue by RomanFlour** [Virtuoel/Pehkui#76]
Pretty self-explanatory. Trying to shrink in the forge version, and the camera does not adjust itself to fit the desired size.

**Comment by Virtuoel** [comment]
What version of Forge are you using, and what other mods do you have installed, if any?

**Comment by RomanFlour** [comment]
This was on 3.1.0, tho I just started the process of updating the modpack I was using to a newer version of forge.

**Comment by RomanFlour** [comment]
36.0, actually, misremembered the number.

**Comment by Virtuoel** [comment]
Ah, 1.16.4?

**Comment by RomanFlour** [comment]
Actually 1.16.5, I misremembered the number and checked for the version I was using on a 1.16.4 modpack I had.

**Comment by Virtuoel** [comment]
Hmm, is this a custom modpack or one on e.g. CurseForge? Can you provide a full modlist? Would be very useful so I could do more extensive inter-mod compatibility testing.

**Comment by Virtuoel** [comment]
Actually, you mentioned 36.0? I believe there was an eye height issue in Forge fixed in 36.0.63, so can you let me know if the issue still occurs after updating to a Forge version newer than that, e.g. 36.1.4?

**Comment by RomanFlour** [comment]
The modpack I'm using uses Enigmatica 6 as a base, with additional mods added in. Mana n Artifice, TConstruct, Evilcraft, Walljump, Psi, Lordcraft are the mods I added to the pack that aren't in Enigmatica 6 normally. Yeah, I'll check after the modpack finishes updating.

**Comment by RomanFlour** [comment]
Just tested it after updating forge, and the problem still occurs.

**Comment by Virtuoel** [comment]
In that case, I'll add that modpack + extra mods to my list of mods to test out improving compatibility with. Thanks for bringing this to my attention.

**Comment by RomanFlour** [comment]
No problem.

**Comment by RomanFlour** [comment]
Oh, and Mahou Tsukai I added to the pack as well.

**Comment by Virtuoel** [comment]
I've found out that this is an issue with the [Shrink mod](https://github.com/gigabit101/Shrink/issues) and not Pehkui. 
Seems their size event handler doesn't take other mods' resizing into account and if their shrinking is not active they always [reset the player to the default size](https://github.com/gigabit101/Shrink/blob/master/src/main/java/net/gigabit101/shrink/events/PlayerEvents.java#L142-L145) which cancels out any size changing that mods did before the Shrink event handler was executed.
