### ISSUE TITLE
Game crashes when i go through an immersive portals portal

### ISSUE THREAD

**Issue by Sasa1405** [Virtuoel/Pehkui#77]
I wanted to play Pehkui mod on 1.16.5 with immersive portals but as soon as i walk through a portal (two diffrent sized portals so i should shrink/grow right?) the came crashes and gives me this crash log:

The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: net/minecraft/command/arguments/IArgumentSerializer
Exit-Code: -1

I play on fabric-loader-1.16.5 with these mods (with file name idk if this is useful for helping):
-Pehkui (Pehkui-2.0.0+1.16.5-forge.jar)
-Immersive portals (immersive-portals-0.90-mc1.16.5-fabric.jar)
-fabric (fabric-api-0.32.9+1.16.jar)

I don't really know what to do about it ._.

**Comment by Virtuoel** [comment]
You appear to be using the Forge version of Pehkui on Fabric. Can you try again with the Fabric version?

**Comment by Sasa1405** [comment]
You mean that one? "Pehkui-2.0.0+21w14a.jar"

**Comment by Virtuoel** [comment]
Yep.

**Comment by Sasa1405** [comment]
It works now, thank you for helping me (even if it was just a fault by me and not an issue, sorry for that btw) and your time.

**Comment by Virtuoel** [comment]
No problem. Glad to be of assistance.
