### ISSUE TITLE
Incompatibilities

### ISSUE THREAD

**Issue by ImSpaceLover** [Virtuoel/Pehkui#8]
This mod is incompatible with:
Optifine
[crash-2020-07-31_23.39.38-client.txt](https://github.com/Virtuoel/Pehkui/files/5008975/crash-2020-07-31_23.39.38-client.txt)

And Carpet (https://www.curseforge.com/minecraft/mc-mods/carpet)
[crash-2020-07-31_23.44.15-client.txt](https://github.com/Virtuoel/Pehkui/files/5008986/crash-2020-07-31_23.44.15-client.txt)

**Comment by Virtuoel** [comment]
Carpet issue has been [fixed](https://github.com/gnembon/fabric-carpet/issues/352) on their end, but is unfortunately not yet released.

**Comment by Virtuoel** [comment]
OptiFine issue resolved in fce770849dd631c253f832064fd265d3dd9bb02e
