### ISSUE TITLE
[Suggestion] 1.16.4-1.16.1 forge port

### ISSUE THREAD

**Issue by arRk-byte** [Virtuoel/Pehkui#82]

**Comment by Dragonlord1005** [comment]
I think (not completely sure) that the 1.16.5 version will still work

**Comment by Virtuoel** [comment]
Unfortunately, supporting old minor 1.16.x Forge versions doesn't seem to be worth it anymore, especially when the latest for 1.16.5 has all sorts of bugfixes that those old ones don't have.
