### ISSUE TITLE
[bug] Crossing Portals (End/Nether) Breaks Player Until Relog

### ISSUE THREAD

**Issue by VaelophisNyx** [Virtuoel/Pehkui#83]
So about this, I've *scoured* the log files on my server and in singleplayer, and cannot find the cause. No errors, or warnings, related to this that I can find. There's a lot of mods, though.

so, if you walk through a portal or TP across dimensions, your body doesn't spawn, and your camera is stuck orbiting where it would have beeen. you cant move either.

relogging or saving and reloading in single player fixes it, but it's a rather disruptive bug

[latest.log](https://github.com/Virtuoel/Pehkui/files/6346779/latest.log)

**Comment by Virtuoel** [comment]
Can you check if your issue still occurs when using Pehkui 2.2.0?

**Comment by Seikm** [comment]
This exact same bug is happening to me on my server. I'm using the latest mod version (Pehkui-2.2.0+21w20a), and minecraft version is 1.16.5 with Fabric 0.7.3

**Comment by Virtuoel** [comment]
I am unable to reproduce this issue with Pehkui 3.1.0.
If the problem still occurs in Pehkui 3.1.0 or above, please open a new issue.
