### ISSUE TITLE
Why does it say something about command_api v1 or whatever

### ISSUE THREAD

**Issue by IAmAHumanToo** [Virtuoel/Pehkui#85]
The point is I cannot launch it in 1.16.3 and I am TOO LAZY TO UPDATE IT TO 1.16.5!!!

**Comment by Virtuoel** [comment]
Unfortunately the APIs needed for Pehkui to run did not yet exist in 1.16.3 Fabric API, and do exist in the 1.16.5 one. You should update anyways, since Mojang fixed some crash bugs in 1.16.5 as well.
