### ISSUE TITLE
[Fabric] My server crashes when my friend tries to join 

### ISSUE THREAD

**Issue by Showdows** [Virtuoel/Pehkui#90]
[crash-2021-04-27_00.44.22-server.txt](https://github.com/Virtuoel/Pehkui/files/6382603/crash-2021-04-27_00.44.22-server.txt)

I have no idea what happened, it was working earlier this week. My friend just recently when they tried to join the server crashed. Sorry I don't know what else to say. I have attached the crash report above.

**Comment by Virtuoel** [comment]
Can you try again with Pehkui 2.1.0 and let me know if this issue still occurs?

**Comment by Showdows** [comment]
> Can you try again with Pehkui 2.1.0 and let me know if this issue still occurs?

It doesn't happen anymore, Thanks!
