### ISSUE TITLE
Mixin Crash w/ Dungeons Gear

### ISSUE THREAD

**Issue by WenXin20** [Virtuoel/Pehkui#91]
`Minecraft v1.16.5`
`Forge v36.1.9`
`Pehkui v2.0.0`
`Dungeons Gear v3.0.6`

The game crashes on launch due to a mixin conflict.
[Crash Report](https://gist.github.com/WenXin20/563fd673ab0850876ce636e003ad9806)

**Comment by Jackiecrazy** [comment]
Fixed on our side.
