### ISSUE TITLE
[Fabric] Pehkui and Slime Origins: Whenever the player finally dies.

### ISSUE THREAD

**Issue by Retr089** [Virtuoel/Pehkui#92]
Hey, I'm wondering if this is a Pehkui error or an error that is with Slime Origins. If you died with the slime origins  mod and Pehkui, it crashes and spits out, "Error: java.lang.IllegalAccessError: tried to access field virtuoel.pehkui.api.PehkuiConfig.DATA from class net.minecraft.class_1309". This happens every single time and is easily replicable. Is there any fix for this? Here is a copy of my log. 
[crash-2021-04-28_19.25.23-server.txt](https://github.com/Virtuoel/Pehkui/files/6395486/crash-2021-04-28_19.25.23-server.txt)

**Comment by Virtuoel** [comment]
This is a Slime Origin issue (https://github.com/Jack-Sibley/slimeorigin/issues/5). They'll need to update the mod to use the new APIs that are in Pehkui versions 2.0.0 and newer.
