### ISSUE TITLE
My Immersive Portals does not work with this

### ISSUE THREAD

**Issue by gooblorshks** [Virtuoel/Pehkui#95]
I am using this with Immersive Portals and when I go through a bigger portal to exit out of a smaller one, I don't change size

**Comment by Virtuoel** [comment]
Are you using the Forge version? If you are, the Forge version of Immersive Portals hasn't added Pehkui compatibility yet.

**Comment by gooblorshks** [comment]
Oh, ok. Yeah, I am using the forge version
